# docker build -t YOUR_DOCKER_HUB_ID/react-app:latest -f Dockerfile.prod .
# docker run -p 3000:80 YOUR_DOCKER_HUB_ID/react-app:latest
FROM node:16-alpine as builder

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
# Copy over sth from another phase (builder)
COPY --from=builder /app/build /usr/share/nginx/html
