# docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 123987109832/react-app:latest
FROM node:16-alpine

WORKDIR '/app'

COPY ./package.json ./
RUN npm install
# COPY . .

CMD ["npm", "start"]