'use strict';

var PROD_NAME = "Trend Micro™ Home Network Security";
var PROD_NAME_SHORT = "Home Network Security";

module.exports = {
  PROD_NAME: PROD_NAME,
  PROD_NAME_SHORT: PROD_NAME_SHORT,
  SPLASH_LOGO: "image_hns_lockup",
  UNKNOWN: "Detected Device",
  ON: "On",
  OFF: "Off",

  PRIVACY_POLICY_LINK: "https://www.trendmicro.com/en_us/about/legal/privacy-policy-product.html",

  LEARN_MORE: "Learn more",
  TURN_ON_NOW: "Turn on now",
  OR: "or",
  CLOSE: "Close",
  COUNTRY_DATA: {
    '248': 'Aland',
    '4': 'Afghanistan',
    '8': 'Albania',
    '12': 'Algeria',
    '16': 'American Samoa',
    '20': 'Andorra',
    '24': 'Angola',
    '660': 'Anguilla',
    '28': 'Antigua and Barbuda',
    '32': 'Argentina',
    '51': 'Armenia',
    '533': 'Aruba',
    '36': 'Australia',
    '40': 'Austria',
    '31': 'Azerbaijan',
    '44': 'Bahamas',
    '48': 'Bahrain',
    '50': 'Bangladesh',
    '52': 'Barbados',
    '112': 'Belarus',
    '56': 'Belgium',
    '84': 'Belize',
    '204': 'Benin',
    '60': 'Bermuda',
    '64': 'Bhutan',
    '68': 'Bolivia',
    '70': 'Bosnia and Herzegovina',
    '72': 'Botswana',
    '76': 'Brazil',
    '96': 'Brunei',
    '100': 'Bulgaria',
    '854': 'Burkina Faso',
    '104': 'Burma (Myanmar)',
    '108': 'Burundi',
    '116': 'Cambodia',
    '120': 'Cameroon',
    '124': 'Canada',
    '132': 'Cape Verde',
    '136': 'Cayman Islands',
    '140': 'Central African Republic',
    '148': 'Chad',
    '152': 'Chile',
    '156': 'China',
    '170': 'Colombia',
    '162': 'Christmas Island',
    '166': 'Cocos (Keeling) Islands',
    '174': 'Comoros',
    '180': 'Congo, Democratic Republic of',
    '178': 'Congo, Republic of',
    '184': 'Cook Islands',
    '188': 'Costa Rica',
    '384': "Cote d'Ivoire",
    '191': 'Croatia',
    '196': 'Cyprus',
    '203': 'Czech Republic',
    '208': 'Denmark',
    '262': 'Djibouti',
    '212': 'Dominica',
    '214': 'Dominican Republic',
    '626': 'East Timor',
    '218': 'Ecuador',
    '818': 'Egypt',
    '222': 'El Salvador',
    '226': 'Equatorial Guinea',
    '232': 'Eritrea',
    '233': 'Estonia',
    '231': 'Ethiopia',
    '238': 'Falkland Islands',
    '234': 'Faroe Islands',
    '242': 'Fiji',
    '246': 'Finland',
    '250': 'France',
    '254': 'French Guiana',
    '258': 'French Polynesia',
    '266': 'Gabon',
    '270': 'Gambia',
    '268': 'Georgia',
    '276': 'Germany',
    '288': 'Ghana',
    '292': 'Gibraltar',
    '300': 'Greece',
    '304': 'Greenland',
    '308': 'Grenada',
    '316': 'Guam',
    '320': 'Guatemala',
    '831': 'Guernsey',
    '324': 'Guinea',
    '624': 'Guinea-Bissau',
    '328': 'Guyana',
    '332': 'Haiti',  
    '340': 'Honduras',
    '344': 'Hong Kong',
    '348': 'Hungary',
    '352': 'Iceland',
    '356': 'India',
    '360': 'Indonesia',
    '368': 'Iraq',
    '372': 'Ireland',
    '833': 'Isle of Man',
    '376': 'Israel',
    '380': 'Italy',
    '388': 'Jamaica',
    '392': 'Japan',
    '832': 'Jersey',
    '400': 'Jordan',
    '398': 'Kazakhstan',
    '404': 'Kenya',
    '296': 'Kiribati',
    '410': 'Korea, Republic of (South)',
    '414': 'Kuwait',
    '417': 'Kyrgyzstan',
    '418': 'Laos',
    '428': 'Latvia',
    '422': 'Lebanon',
    '426': 'Lesotho',
    '430': 'Liberia',
    '438': 'Liechtenstein',
    '440': 'Lithuania',
    '442': 'Luxembourg',
    '446': 'Macao',
    '807': 'Macedonia',
    '450': 'Madagascar',
    '454': 'Malawi',
    '458': 'Malaysia',
    '462': 'Maldives',
    '466': 'Mali',
    '470': 'Malta',
    '584': 'Marshall Islands',
    '478': 'Mauritania',  
    '480': 'Mauritius',
    '175': 'Mayotte',
    '484': 'Mexico',
    '583': 'Micronesia, Federated States of',
    '498': 'Moldova',
    '492': 'Monaco',
    '496': 'Mongolia',
    '9891': 'Montenegro',
    '500': 'Montserrat',
    '504': 'Morocco',
    '508': 'Mozambique',
    '580': 'N. Mariana Islands',
    '516': 'Namibia',
    '520': 'Nauru',
    '524': 'Nepal',
    '528': 'Netherlands',
    '530': 'Netherlands Antilles',
    '540': 'New Caledonia',
    '554': 'New Zealand',
    '558': 'Nicaragua',
    '562': 'Niger',
    '566': 'Nigeria',
    '570': 'Niue',
    '574': 'Norfolk Island',
    '578': 'Norway',
    '512': 'Oman',
    '586': 'Pakistan',
    '585': 'Palau',
    '591': 'Panama',
    '598': 'Papua New Guinea',
    '600': 'Paraguay',
    '604': 'Peru',
    '608': 'Philippines',  
    '612': 'Pitcairn',
    '616': 'Poland',
    '620': 'Portugal',
    '630': 'Puerto Rico',
    '634': 'Qatar',
    '638': 'Reunion',
    '642': 'Romania',
    '643': 'Russia Federation',
    '646': 'Rwanda',
    '654': 'Saint Helena',
    '659': 'Saint Kitts and Nevis',
    '662': 'Saint Lucia',
    '666': 'Saint Pierre and Miquelon',
    '670': 'Saint Vincent and the Grenadines',
    '882': 'Samoa',
    '674': 'San Marino',
    '678': 'Sao Tome and Principe',
    '682': 'Saudi Arabia',
    '686': 'Senegal',
    '891': 'Serbia',
    '690': 'Seychelles',
    '694': 'Sierra Leone',
    '702': 'Singapore',
    '703': 'Slovakia',
    '705': 'Slovenia',
    '90': 'Solomon Islands',
    '706': 'Somalia',
    '710': 'South Africa',
    '724': 'Spain',
    '144': 'Sri Lanka',
    '740': 'Suriname',
    '744': 'Svalbard',
    '748': 'Swaziland',
    '752': 'Sweden',
    '756': 'Switzerland',
    '158': 'Taiwan',
    '762': 'Tajikistan',
    '834': 'Tanzania',
    '764': 'Thailand',
    '768': 'Togo',
    '772': 'Tokelau',
    '776': 'Tonga',
    '780': 'Trinidad and Tobago',
    '788': 'Tunisia',
    '792': 'Turkey',
    '795': 'Turkmenistan',
    '796': 'Turks and Caicos Islands',
    '798': 'Tuvalu',
    '800': 'Uganda',
    '804': 'Ukraine',
    '784': 'United Arab Emirates',
    '826': 'United Kingdom',
    '840': 'United States',
    '858': 'Uruguay',
    '860': 'Uzbekistan',
    '548': 'Vanuatu',
    '336': 'Vatican City State',
    '862': 'Venezuela',
    '704': 'Vietnam',
    '92': 'Virgin Islands, British',
    '850': 'Virgin Islands, US',
    '876': 'Wallis and Futuna',
    '732': 'Western Sahara',
    '887': 'Yemen',
    '894': 'Zambia',
    '716': 'Zimbabwe',
  },
  FROM_TO: "From {0} to {1}",
  TO: "{0} to {1}",
  AT: "At {0}",
  AND: "and",
  VIEW_ALL: "View all",
  LOCALE_H: "h A",
  LOCALE_LT: "hh:mm A",
  LOCALE_L: "MMM. DD",
  LOCALE_LL: "MMM. YYYY",
  LOCALE_LLL: "MMM. DD, YYYY",
  LOCALE_LLLL: "MMM. DD, YYYY HH:mm:ss",
  LOCALE_TODAY: "Today",
  LOCALE_YESTERDAY: "Yesterday",
  LOCALE_TOMORROW: "tomorrow",
  HOUR_UNIT: "{0} hour",
  HOUR: "1 hour",
  HOURS: "{0} hours",
  MINUTE_UNIT: "{0} minute",
  MINUTE: "1 minute",
  MINUTES: "{0} minutes",
  MINUTE_CAP:"1 Minute",
  MINUTES_CAP:"{0} Minutes",
  HOUR_CAP:"1 Hour",
  HOURS_CAP:"{0} Hours",
  DURATION_H: "{0}h",
  DURATION_M: "{0}m",
  YEARLY: "Yearly",
  MONTHLY: "Monthly",
  LESS_THAN:"less than",
  INTERNET_USE_ONLINE:"Online",
  DURATION_ONLINE: "Online {0}",
  DURATION_OFFLINE: "Offline {0}",
  UPDATED: "Updated",
  UPDATING: "Updating",
  PAUSE: "Pause",
  RESUME: "Resume",
  STATUS_BAR_STATION_OFFLINE_TITLE: "The station is offline",
  STATUS_BAR_STATION_OFFLINE_TITLE_POPUP: "Your Station Is Offline",
  STATUS_BAR_STATION_OFFLINE_DESC: "Please connect your Station to the Internet to update the settings.",
  STATUS_BAR_NO_INTERNET_TITLE: "No Internet connection available",
  STATUS_BAR_NO_INTERNET_TITLE_POPUP: "Please Connect to Internet",
  STATUS_BAR_NO_INTERNET_DESC: "Make sure that your device can reach the Internet and try again.",
  STATUS_BAR_STATION_UPDATING_TITLE: "The Station is updating",
  STATUS_BAR_STATION_UPDATING_DESC: "Please wait until the update is complete and try again",
  STATUS_BAR_STATION_EXPIRED_RENEW_TITLE: "Subscription Expired. <a href=http://renew>Renew now</a>",
  STATUS_BAR_STATION_EXPIRED_TITLE: "Subscription Expired. <a href=http://contact-support>Contact {0}</a>",
  STATUS_BAR_STATION_EXPIRED_TITLE_ANZ: "Visit your <a href=http://contact-support>Trend Micro Account</a> to renew",
  TOAST_THANKS_FEEDBACK: "Thank you for your feedback",
  TOAST_SAVED: "Saved",
  TOAST_CACHE_CLEARED: "Cache cleared",
  TOAST_SUBSCRIPTION_EXPIRES: "Subscription Expires",
  TOAST_SUBSCRIPTION_EXPIRES_JP: "Expires",
  TOAST_SUBSCRIPTION_EXPIRED: "Subscription Expired",
  TOAST_SUBSCRIPTION_EXPIRED_JP: "Expired",
  TOAST_SUBSCRIPTION_EXPIRE_JP: "Please sign into your <a href=http://sso>Trend Micro Account</a> or tap Renew Now.",
  TOAST_SUBSCRIPTION_EXPIRE_ANZ: "Sign into your <a href=http://sso>Trend Micro Account</a> to renew.",
  TOAST_CONTACT_SUPPORT: "Please check your email or <a href=http://contact-support>contact {0}</a> for assistance.",
  TOAST_CONTACT_SUPPORT_JP: "Please check your email or sign into your <a href=http://sso>Trend Micro Account</a> to renew your subscription.",
  TOAST_ONE_RULE_PER_DAY: "One rule per day",
  TOAST_REMOVED_FROM_APPROVED_LIST: "Removed from Approved List",
  TOAST_DEVICE_SETTING_SAVED: "{0} settings saved",
  TOAST_DEVICE_BLOCKED: "{0} blocked",
  TITLE_SECTION_DASHBOARD: "Dashboard",
  TITLE_SECTION_TIMELINE: "Timeline",
  TITLE_SECTION_DEVICES: "Devices",
  TITLE_SECTION_FAMILY: "Family",
  TITLE_SECTION_NETWORK: "Network",
  TITLE_SECTION_SETTINGS: "Settings",
  TITLE_SECTION_TUTORIALS: "Tutorials",
  TITLE_SECTION_COMMUNITY: "Community",
  TITLE_SECTION_HELP: "Help",
  ACTION_BAR_DONE: "Done",
  ACTION_BAR_SKIP: "Skip",
  ACTION_BAR_NEXT: "Next",
  ACTION_BAR_OK: "OK",
  DIALOG_CONFIRM_YES: "Yes",
  DIALOG_CONFIRM_NO: "No",
  DIALOG_CONFIRM_OK: "OK",
  DIALOG_CONFIRM_CANCEL: "Cancel",
  DIALOG_CONFIRM_DISCONNECT: "End",
  DIALOG_CONFIRM_RESET: "Reset",
  DIALOG_CONFIRM_NOT_NOW: "Not Now",
  DIALOG_CONFIRM_SET_UP: "Set Up",
  DIALOG_CONFIRM_CHANGE: "Change",
  DIALOG_CONFIRM_CLOSE: "Close",
  DIALOG_CONFIRM_ASSIGN: "Assign",
  DIALOG_CONFIRM_JOIN: "Join",
  DIALOG_CONFIRM_REFRESH: "Refresh",
  DIALOG_CONFIRM_GET_HELP: "Get Help",
  DIALOG_CONFIRM_SELECT: "Select",
  DIALOG_CONFIRM_CONTINUE: "Continue",
  DIALOG_CONFIRM_CONTINUE_ALTER: "Continue",
  DIALOG_CONFIRM_ACCEPT_AND_CONTINUE: "Accept and Continue",
  DIALOG_CONFIRM_DELETE: "Delete",
  DIALOG_CONFIRM_NEXT: "Next",
  DIALOG_CONFIRM_EDIT: "Edit",
  DIALOG_CONFIRM_BACK: "Back",
  DIALOG_LINK_LEARNMORE: "Learn More",
  DIALOG_LINK_FEEDBACK: "Give Feedback",
  ERROR_MAINTENENCE: "Sorry for the Inconvenience",
  ERROR_MAINTENENCE_DETAIL: "Due to maintenance, the system is unavailable right now. Please try again after {0}.",
  ERROR_MAINTENENCE_UNKNOWN_DETAIL: "Due to maintenance, the system is unavailable right now. Please try again later.",
  ERROR_NO_MAIL_ACCOUNT: "No Mail Account Found",
  ERROR_NO_MAIL_ACCOUNT_DETAIL: "Please set up a mail account and try again.",
  ERROR_CAMERAROLL_UNAVAILABLE: "Cannot Access Photos",
  ERROR_CAMERAROLL_UNAVAILABLE_DETAIL: "Please tap Settings and allow the app access to your photos. If you continue to see this message, please contact Support for help.",
  ERROR_GENERAL: "Unable to Continue",
  ERROR_GENERAL_DETAIL: "Please try again. <a href=http://help>Get Help</a>. (Error code: {0})",
  WELCOME_TITLE: "Welcome",
  WELCOME_SUBTITLE: PROD_NAME + " protects your devices and data by blocking unwanted intrusions.",
  WELCOME_ACCEPT: "Accept and Continue",
  WELCOME_EULA: "By installing this app, you accept the terms of <a href=http://agree>Trend Micro License Agreement</a>.",
  WELCOME_UBM_TITLE: "Help Make Improvements",
  WELCOME_UBM_DETAIL: "You have the option to share anonymous usage and crash data with Trend Micro to help improve this app by marking the checkboxes below. Deciding not to mark the checkboxes will not affect the capabilities or effectiveness of " + PROD_NAME_SHORT + ".",
  GDPR_TITLE: "Privacy and Personal Data Collection Disclosure",
  GDPR_DETAIL: "Certain features available in " + PROD_NAME + " collect and send feedback data regarding product usage and detection information to Trend Micro. Some of the data may be considered personal data in certain jurisdictions and under certain regulations.\n\nBy installing " + PROD_NAME + ", the following data will be provided to Trend Micro so that we can protect your online activity:\nEmail Address\nPassword\nFirst name\nLast name\nLanguage\nPhone Number\n\nYou may opt out of having some of these data being provided to Trend Micro by disabling those data collecting functions. Please refer to " + PROD_NAME + "’s <a href=DCN>Data Collection Notice</a> for details of how to disable data collection functions. Please note that certain data collecting functions cannot be disabled.\n\nFor more information on how we collect data, please refer to Trend Micro’s <a href=privacy>Privacy Policy</a>.",
  GDPR_MESSAGE: "Please review our Privacy Policy and Data Collection Notice",
  GDPR_UBM: "I agree to share anonymous usage data to help improve this app",
  GDPR_CRASH_REPORT: "I agree to share anonymous crash data to help improve this app",
  PRIVACY_POLICY: "Trend Micro Privacy Policy",
  DATA_COLLECTION: "Data Collection Notice",
  REMOTE_PAIRING_TITLE: "Connect to the Station",
  REMOTE_PAIRING_INSTRUCTION: "Type the Pairing Code. The Pairing Code is case-sensitive.",
  REMOTE_PAIRING_HINT: "Looking for the Pairing Code?",
  LAN_PAIRING_TITLE: "Connecting to the Station",
  LAN_PAIRING_INSTRUCTION: "Please keep your Station online and connect your phone to the same Wi-Fi network as the Station. Connecting to the Station may take a few minutes to complete. <a href='pairing'>Learn more</a>",
  LAN_PAIRING_ERROR_NO_INTERNET: "Please Connect to Wi-Fi",
  LAN_PAIRING_ERROR_NO_INTERNET_DETAIL: "Please connect this device to the same Wi-Fi network as the online Station and try again.",
  LAN_PAIRING_ERROR_OVERSEAT: "Connection Unsuccessful",
  LAN_PAIRING_ERROR_OVERSEAT_DETAIL: "Please check your Pairing Code or connect to a different Station and try again. <a href=http://overseat>Get Help</a>. (Error code: {0})",
  LAN_PAIRING_ERROR_INCORRECT_PAIRING_CODE: "Incorrect Pairing Code",
  LAN_PAIRING_ERROR_INCORRECT_PAIRING_CODE_DETAIL: "Please check your Pairing Code and try again. <a href=http://incorrect-pairing-code>Get Help</a>. (Error code: {0})",
  LAN_PAIRING_ERROR_INCORRECT_STATION_CODE: "Incorrect Station Code",
  LAN_PAIRING_ERROR_INCORRECT_STATION_CODE_DETAIL: "Please scan your Station Code again. <a href=http://incorrect-station-code>Get Help</a>. (Error code: {0})",
  LAN_PAIRING_ERROR_BOX_OFFLINE: "Connection Unsuccessful",
  LAN_PAIRING_ERROR_BOX_OFFLINE_DETAIL: "1. Make sure the Station is plugged into your router’s LAN port.\n2. Wait until the light on your Station becomes green.",
  LAN_PAIRING_ERROR_NOT_SAME_WIFI: "Please Go to Your Station",
  LAN_PAIRING_ERROR_NOT_SAME_WIFI_DETAIL: "You will need to scan the Station Code with your phone.",
  LAN_PAIRING_ERROR_RETURNED_PAIRING_CODE: "Returned Pairing Code",
  LAN_PAIRING_ERROR_RETURNED_PAIRING_CODE_DETAIL: "This Pairing Code was returned. Please try again with a different Pairing Code. <a href=http://returned-pairing-code>Get Help</a>. (Error code: {0})",
  BOX_STATUS_TITLE: "Updating Station",
  BOX_STATUS_DESC_1: "The Station may go offline and the Station light may turn red during the update. <a href='updating'>Learn more</a>",
  BOX_STATUS_DESC_2: "The Station may go offline and the Station light may turn red during the update, please keep Station plugged in. <a href='waiting'>Learn more</a>",
  BOX_STATUS_ERROR: "Please <a href='get-support'>contact Support</a> and give them the error code: {0}",
  BOX_STATUS_OFFLINE_TITLE: "Reconnect Your Station",
  BOX_STATUS_OFFLINE_DESC: "Please check that the Station is plugged into the LAN port of the router and try again. <a href='offline'>Learn more</a>",
  BOX_STATUS_NO_INTERNET_TITLE: "No Internet Connection",
  BOX_STATUS_NO_INTERNET_DESC: "Please reconnect this device to the Internet to finish the Station update. <a href='no-internet'>Learn more</a>",
  BOX_STATUS_UPDATED: "Station Update Successful",
  BOX_STATUS_STATION_DETECTING: "Detecting Station",
  BOX_STATUS_CHECKING_STATION: "Checking Station",
  BOX_STATUS_EXTRACTING: "Extracting",
  BOX_STATUS_DECRYPTING: "Decrypting",
  BOX_STATUS_VERIFYING: "Verifying",
  BOX_STATUS_STATION_UPDATING: "Station updating",
  BOX_STATUS_UPDATING: "Updating",
  BOX_STATUS_CONTINUE_UPDATE: "Continuing update",
  BOX_STATUS_KEEP_PLUG_IN: "Keep Station plugged in",
  PAIRING_TITLE: "Scan the Station Code",
  PAIRING_SUBTITLE_SCAN: "Scan the Station Code on the label of the Station. The label can be found on the bottom of the Station. <a href=http://more>Learn More</a>",
  PAIRING_SCAN_NOW: "Scan Now",
  PAIRING_SUCCESS: "Connection Successful",
  PAIRING_CAMERA_UNAVAILABLE_TITLE: "Camera Unavailable",
  PAIRING_CAMERA_UNAVAILABLE_MESSAGE: "Please make sure that the app can access the camera. If you continue to see this message, please contact Support for help.",
  ACCOUNT_INFO_EMAIL: "Email Address",
  ACCOUNT_INFO_EMAIL_ALTER: "Email",
  ACCOUNT_INFO_PWD: "Password",
  ACCOUNT_INFO_FNAME: "First Name",
  ACCOUNT_INFO_LNAME: "Last Name",
  ACCOUNT_INFO_FULLNAME: "Name",
  ACCOUNT_INFO_COUNTRY: "Country",
  ACCOUNT_INFO_PHONE: "Phone Number",
  ACCOUNT_INFO_ERROR_NO_DATA: "Required.",
  ACCOUNT_INFO_ERROR_WRONG_EMAIL_FORMAT: "Incorrect email format.",
  ACCOUNT_INFO_ERROR_EMAIL_EXIST: "Address already used. <a href='http://signin'>Sign in instead</a>",
  ACCOUNT_INFO_ERROR_WRONG_NAME_FORMAT: "Please do not use the following special characters: / \\ * ? \" < > | & :",
  ACCOUNT_INFO_ERROR_WRONG_PWD_FORMAT: "Please use at least 8 characters.",
  ACCOUNT_INFO_ERROR_WRONG_PWD_FORMAT2: "Use only letters, numbers and the following special characters: @ . - _ ",
  ACCOUNT_INFO_ERROR_WRONG_PWD_NOT_MATCH: "The passwords do not match.",
  ACCOUNT_INFO_ERROR_WRONG_PHONE_FORMAT: "Please use 3 to 15 numbers.",
  ACCOUNT_INFO_ERROR_NUMBER_ONLY: "Please only use numbers",
  SIGNIN_TITLE: "Sign In",
  SIGNIN_DESC: "Sign into your Trend Micro Account to start using " + PROD_NAME,
  SIGNIN_DESC_ALTER: "Sign into your Trend Micro Account to use " + PROD_NAME,
  SIGNIN_FORGET_PWD: "Forgot your password?",
  SIGNIN_BUTTON: "Sign In",
  SIGNIN_NEED_ACCOUNT: "Need a Trend Micro Account?",
  SIGNIN_CREATE_ACCOUNT: "Create an account",
  SIGNIN_ERROR: "Unable to Sign In",
  SIGNIN_ERROR_DETAIL: "Please provide the correct email address and password.",
  SIGNIN_ERROR_DETAIL_ALTER: "Please check your password and try again.",
  SIGNUP_TITLE: "Create Account",
  SIGNUP_DESC: "Create a Trend Micro account to start using " + PROD_NAME + ".",
  SIGNUP_DESC_LINK: "Or <a href='http://signin'>sign in instead</a>.",
  SIGNUP_PWD_DESC: "Confirm your email address",
  SIGNUP_CREATE_PWD: "Create a password",
  SIGNUP_PWD: "Password",
  SIGNUP_CONFIRM_PWD: "Confirm Password",
  SIGNUP_PWD_HINT: "Please use at least 8 characters.",
  SIGNUP_RECEIVE_NEWS: "Receive the latest news and offers from Trend Micro",
  SIGNUP_BUTTON: "Create Account",
  LOGIN: "Sign In",
  TUTORIAL_TIMELINE: "Keep Track Using the Timeline",
  TUTORIAL_TIMELINE_DESC: "You can see security events, as well as newly connected devices. Tap on an event to find out more.",
  TUTORIAL_DEVICE: "See Who Is Connected Using Devices",
  TUTORIAL_DEVICE_DESC: "View and manage all of the devices that are online right now.",
  TUTORIAL_FAMILY: "Safe Internet for Your Family",
  TUTORIAL_FAMILY_DESC: "Decide what your kids can see online, and when they can use the Internet.",
  TUTORIAL_ANTIVIRUS: "Use with Your Anti-Virus Software",
  TUTORIAL_ANTIVIRUS_DESC: "PCs and phones still need protection on-the-go and advanced security, so continue to use anti-virus.",
  TUTORIAL_TRY_IT_NOW: "Try It on This Device",
  TUTORIAL_TRY_DIFF_DEVICE: "Try a Different Device",
  TUTORIAL_WTP_TITLE: "Protection from Dangerous Websites",
  TUTORIAL_WTP_DESC: PROD_NAME_SHORT + " brings world-class web threat protection to your home network, which prevents attacks from reaching your connected devices.",
  TUTORIAL_WTP_STEP1: "Connect your device to the same network as the Station.",
  TUTORIAL_WTP_STEP2: "Go to this website with your connected device to see how " + PROD_NAME + " protects you:",
  TUTORIAL_CONNECT_TO_TEST_TITLE: "Connect to Test",
  TUTORIAL_CONNECT_TO_TEST_MESSAGE: "To open the website, connect your device to the same Wi-Fi network as the Station, and try again.",
  BOX_RESET_TITLE: "Connect to the Station",
  BOX_RESET_DESC: "Your Station was reset. Please reconnect, or connect to a new Station. <a href=http://set-up-new>Get Help</a>",
  AFTER_RMA_TITLE: "Connect to the Station",
  AFTER_RMA_DESC: "Your Station was returned. Please connect to a new Station. <a href=http://set-up-new>Get Help</a>",
  REFUND_TITLE: "Connect to the Station",
  REFUND_DESC: "The Station was returned. Please connect to a new Station. <a href=http://set-up-new>Get Help</a>",
  EOLA_TITLE: "Unable to Continue",
  EOLA_DESC: "Please contact <a href=http://vendor>{0}</a> for help.",
  EOLA_PAIRING_CODE: "Pairing Code",
  EOLA_SET_UP_NEW: "Or you can <a href=http://set-up-new>set up a new Station</a>.",
  EOLB_TITLE: "Thank you for your use of " + PROD_NAME,
  EOLB_DESC: "Service for " + PROD_NAME + " is now discontinued. If you have any questions, please contact <a href=http://vendor>{0}</a>.",
  UPDATE_NEEDED_TITLE: "Update Needed",
  UPDATE_NEEDED_DESC: "Please click the button below to get the latest version. <a href=http://update-needed>Learn more</a>",
  UPDATE_NEEDED_ACTION: "Update Now",
  DEVICE_UPDATE_NEEDED_TITLE: "Device Update Needed",
  DEVICE_UPDATE_NEEDED_DESC: "Please update your device to {0} {1} to continue using the " + PROD_NAME + " app. <a href=http://update-needed>Learn more</a>",
  PUG_BLOCK_OPTIN_TITLE: "Power User Group App Needed",
  PUG_BLOCK_OPTIN_DESC: "You have joined the Power User Group. Please install the Power User Group app.",
  PUG_BLOCK_OPTOUT_TITLE: "Thank You",
  PUG_BLOCK_OPTOUT_DESC: "You have left the Power User Group. Please install the " + PROD_NAME + " app.",
  ACTION_REQUIRED_TITLE: "Action Required",
  UNSECURED: "Unsecured",
  DEVICE_ADDME_TITLE_0: "Similar Device?",
  DEVICE_ADDME_SUBTITLE_0: "Using the device you want to identify, connect to the same network as the Station and go to: http:// addme.tm. You can add or update the name of your device.",
  DEVICE_ADDME_IMAGE_0: "bg_device_identify_a0",
  DEVICE_ADDME_TITLE_1: "Identify Your Devices Faster",
  DEVICE_ADDME_SUBTITLE_1: "When you turn on and use your devices, " + PROD_NAME + " can more easily identify them.",
  DEVICE_ADDME_TITLE_2: "Adding a Device?",
  DEVICE_ADDME_SUBTITLE_2: "Using the device you want to add, connect to the same network as the Station and go to: http://addme.tm. You can add or update the name of your device.",
  DEVICE_ADDME_DESC: PROD_NAME + " is identifying {0} devices...",
  DEVICE_ADDME_DESC_SINGLE: PROD_NAME + " is identifying {0} device...",
  DEVICE_ACCESS_REQUEST: "Request from {0} to join the network",
  DEVICE_ACCESS_UNKNOWN: "a new device",
  DEVICE_ACCESS_DETECTED: "Detected Time",
  DEVICE_ACCESS_ALLOW: "Allow Connection",
  DEVICE_ACCESS_BLOCK: "Block",
  DEVICE_UNASSIGNED: "Unassigned",
  DEVICE_UNASSIGNED_SUBTITLE: "These devices are protected from security threats and have unrestricted Internet access.",
  DEVICE_PRIMARY_ROUTER: "Primary Router",
  DEVICE_NO_DEVICES: "No connected devices.",
  DEVICE_NO_ONLINE_DEVICES: "No online devices",
  DEVICE_SHOW_ALL_DEVICES: "All Devices",
  DEVICE_SHOW_ONLINE_DEVICES: "Online Devices",
  DEVICE_BTN_SHOW_ALL_DEVICES: "Show all devices",
  DEVICE_BTN_SHOW_ONLINE_DEVICES: "Only show online devices",
  DEVICE_TAB_REPORT: "Report",
  DEVICE_TAB_SETTINGS: "Settings",
  DEVICE_SETTINGS_OWNER: "Owner",
  DEVICE_SETTINGS_OWNER_HINT: "Choose an owner",
  DEVICE_SETTINGS_OWNER_NEW_DEVICE: "Choose an Owner",
  DEVICE_SETTINGS_OWNER_ALLOWED_HINT: "{0} connection allowed. Choose an owner to manage this device.",
  DEVICE_SETTINGS_REMOVE_OWNER: "Move to Unassigned",
  DEVICE_SETTINGS_DEVICE_NAME: "Name",
  DEVICE_SETTINGS_DEVICE_NAME_HINT: "Add device name",
  DEVICE_SETTINGS_DEVICE_NAME_DETECTED: "Device hostname detected by " + PROD_NAME_SHORT + ": {0}",
  DEVICE_SETTINGS_TYPE: "Type",
  DEVICE_SETTINGS_TYPE_HINT: "Add device type",
  DEVICE_SETTINGS_TYPE_OTHER: "Other",
  DEVICE_SETTINGS_TYPE_CAMERA: "IP Camera",
  DEVICE_SETTINGS_TYPE_NAS: "File Server",
  DEVICE_SETTINGS_TYPE_ROUTER: "Router",
  DEVICE_SETTINGS_TYPE_PC: "Windows PC",
  DEVICE_SETTINGS_TYPE_MAC: "Mac",
  DEVICE_SETTINGS_TYPE_IPHONE: "iPhone",
  DEVICE_SETTINGS_TYPE_PRINTER: "Printer",
  DEVICE_SETTINGS_TYPE_GAME_CONSOLE: "Game Console",
  DEVICE_SETTINGS_TYPE_TV: "TV",
  DEVICE_SETTINGS_TYPE_ANDROID_PHONE: "Android Phone",
  DEVICE_SETTINGS_TYPE_IPAD: "iPad",
  DEVICE_SETTINGS_TYPE_TABLET: "Tablet",
  DEVICE_SETTINGS_TYPE_NOTEBOOK: "Windows Notebook",
  DEVICE_SETTINGS_TYPE_JEWELRY_BOX: "JewelryBox",
  DEVICE_SETTINGS_TYPE_KINDLE: "E-reader",
  DEVICE_SETTINGS_TYPE_PHONE: "Phone",
  DEVICE_SETTINGS_TYPE_MEDIA_DEVICE: "Media Device",
  DEVICE_SETTINGS_TYPE_MACBOOK: "MacBook",
  DEVICE_SETTINGS_TYPE_HOME_CONTROLLER: "Smart Home Controller",
  DEVICE_SETTINGS_TYPE_WIFI_SPEAKER: "Wireless Speakers",
  DEVICE_SETTINGS_TYPE_HUB: "Hub",
  DEVICE_SETTINGS_TYPE_ROBOT: "Robot",
  DEVICE_SETTINGS_TYPE_PLUG: "Smart Plug",
  DEVICE_SETTINGS_TYPE_WATCH: "Smartwatch",
  DEVICE_SETTINGS_TYPE_THERMOSTAT: "Smart Thermostat",
  DEVICE_SETTINGS_TYPE_LIGHT_BULB: "Light Bulb",
  DEVICE_SETTINGS_TYPE_WEIGHT_METER: "Scale",
  DEVICE_SETTINGS_TYPE_AIR_PURIFIER: "Air Purifier",
  DEVICE_SETTINGS_TYPE_3DS: "3DS",
  DEVICE_SETTINGS_TYPE_REFRIGERATOR: "Refrigerator",
  DEVICE_SETTINGS_TYPE_PLAYSTATION: "PlayStation",
  DEVICE_SETTINGS_TYPE_AMAZON_ECHO: "Echo",
  DEVICE_SETTINGS_TYPE_GOOGLE_HOME: "Home",
  DEVICE_SETTINGS_TYPE_NINTENDO_SWITCH: "Nintendo Switch",
  DEVICE_SETTINGS_TYPE_XBOX_ONE: "Xbox One",
  DEVICE_SETTINGS_TYPE_HOME_POD: "HomePod",
  DEVICE_SETTINGS_TYPE_DOORBELL: "Smart Doorbell",
  DEVICE_SETTINGS_TYPE_BABY_MONITOR: "Baby Monitor",
  DEVICE_SETTINGS_TYPE_COOKING: "Smart Cooking Device",
  DEVICE_SETTINGS_TYPE_DOOR_SECURITY_CAMERA: "Indoor Security Camera",
  DEVICE_SETTINGS_TYPE_IROBOT: "Vacuum Cleaner",
  DEVICE_SETTINGS_TYPE_LIGHTS_SWITCH: "Light Switch",
  DEVICE_SETTINGS_TYPE_OUTDOOR_SECURITY_CAMERA: "Outdoor Security Camera",
  DEVICE_SETTINGS_TYPE_REMOTE_CONTROL: "Remote Control",
  DEVICE_SETTINGS_TYPE_SMART_SPRINKLERS: "Sprinklers",
  DEVICE_SETTINGS_TYPE_SMART_BTN: "Smart Button",
  DEVICE_SETTINGS_TYPE_SMART_CAR: "Car",
  DEVICE_SETTINGS_TYPE_PET_CAMERA_FEEDER: "Pet Feeder / Camera",
  DEVICE_SETTINGS_TYPE_SMART_DOOR_LOCK: "Smart Lock",
  DEVICE_SETTINGS_TYPE_TV_STICK: "TV Stick",
  DEVICE_SETTINGS_TYPE_AUDIO_RECEIVER: "Audio Receiver",
  DEVICE_SETTINGS_TYPE_SMART_HOME_HUB: "Smart Home Hub",
  DEVICE_SETTINGS_TYPE_SMOKE_DETECTOR: "Smoke Detector",
  DEVICE_SETTINGS_TYPE_BLURAY_PLAYER: "Blu-ray / DVD player",
  DEVICE_SETTINGS_TYPE_SMART_SPEAKER_GENERIC: "Smart Speaker",
  DEVICE_SETTINGS_ADDME_TITLE: "Identify this device",
  DEVICE_SETTINGS_ADDME_DESC: "Tap Learn More to see how to identify this device faster.",
  DEVICE_SETTINGS_SIMILAR_TITLE: "Modify the device description",
  DEVICE_SETTINGS_SIMILAR_DESC: "Read about how to modify the description of this device",
  DEVICE_SETTINGS_UNSECURED_TITLE: "Unsecured Device",
  DEVICE_SETTINGS_UNSECURED_DESC: "To turn on protection, and remove the device from the Unsecured Devices List, tap Remove.",
  DEVICE_SETTINGS_UNSECURED_REMOVE: "Remove",
  DEVICE_SETTINGS_UNSECURED_MODIFY_HINT: "Device Moved",
  DEVICE_SETTINGS_UNSECURED_MODIFY_HINT_DETAIL: "It may take up to 5 minutes for the device to reconnect to your router, or you can reboot the device to reconnect immediately.",
  DEVICE_SETTINGS_BRAND: "Brand",
  DEVICE_SETTINGS_BRAND_HINT: "Add device brand",
  DEVICE_SETTINGS_MODEL: "Model",
  DEVICE_SETTINGS_MODEL_HINT: "Add device model",
  DEVICE_SETTINGS_PORTS: "Active Ports",
  DEVICE_SETTINGS_PORTS_DESC: "Ports that are open or in use",
  DEVICE_SETTINGS_PORTS_PORT: "Port",
  DEVICE_SETTINGS_PORTS_PROTOCOL: "Protocol",
  DEVICE_SETTINGS_DEVICE_ADDRESS: "IP Address",
  DEVICE_SETTINGS_DEVICE_HOSTNAME: "Hostname",
  DEVICE_SETTINGS_DEVICE_IPV6_ADDRESS: "IPv6 Address",
  DEVICE_SETTINGS_DEVICE_MAC: "MAC ID",
  DEVICE_SETTINGS_ALLOW_CONNECT: "Connect to the Network",
  DEVICE_SETTINGS_GUIDE: "Tap <a href=''>here</a> to find out how to customize your device information",
  DEVICE_SETTINGS_DELETE: "Forget This Device",
  DEVICE_SETTINGS_DELETE_DIALOG_TITLE: "Forget This Device?",
  DEVICE_SETTINGS_DELETE_CONFIRM_MESSAGE: "This device will reappear if it connects to the router protected by " + PROD_NAME + ".",
  DEVICE_SETTINGS_BLOCK_TITLE: "Block Network Connection",
  DEVICE_SETTINGS_BLOCK_MESSAGE: "Are you sure that you want to block the network connection for this device?",
  DEVICE_SETTINGS_FOOTER_PRIMARY_ROUTER: "For stability, the Primary Router must be connected to the network and cannot be assigned.",
  DEVICE_SETTINGS_TUTORIAL: "Tap an item to edit.",
  DEVICE_SETTINGS_ACCESS_PERMISSION: "Network Access Permission",
  DEVICE_REPORT_VULNERABILITY: "Vulnerabilities",
  DEVICE_REPORT_NETWORK_ATTACK: "Network Attacks",
  DEVICE_REPORT_WEB_THREAT: "Web Threats",
  DEVICE_REPORT_RANSOMWARE: "Ransomware Websites",
  DEVICE_REPORT_REMOTE_ACCESS: "Remote Access",
  DEVICE_REPORT_NUMBER_FOUND: "{0} found",
  DEVICE_REPORT_NUMBER_PREVENTED: "{0} prevented",
  DEVICE_REPORT_NUMBER_FIXED: "{0} fixed",
  DEVICE_REPORT_NUMBER_BLOCKED: "{0} blocked",
  DEVICE_REPORT_FOUND_LAST_MONTH: "Found in the last 30 days",
  DEVICE_REPORT_PREVENTED_LAST_MONTH: "Prevented in the last 30 days",
  DEVICE_REPORT_FIXED_LAST_MONTH: "Fixed in the last 30 days",
  DEVICE_REPORT_BLOCKED_LAST_MONTH: "Blocked in the last 30 days",
  DEVICE_REPORT_NO_NETWORK_ATTACK: "No network attacks found",
  DEVICE_REPORT_NO_WEB_THREAT: "No web threats found",
  DEVICE_REPORT_NO_VULNERABILITY: "No vulnerabilities found",
  DEVICE_REPORT_NO_RANSOMWARE: "No ransomware websites found",
  DEVICE_REPORT_NO_REMOTE_ACCESS: "No remote accesses found",
  DEVICE_REPORT_ADD_TO_WTP_LIST: "Add to Approved List",
  DEVICE_REPORT_ADDED_TO_WTP_LIST: "Added to Approved List. (<a href=''>View details</a>)",
  DEVICE_REPORT_ADD_TO_WTP_DIALOG_TITLE: "Add this website to Approved List?",
  DEVICE_REPORT_ADD_TO_WTP_DIALOG_MESSAGE: "Websites on the Approved List are not blocked by " + PROD_NAME + ".\n\nThis website may be dangerous.",
  DEVICE_REPORT_ADD_TO_RAP_LIST: "Do not block this program for this device again",
  DEVICE_REPORT_ADDED_TO_RAP_LIST: "Added to Approved List. (<a href=''>View details</a>)",
  DEVICE_REPORT_ADD_TO_RAP_DIALOG_TITLE: "Add {0} to {1}’s Approved List?",
  DEVICE_REPORT_ADD_TO_RAP_DIALOG_MESSAGE: "Approved programs grant remote access permission to connect to {0}.",
  DEVICE_REPORT_PROGRAM_NOTIFICATION_ON: "Do not notify me about connections with this program again",
  DEVICE_REPORT_PROGRAM_NOTIFICATION_OFF: "Notifications off (<a href=''>Turn notifications on</a>)",
  DEVICE_OFFLINE_DESC: "Connect to the Internet to check your connected devices",   
  DEVICE_POPOVER_DISCOVER_TITLE: "Identify Your Devices Faster",
  DEVICE_POPOVER_DISCOVER_MESSAGE: "When you turn on and use your devices, " + PROD_NAME + " can more easily identify them. <a href=http://discover-device>Learn more</a>",
  ISSUE_TITLE_PASSWORDLESS: "Needs a stronger password",
  IMAGE_CROPPER_TITLE: "Move and Scale",
  FAMILY_HOUSEHOLD: 'Shared',
  FAMILY_GUEST: 'Guest',
  FAMILY_ADD_MEMBER: "Add Someone",
  FAMILY_ADD_HINT: "You can assign devices to anyone in your family and manage how they use the Internet.",
  FAMILY_NO_FAMILY: "No family",
  FAMILY_TAB_REPORT: "Report",
  FAMILY_TAB_SETTINGS: "Settings",
  FAMILY_TAB_DEVICE: "Device",
  FAMILY_SETTINGS_NAME: "Name",
  FAMILY_SETTINGS_WEB_FILTER: "Filtering",
  FAMILY_SETTINGS_WEB_FILTER_HINT: "Block inappropriate websites and content",
  FAMILY_SETTINGS_APP_INSTALL: "Inappropriate App Used",
  FAMILY_SETTINGS_APP_INSTALL_HINT: "Find out when {0} opens one.",
  FAMILY_SETTINGS_NETWORK_CONTROL: "Bedtime",
  FAMILY_SETTINGS_NETWORK_CONTROL_HINT: "Limit when {0} can use the Internet.",
  FAMILY_SETTINGS_CONNECT_HOME: "Connection Alert",
  FAMILY_SETTINGS_CONNECT_HOME_HINT: "Sends an alert when {0}’s devices connect to the home network between 12 PM and 10 PM",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_HINT: "No devices are assigned to {0}. <a href=''>Assign a device now</a>.",
  FAMILY_SETTINGS_SET_UP_NOW: "Set Up Now",
  FAMILY_SETTINGS_REMOVE: "Remove This Person",
  FAMILY_SETTINGS_REMOVE_CONFIRM_MESSAGE: "Are you sure you want to remove this person from " + PROD_NAME + "?",
  FAMILY_SETTINGS_GET_NOTIFICATION: "Get Notifications",
  FAMILY_SETTINGS_BLOCK: "Block",
  FAMILY_SETTINGS_TIME_LIMIT: "Time Limits",
  FAMILY_SETTINGS_WEB_FILTER_WEB_TITLE: "WEBSITE",
  FAMILY_SETTINGS_WEB_FILTER_CONTENT_TITLE: "CONTENT",
  FAMILY_SETTINGS_CONTENT_FILTER_GOOGLE_TITLE: "Turn on Google SafeSearch",
  FAMILY_SETTINGS_CONTENT_FILTER_GOOGLE_MESSAGE: "Filter explicit search results. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_CONTENT_FILTER_YOUTUBE_TITLE: "Turn on YouTube Restricted Mode",
  FAMILY_SETTINGS_CONTENT_FILTER_YOUTUBE_MESSAGE: "Filter mature content. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_TITLE: "Content Filtering",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_MESSAGE: "Now you can turn on Google SafeSearch and YouTube Restricted Mode for {0}",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_ACTION: "Turn on Now",
  FAMILY_SETTINGS_WEB_FILTER_SUBTITLE: "When selected websites are visited",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY: "WEBSITE CATEGORY",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_INFO: "Website Categories",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_ADULT: "Adult or Sexual",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_PERSONAL: "Personals or Dating",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_CRIME: "Criminal or Questionable",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_DRUG: "Illegal Drugs",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_USERDEFINED: "Website on Denied List",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_ADULT_INFO: "Sites that display nude or seminude depictions of the human body, including nudist sites. Also includes sites that display sexually explicit material intended to arouse a sexual or prurient interest.",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_PERSONAL_INFO: "Sites that specialize in promoting romance, dating, friendships, or other interpersonal relationships among people who have not met previously.",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_CRIME_INFO: "Sites that advocate or give advice on performing illegal acts such as theft, evasion of law enforcement, fraud, burglary techniques, and plagiarism. Also includes sites that provide or sell questionable educational materials, such as term papers.",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_DRUG_INFO: "Sites that promote, offer, sell, supply, encourage, or otherwise advocate the illegal use, cultivation, manufacture, or distribution of drugs, pharmaceuticals, intoxicating plants, or chemicals, and related paraphernalia.",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIST: "EXCEPTION LIST",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS: "Set Exceptions",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_ADD: "Add a new website",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_OPEN: "Open This Website",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_REMOVE: "Remove This Website",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_REACH: "Limit Reached",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_URL: "There is a maximum of 1024 List entries on the Station. Please delete websites to add new ones. <a href=http://exception-limit-url>Learn more</a>",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_MEMBER: "A total of 31 family members can have Exceptions Lists. Please empty the Exceptions Lists from a family member in order to create a new Exceptions List. To empty an Exceptions List, remove all of the websites from the Exceptions List. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_INVALID_CHARS: "Please use only letters, numbers and the following special character: -",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_INVALID_FORMAT: "Please use a valid website address",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST: "Cannot Add to {0}'s Denied List",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST_WTP: "To add this website to {0}'s Denied List, you will need to remove it from the Approved List. Approved List changes can be made on the Settings page. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST_MEMBER: "To add this website to {0}'s Denied List, you will need to remove it from {1}'s Allowed List. {2}'s Allowed List can be found on {3}'s Settings page. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_ALLOWED_LIST: "Cannot Add to {0}'s Allowed List",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_ALLOWED_LIST_MEMBER: "To add this website to {0}'s Allowed List, you will need to remove it from {1}'s Denied List. {2}'s Denied List can be found on {3}'s Settings page. <a href=''>Learn more</a>",
  FAMILY_SETTINGS_WEB_FILTER_INVALID_FORMAT_TITLE: "Incorrect Website Address",
  FAMILY_SETTINGS_WEB_FILTER_INVALID_FORMAT_DETAIL: "To edit the website name, please type a valid website address.",
  FAMILY_SETTINGS_FILTERING_UP_TO: "up to {0}",
  FAMILY_SETTINGS_FILTERING_AGE_LEVEL: "Age Level",
  FAMILY_SETTINGS_FILTERING_PRETEEN: "Pre-teen",
  FAMILY_SETTINGS_FILTERING_TEEN: "Teen",
  FAMILY_SETTINGS_FILTERING_CHILD: "Child",
  FAMILY_SETTINGS_FILTERING_CUSTOM: "Custom",
  FAMILY_SETTINGS_FILTERING_FILTERED_CATEGORTIES: "Filtered Categories",
  FAMILY_SETTINGS_FILTERING_CATES_MEDIA: "Communication or Media",
  FAMILY_SETTINGS_FILTERING_CATES_CONTROVERSIAL: "Controversial",
  FAMILY_SETTINGS_FILTERING_CATES_SHOPPING: "Shopping and Entertainment",
  FAMILY_SETTINGS_FILTERING_WEBSITE_EXCEPT: "Website Exceptions",
  FAMILY_SETTINGS_FILTERING_DIALOG_NO_CATES: "No Categories Selected",
  FAMILY_SETTINGS_FILTERING_DIALOG_NO_CATES_MESSAGE: "Select an age level or a category to begin website filtering.",
  FAMILY_SETTINGS_ALLOWED_LIST: "Allowed List",
  FAMILY_SETTINGS_ALLOWED_WEBSITE: "Allowed Website",
  FAMILY_SETTINGS_DENIED_LIST: "Denied List",
  FAMILY_SETTINGS_DENIED_WEBSITE: "Denied Website",
  FAMILY_SETTINGS_APP_FILTER_CATEGORY: "App Categories",
  FAMILY_SETTINGS_APP_FILTER_GAMES: "Games",
  FAMILY_SETTINGS_APP_FILTER_GAMES_INFO: "Apps designed primarily for entertainment.",
  FAMILY_SETTINGS_APP_FILTER_ADULT: "Adult or Sexual",
  FAMILY_SETTINGS_APP_FILTER_ADULT_INFO: "Apps that display nude or seminude depictions of the human body. Also includes apps that display sexually explicit material intended to arouse sexual or prurient interest.",
  FAMILY_SETTINGS_APP_FILTER_SOCIAL: "Social Network or Chat",
  FAMILY_SETTINGS_APP_FILTER_SOCIAL_INFO: "Apps that provide chat or instant messaging capabilities. Also includes apps that support or promote online networks of friends or colleagues for social or business purposes.",
  FAMILY_SETTINGS_APP_FILTER_DATING: "Dating",
  FAMILY_SETTINGS_APP_FILTER_DATING_INFO: "Apps that match users together for romantic or intimate encounters.",
  FAMILY_SETTINGS_APP_FILTER_SHOPPING: "Shopping or Advertisements",
  FAMILY_SETTINGS_APP_FILTER_SHOPPING_INFO: "Apps that provide or advertise the means to purchase goods or services, or that support transactions for procuring goods or services.",
  FAMILY_SETTINGS_APP_FILTER_P2P: "P2P or File Transfer",
  FAMILY_SETTINGS_APP_FILTER_P2P_INFO: "Apps that provide online services for participating in peer-to-peer networks commonly used to share music, videos, and other types of files.",
  FAMILY_SETTINGS_APP_FILTER_VIEW_APP_LIST: "View App List",
  FAMILY_SETTINGS_APP_INSTALL_SUBTITLE: "When selected apps are opened",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY: "APP CATEGORY",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_GAME: "Games",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_ADULT: "Adult",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_CHAT: "Social Network or Chat",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_SHOPPING: "Shopping or Advertisement",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_P2P: "P2P or File Transfer",
  FAMILY_SETTINGS_APP_INSTALL_NO_SELECTED_DIALOG_TITLE: "No Categories Selected",
  FAMILY_SETTINGS_APP_INSTALL_NO_SELECTED_DIALOG_MESSAGE: PROD_NAME + " can only monitor the types of apps you select. Would you like to select some app categories now?",
  FAMILY_SETTINGS_NETWORK_CONTROL_SUBTITLE: "When the Internet is used during the schedule below",
  FAMILY_SETTINGS_NETWORK_CONTROL_BLOCK: "Block Internet Access",
  FAMILY_SETTINGS_NETWORK_CONTROL_BLOCK_SUBTITLE: "Set the schedule below",
  FAMILY_SETTINGS_NETWORK_CONTROL_FROM: "From",
  FAMILY_SETTINGS_NETWORK_CONTROL_TO: "To",
  FAMILY_SETTINGS_NETWORK_CONTROL_ENTIRE_DAY_DIALOG: "Internet Access Unchanged",
  FAMILY_SETTINGS_NETWORK_CONTROL_ENTIRE_DAY_DIALOG_MESSAGE: "No hours have been selected for {0}, so they will have unlimited Internet access.",
  FAMILY_SETTINGS_NETWORK_CONTROL_TAB_SCHOOL_NIGHTS: "School Nights",
  FAMILY_SETTINGS_NETWORK_CONTROL_TAB_WEEKEND: "Weekend",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE: "Schedule",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_SCHOOL_NIGHTS: "Sunday to Thursday",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_WEEKEND: "Friday and Saturday",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_DESC_SCHOOL_NIGHTS: "Limit and monitor the Internet from Sunday through Thursday during the specified hours.",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_DESC_WEEKEND: "Limit and monitor the Internet on Friday and Saturday during the specified hours.",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_EXAMPLE: "For example:",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_RESTRICT: "The Internet is restricted from:",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_PERIOD: "{0} 10:00 PM to {1} 05:00 AM",
  FAMILY_PARENTAL_CONTROL_FEATURES_DIALOG: "Parental Control Features",
  FAMILY_PARENTAL_CONTROL_FEATURES_DIALOG_MESSAGE: "Trend Micro suggests that you discuss parental control features with your family, and use the data provided as a reference for conversation.",
  FAMILY_SETTINGS_TIME_LIMITS: "Time Limits",
  FAMILY_SETTINGS_TIME_CONTROL_INTERNET: "Internet",
  FAMILY_SETTINGS_TIME_CONTROL_TIME_PERIOD_TO: " to ",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_DAYS: "Days:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_HOURS: "Number of Hours Allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_MINUTES: "Number of Minutes Allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_TIME_ALLOWED: "Amount of Time Allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_TIME_PERIOD: "Time Period Allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_COUNT: "Rule {0}",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_TEXT: "Add new rule",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_BUTTON: "Add First Rule",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_HINT: "Time Limits helps you manage your child's Internet use.",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_DELETE: "Delete this rule",
  FAMILY_SETTINGS_TIME_CONTROL_TIP: "Welcome to Time Limits",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_MESSAGE: "You can set multiple rules, limit online time and specify when Internet access is allowed",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DAYS: "Create Your Own Rules",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DAYS_MESSAGE: "Set rules that fit your family's schedule",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_LIMIT: "Limit Online Time",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_LIMIT_MESSAGE: "Select the number of hours that the Internet can be used",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_ALLOWED: "Specify When Internet Access is Allowed",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_ALLOWED_MESSAGE: "Family members can use the Internet only during the time periods you select",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DONE: "Your First Rule",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DONE_MESSAGE: "Based on your previously selected settings",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS: "Select Days",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_TITLE:"Select the days for this rule:",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_MON: "Monday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_TUE: "Tuesday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_WED: "Wednesday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_THU: "Thursday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_FRI: "Friday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_SAT: "Saturday",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_SUN: "Sunday",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS: "Set Hours",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TITLE:"Select the number of hours per day that {0} can use the Internet:",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TITLE_HINT:"Block Internet after reaching the limit",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TIME_LIMIT:"Internet Time Limit",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_NOTIFICATION_HINT: 'When {0} reaches the limit',
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_UNLIMITED: "No Limit",
  FAMILY_SETTINGS_TIME_CONTROL_BLOCK_APP_AFTER: "Block {0} after",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED: 'Set Times Allowed',
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_TITLE: 'Select the time period when {0} can use the Internet:',
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_PERIOD_TITLE:'Time period {0}:',
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_FROM: "From",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_TO: " to ",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_ADD_BUTTON: "Add another time period",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_BLOCK_INTERNET: "Block Internet Access",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_NOTIFICATION_HINT: "When the Internet is used outside of the time period",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_DELETE: "delete",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_NOT_SPECIFIED: "Not specified",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_NOT_ALLOWED: "Hours Not Allowed",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_NOT_ALLOWED_MESSAGE: "Allowed hours must be set for the same day.",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_ACCESS_UNCHANGED: "Internet Access Unchanged",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_ACCESS_UNCHANGED_MESSAGE: "Internet access is unlimited.",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_OVERLAY: "Hours Previously Selected",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_OVERLAY_MESSAGE: "Please select a different time period.",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_NEEDED: "Select Days Needed",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_NEEDED_MESSAGE: "Please select at least one day",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_CONFLICT: "Day Previously Selected",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_CONFLICT_MESSAGE: "Please select a different day.",
  FAMILY_SETTINGS_TIME_CONTROL_DELETE_RULE_DIALOG: "Delete This Rule",
  FAMILY_SETTINGS_TIME_CONTROL_DELETE_RULE_DIALOG_MESSAGE: "Are you sure that you want to delete this rule?",
  FAMILY_SETTINGS_TIME_CONTROL_EVERYDAY_HAS_RULE: "Every Day Has a Rule",
  FAMILY_SETTINGS_TIME_CONTROL_EVERYDAY_HAS_RULE_MESSAGE: "Only one rule is allowed per day. <a href=http://more>Learn more</a>",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE: "Rule Complete",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_HOUR_ALLOWED: " of Internet allowed",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_TIME_PERIOD: "Times allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_NOTIFICATION_ONLY: "Notifications will be sent except for these times:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_NO_TIME_LIMIT_BLOCK: "Times Internet is allowed:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_AM: "AM",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_PM: "PM",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_YOUTUBE: "{0} of YouTube allowed",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_INTERNET: "{0} of Internet allowed, includes {1} of YouTube",
  FAMILY_SETTINGS_TIME_CONTROL_EDIT_RULE_NAME: "Rule Name",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_ALLOWED: "Allowed",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_NOTIFICATION_ONLY: "Notifications Only",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_BLOCKED:"Blocked",
  FAMILY_SETTINGS_PROMOTE_FILTERING: "New filtering options",
  FAMILY_SETTINGS_PROMOTE_TIME_LIMITS: "Now you can limit YouTube",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_CANCELED_DIALOG: "Rule Updated for the Next Day That the Rule Applies",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_CANCELED_DIALOG_MESSAGE: "Because of today’s time limit cancellation, the change will take effect the next day the rule applies.",
  FAMILY_TIME_LIMITS_PROMOTE_YOUTUBE: "Tap here to limit YouTube",
  FAMILY_SETTINGS_CONNECT_HOME_SUBTITLE: "When the selected devices below connect to the home network between 12 PM and 10 PM",
  FAMILY_SETTINGS_CONNECT_HOME_SELECT: "SELECT DEVICE",
  FAMILY_SETTINGS_CONNECT_HOME_NO_SELECTED_DIALOG_TITLE: "No Devices Selected",
  FAMILY_SETTINGS_CONNECT_HOME_NO_SELECTED_DIALOG_MESSAGE: PROD_NAME + " can only notify you when devices are selected. Would you like to select some devices now?",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_DIALOG_TITLE: "No Devices Assigned",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_DIALOG_MESSAGE: PROD_NAME + " only sends notifications for devices that are assigned to a family member. Would you like to assign some devices now?",
  FAMILY_INTERNET_USE_REPORT:"Internet Use Report",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT: "Online Activity Report",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT_HINT: "Record the apps and websites this family member uses",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT_TOAST: "Internet Use Report can be found in {0}’s report",
  FAMILY_SETTINGS_YOUTUBE_LIMIT: "Time on {0}",
  FAMILY_SETTINGS_YOUTUBE_NO_LIMIT: "Do Not Block",
  FAMILY_SETTINGS_YOUTUBE_DURING_LIMIT: "During the {0} of Internet:",
  FAMILY_REPORT_WEB_FILTER_TITLE: "Attempted to visit {0} {1} websites",
  FAMILY_REPORT_WEB_FILTER_TITLE_SINGLE: "Attempted to visit 1 {0} website",
  FAMILY_REPORT_WEBSITE_ON_DENIED_LIST: "Attempted to visit {0} website on Denied List",
  FAMILY_REPORT_WEBSITES_ON_DENIED_LIST: "Attempted to visit {0} websites on Denied List",
  FAMILY_REPORT_WEB_FILTER_TIME: "Blocked between {0} and {1}",
  FAMILY_REPORT_WEB_FILTER_TIME_AT: "Blocked at {0}",
  FAMILY_REPORT_WEB_FILTER_TITLE_VISIT: "Visited {0} {1} websites",
  FAMILY_REPORT_WEB_FILTER_TITLE_VISIT_SINGLE: "Visited 1 {0} website",
  FAMILY_REPORT_WEB_FILTER_TIME_VISIT: "Visited from {0} to {1}",
  FAMILY_REPORT_WEB_FILTER_TIME_AT_VISIT: "Visited at {0}",
  FAMILY_REPORT_WEB_FILTER_TIME_AT_ALLOW: "Allowed at {0}",
  FAMILY_REPORT_APP_INSTALL_TITLE: "Used {0} {1} apps",
  FAMILY_REPORT_APP_INSTALL_TITLE_SINGLE: "Used 1 {0} app",
  FAMILY_REPORT_APP_INSTALL_TIME: "Used from {0} to {1}",
  FAMILY_REPORT_APP_INSTALL_TIME_AT: "Used at {0}",
  FAMILY_REPORT_NET_CONTROL_DETAIL_TITLE: "Attempt to visit internet at {0}",
  FAMILY_REPORT_CONNECT_HOME_TITLE: "Connected to the home network",
  FAMILY_REPORT_CONNECT_HOME_DETAIL_TITLE: "Connected to the home network at {0}",
  FAMILY_REPORT_EMPTY: "Nothing to report for {0}",
  FAMILY_REPORT_EMPTY_NO_RULE: "You have not set up any rules for {0}. Tap Settings to add some.",
  FAMILY_REPORT_INTERNET_USE_TODAY:"Internet Use Today:",
  FAMILY_REPORT_DAILY_LIMIT:"Daily Limit",
  FAMILY_REPORT_INTERNET_PAUSE:"Pause Internet",
  FAMILY_REPORT_INTERNET_RESUME: "Resume Internet",
  FAMILY_REPORT_APP_RESUME: "Resume",
  FAMILY_REPORT_APP_PAUSE: "Pause",
  FAMILY_REPORT_LIMIT: "Limit",
  FAMILY_REPORT_USED:"used",
  FAMILY_REPORT_TOTAL:"Total",
  FAMILY_REPORT_INTERNET_BLOCK: "Internet Blocked",
  FAMILY_REPORT_OUT_OF_ALLOWED_PERIODS: "Out of allowed time periods",
  FAMILY_REPORT_CURRENT_ALLOWED_PERIODS: "Current time periods allowed",
  FAMILY_REPORT_CANCEL_TIME_LIMITS: "Cancel Today’s Time Limits",
  FAMILY_REPORT_DAY_LIMIT_REACHED: "Hours per day limit reached",
  FAMILY_REPORT_CANCEL_LIMITS_DIALOG_MESSAGE:"You can still pause the Internet for {0}.",
  FAMILY_REPORT_CURRENT_TIME:"Current Time",
  FAMILY_DEVICE_EMPTY: "{0} does not have any devices yet.",
  FAMILY_DEVICE_EMPTY_ADD: "Add Devices Now",
  FAMILY_DEVICE_MANAGE: "Manage Devices",
  FAMILY_DEVICE_MANAGE_EMPTY: "All of the devices in your home network have been assigned. Tap Show All Devices to see or change the device owners.",
  FAMILY_DEVICE_MANAGE_OTHER: "Other Devices",
  FAMILY_DEVICE_MANAGE_SHOW_ALL: "Show All Devices",
  FAMILY_DEVICE_MANAGE_SHOW_UNASSIGNED: "Show Only Unassigned",
  FAMILY_DEVICE_MANAGE_ALL_DEVICE_ASSIGNED: "All of the devices in your home network have been assigned. Tap Show All Devices to see or change the device owners.",
  FAMILY_DEVICE_NO_DEVICES_ASSIGNED: "No Devices Assigned",
  FAMILY_DEVICE_NO_DEVICES_ASSIGNED_MESSAGE: PROD_NAME + " can only monitor devices that have been assigned to a family member. Would you like to assign some devices now?",
  FAMILY_EDIT_TITLE_NAME: "Name This Person",
  FAMILY_EDIT_TITLE_STICKER: "Choose a Picture",
  FAMILY_STICKER_UNSUPPORTED_FILE_DIALOG: "Unsupported File",
  FAMILY_STICKER_UNSUPPORTED_FILE_DIALOG_MESSAGE: "Please add a picture.",
  FAMILY_EDIT_TITLE_DEVICE: "Assign Devices",
  FAMILY_EDIT_ADD_PHOTO: "Add Photo",
  FAMILY_EDIT_CHANGE_PHOTO: "Change Photo?",
  FAMILY_EDIT_CHANGE_PHOTO_DETAIL: "Tap Change to select a new photo.",
  FAMILY_EDIT_DEVICE_REASSIGN_TITLE: "Reassign Device",
  FAMILY_EDIT_DEVICE_REASSIGN_MESSAGE: "Are you sure that you want to assign {0} to {1}?",
  FAMILY_OFFLINE_DESC: "Connect to the Internet to check your family settings.",
  FAMILY_REPORT_OFFLINE_DESC: "Connect to the Internet to check the report.",
  FAMILY_EVENT_CONTINUE_BROWSING_TITLE: "{0} wants to open a {1} website",
  FAMILY_EVENT_CONTINUE_BROWSING_DEFAULT_REASON: "I want to open this website.",
  FAMILY_EVENT_CONTINUE_BROWSING_ALLOW: "Add to Allowed List",
  FAMILY_EVENT_CONTINUE_BROWSING_DISALLOW: "Do Not Allow",
  SCAN_RESULT_TITLE_AR: "Action Required",
  SCAN_RESULT_DETAIL_TITLE_PASSWORD: "The password on {0} needs to be changed",
  SCAN_RESULT_DETAIL_DETAILS_PASSWORD: "{0} is using the default password, which was supplied by the manufacturer. Using the default password makes your {1} vulnerable to hackers.",
  SCAN_RESULT_DETAIL_PASSWORD_INTRO: "The current information is:",
  SCAN_RESULT_DETAIL_PASSWORD_URL: "Server : {0}",
  SCAN_RESULT_DETAIL_PASSWORD_ACCOUNT: "Account: {0}",
  SCAN_RESULT_DETAIL_PASSWORD_PASSWORD: "Password: {0}",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_TITLE: "Please follow the instructions to change the password:",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP1: "1. Connect your computer or mobile device to the same network as the online Station.",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP1_ROUTER: "1. Connect your computer or mobile device to the router.",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP2: "2. Open {0} and log in with your account information.",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP3: "3. Change the password. A strong password should have at least 8 characters and a mix of letters, numbers, and symbols.",
  SCAN_RESULT_DETAIL_SKIP: "Skip for Now",
  SCAN_RESULT_DETAIL_RESOLVE: "Already Done",
  SCAN_RESULT_FEEDBACK_HELPFUL: "Was this helpful?",
  SCAN_RESULT_FEEDBACK_YES: "Yes",
  SCAN_RESULT_FEEDBACK_NO: "No",
  SCAN_IDENTIFYING_DEVICES: "Identifying devices",
  SCAN_LOOKING_WEAK_PASSWORD: "Looking for default passwords",
  SCAN_SCANNING_PORTS: "Scanning ports",
  SECURITY_LOG_TITLE_IP: "IP Address: {0}",
  SECURITY_LOG_ACTION_STOP: "Stopped",
  SECURITY_LOG_ACTION_FILTER: "Filtered",
  SECURITY_LOG_ACTION_BLOCK: "Blocked",
  SECURITY_LOG_ACTION_VISIT: "Visited",
  SECURITY_LOG_TIME: "Blocked between {0} and {1}",
  SECURITY_LOG_TIME_AT: "Blocked at {0}",
  SECURITY_LOG_TIME_CONNECTED: "Connected between {0} and {1}",
  SECURITY_LOG_BLOCKED_ATTACKS: "Blocked {0} attacks",
  SECURITY_LOG_BLOCKED_ATTACK: "Blocked {0} attack",
  SECURITY_LOG_BLOCKED_ATTEMPTS: "(total of {0} attempts over {1} attacks)",
  SECURITY_LOG_BLOCKED_ATTEMPTS_SINGLE: "(total of {0} attempts over {1} attack)",
  SECURITY_LOG_BLOCKED_ATTEMPT: "(total of {0} attempt over {1} attack)",
  SECURITY_LOG_CATEGORY: "Category: ",
  SECURITY_LOG_RISK: "Potential Risk: ",
  SECURITY_LOG_RISK_FREE: "No action is necessary. " + PROD_NAME + " continues to protect you from these types of attacks.",
  SECURITY_LOG_SOURCE: "From: {0}",
  SECURITY_LOG_TARGET: "To: {0}",
  SECURITY_LOG_SEVERITY: "Severity: ",
  SECURITY_LOG_SUGGESTIONS: "Suggestion",
  SECURITY_LOG_SAFE_BROWSING: "<a href=''>Learn more</a> about safe browsing.",
  SECURITY_LOG_OS: "Operation System: ",
  SECURITY_LOG_LOCATION_FROM: "From",
  SECURITY_LOG_LOCATION_TO: "To",
  SECURITY_LOG_SEE_DETAILS: "See details",
  SECURITY_LOG_GET_HELP: "Get help",
  SECURITY_LOG_TUTORIAL: "Tap to see details.",
  SECURITY_LOG_NETWORK_ATTACK_ACCESS_CONTROL_TITLE: "Access Control Attack",
  SECURITY_LOG_NETWORK_ATTACK_BUFFER_OVERFLOW_TITLE: "Buffer Overflow Attack",
  SECURITY_LOG_NETWORK_ATTACK_DOS_TITLE: "Denial-Of-Service Attack",
  SECURITY_LOG_NETWORK_ATTACK_TITLE: "Network Attack",
  SECURITY_LOG_NETWORK_ATTACK_SCAN_TITLE: "Scan Attack",
  SECURITY_LOG_NETWORK_ATTACK_VIRUS_TITLE: "Virus/Worm Attack",
  SECURITY_LOG_NETWORK_ATTACK_WEB_TITLE: "Web Attack",
  SECURITY_LOG_NETWORK_ATTACK_ACCESS_CONTROL: "An attempt to give hackers access to devices in a network.",
  SECURITY_LOG_NETWORK_ATTACK_BUFFER_OVERFLOW: "An attempt to flood devices with data.",
  SECURITY_LOG_NETWORK_ATTACK_DOS: "An attempt to disrupt Internet access by making useless requests to a targeted network.",
  SECURITY_LOG_NETWORK_ATTACK: "An attempt to gain unauthorized access to a network or take control of devices.",
  SECURITY_LOG_NETWORK_ATTACK_SCAN: "An attempt to discover whether there are any open ports available in order to give network access to hackers.",
  SECURITY_LOG_NETWORK_ATTACK_VIRUS: "An attempt to open a network to hackers.",
  SECURITY_LOG_NETWORK_ATTACK_WEB: "An attempt to target users who are browsing the Internet.",
  SECURITY_LOG_REMOTE_ACCESS_ALLOWED: "Allowed connection to {0}",
  SECURITY_LOG_REMOTE_ACCESS_CONNECTION_ALLOWED: "Allowed 1 connection",
  SECURITY_LOG_REMOTE_ACCESS_CONNECTIONS_ALLOWED: "Allowed {0} connections",
  SECURITY_LOG_REMOTE_ACCESS_BLOCKED: "Blocked connection to {0}",
  SECURITY_LOG_REMOTE_ACCESS_ATTEMPT_BLOCKED: "Blocked 1 connection attempt",
  SECURITY_LOG_REMOTE_ACCESS_ATTEMPTS_BLOCKED: "Blocked {0} connection attempts",
  SECURITY_LOG_REMOTE_ACCESS_RISK: "Allowing a connection with this software allows others to have a direct connection to your network and device, which leaves your information vulnerable.",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE: "Refuse unknown requests",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE_REMOVE: "Be aware of unwanted connection attempts",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE_NOTIFY: "Limit network access from outside sources",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC: "If someone calls you claiming to be tech support, hang up. Tech support will not contact you directly. <a href=http://Remote_Access>Learn more</a>",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC_REMOVE: "Remove {0} from Approved List if you are concerned that hackers may use this connection and maliciously access your network and devices.",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC_NOTIFY: "If you do not regularly use remote access programs, turn on Block Remote Access to protect your network. <a href=http://Remote_Access>Turn on now</a>",
  SECURITY_LOG_CATEGORY_ILLEGAL: "Illegal or Prohibited Content",
  SECURITY_LOG_CATEGORY_ILLEGAL_DESC: "This website may provide information about or software for sharing and transferring illegal files.",
  SECURITY_LOG_CATEGORY_INSECURE_IOT_CONNECTION: "Unsecure IoT Connections",
  SECURITY_LOG_CATEGORY_INSECURE_IOT_CONNECTION_DESC: "This website may have unsecure connections that will compromise or damage IoT devices.",
  SECURITY_LOG_CATEGORY_PROXY_AVOIDANCE: "Proxy Avoidance",
  SECURITY_LOG_CATEGORY_PROXY_AVOIDANCE_DESC: "This website may be designed to bypass proxy servers and/or web filtering systems.",
  SECURITY_LOG_CATEGORY_MALICIOUS_SOFTWARE: "Potentially Malicious Software",
  SECURITY_LOG_CATEGORY_SPYWARE: "Spyware",
  SECURITY_LOG_CATEGORY_SPYWARE_DESC: "This website may host software that gathers and transmits data from computers owned by unsuspecting users.",
  SECURITY_LOG_CATEGORY_PHISHING: "Phishing",
  SECURITY_LOG_CATEGORY_PHISHING_DESC: "This website may mimic a legitimate website to gather personal information.",
  SECURITY_LOG_CATEGORY_SPAM: "Spam",
  SECURITY_LOG_CATEGORY_SPAM_DESC: "This website may be linked to spam messages.",
  SECURITY_LOG_CATEGORY_ADWARE: "Adware",
  SECURITY_LOG_CATEGORY_ADWARE_DESC: "This website may install and promote software that is designed to display ads or other promotional content.",
  SECURITY_LOG_CATEGORY_VIRUS_MALWARE: "Virus Accomplice /  Malware Accomplice",
  SECURITY_LOG_CATEGORY_VIRUS_MALWARE_DESC: "This website may be used by malicious programs, including websites used to store stolen information.",
  SECURITY_LOG_CATEGORY_DISEASE_VECTOR: "Disease Vector",
  SECURITY_LOG_CATEGORY_DISEASE_VECTOR_DESC: "This website may facilitate the distribution of malicious software or source code.",
  SECURITY_LOG_CATEGORY_COOKIES: "Cookies",
  SECURITY_LOG_CATEGORY_DIALERS: "Dialers",
  SECURITY_LOG_CATEGORY_HACKING: "Hacking",
  SECURITY_LOG_CATEGORY_JOKE: "Joke Program",
  SECURITY_LOG_CATEGORY_PASSWORD_CRACKING: "Password Cracking Apps",
  SECURITY_LOG_CATEGORY_REMOTE_ACCESS: "Remote Access",
  SECURITY_LOG_CATEGORY_ADSENSE: "Made for AdSense sites",
  SECURITY_LOG_CATEGORY_WEB_ADVERTISEMENT: "Web Advertisement",
  SECURITY_LOG_CATEGORY_MALICIOUS_DOMAIN: "Malicious Domain",
  SECURITY_LOG_CATEGORY_MALICIOUS_DOMAIN_DESC: "This web domain may host malicious data.",
  SECURITY_LOG_CATEGORY_C_C_SERVER: "C&C Server",
  SECURITY_LOG_CATEGORY_C_C_SERVER_DESC: "This server may host command and control (C&C) servers.",
  SECURITY_LOG_CATEGORY_COIN_MINER: "Coin Mining",
  SECURITY_LOG_CATEGORY_COIN_MINER_DESC: "This website may host unwanted scripts and files that perform actions related to cryptocurrency.",
  SECURITY_LOG_CATEGORY_SCAM: "Scam",
  SECURITY_LOG_CATEGORY_SCAM_DESC: "This website may attempt to defraud visitors.",
  SECURITY_LOG_SEVERITY_HIGH: "High",
  SECURITY_LOG_SEVERITY_LOW: "Low",
  SECURITY_LOG_ONLINE_STATUS: "Resume Online Status",
  SECURITY_LOG_OFFLINE_STATUS: "Offline",
  LOCATION_TITLE: "Location",
  LOCATION_DESCRIPTION: "The location is an estimation based on the most current IP address detected by our servers.\n\nThere may be inaccuracies or limitations of the location information, including the possibility that proxy servers are being used.",
  SETTINGS_NETWORK_AND_SECURITY: "NETWORK AND SECURITY",
  SETTINGS_NETWORK_AND_SECURITY_DESC: PROD_NAME + " applies these settings to all connected devices.",
  SETTINGS_NETWORK_SECURITY: "Network Security",
  SETTINGS_PRODUCT_INFORMATION: "Product Information",
  SETTINGS_WEB_THREAT_PROTECTION: "Web Threat Protection",
  SETTINGS_NETWORK_MANAGEMENT: "NETWORK MANAGEMENT",
  SETTINGS_NETWORK_PROTECTION: "Network Protection",
  SETTINGS_NETWORK_PROTECTION_DESC: "Helps prevent external attacks and malicious network behavior",
  SETTINGS_WEBSITE_BLOCKING: "Website Blocking",
  SETTINGS_WEBSITE_BLOCKING_DESC: "Filters potentially dangerous websites",
  SETTINGS_APPROVED_LIST: "Approved List",
  SETTINGS_APPROVED_WEBSITE: "Approved Website",
  SETTINGS_APPROVED_WEBSITE_CONFLICT: "Cannot Add to Approved List",
  SETTINGS_APPROVED_WEBSITE_CONFLICT_DETAIL: "To add this website to the Approved List, you will need to remove it from the family member’s Denied List. Denied List changes can be made on the family member’s Settings page. <a href=http://conflict-wtp-black>Learn more</a>",
  SETTINGS_INTRANET_PROTECTION: "Internal Attack Blocking",
  SETTINGS_INTRANET_PROTECTION_DESC: "Helps prevent attacks between devices in your home network",
  SETTINGS_INTRANET_PROTECTION_DIALOG_TITLE: "Please note:",
  SETTINGS_INTRANET_PROTECTION_DIALOG_MESSAGE: "Because some routers may not fully support this feature, you may have network instability issues.\n\nWould you like to turn Internal Attack Blocking on?",
  SETTINGS_SMART_FIREWALL: "Cyberattack Shield (Beta)",
  SETTINGS_SMART_FIREWALL_DESC: "Real-time defense against cyberattacks",
  SETTINGS_SMART_FIREWALL_LEARN_MORE: "Learn about Cyberattack Shield",
  SETTINGS_NETWORK_ACCESS_CONTROL: "Network Access Control",
  SETTINGS_NETWORK_ACCESS_PERMISSION: "New Device Approval",
  SETTINGS_NETWORK_ACCESS_PERMISSION_DESC: "Require permission when a new device joins the network",
  SETTINGS_NETWORK_ACCESS_NOTIFY_POPUP: "Get Notifications?",
  SETTINGS_NETWORK_ACCESS_NOTIFY_POPUP_DESC: "Would you like to be notified when new devices join the home network?",
  SETTINGS_REMOTE_ACCESS_PROTECTION: "Remote Access Protection",
  SETTINGS_REMOTE_ACCESS_PROTECTION_DESC: "Limit remote access connections to your devices",
  SETTINGS_REMOTE_ACCESS_PROTECTION_BLOCK: "Block Remote Access",
  SETTINGS_REMOTE_ACCESS_PROTECTION_MESSAGE: "Limit remote access connections to your devices",
  SETTINGS_REMOTE_ACCESS_PROTECTION_ADD: "Add Program",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED: "Approved for 1 device",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED_PLURAL: "Approved for {0} devices",
  SETTINGS_REMOTE_ACCESS_PROTECTION_UNAPPROVED: "Unapproved",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_PROGRAM: "Select Program",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_DEVICE: "Select Devices",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_DEVICE_DESC: "Select devices to approve {0}:",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECTED_DEVICES: "{0} allowed on:",
  SETTINGS_REMOTE_ACCESS_PROTECTION_OTHER_DEVICES: "Other Devices:",
  SETTINGS_REMOTE_ACCESS_PROTECTION_EMPTY: "{0} is not approved for any devices.\nTap Manage Devices to add devices.",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED_PROGRAM: "Approved Program",
  SETTINGS_REMOTE_ACCESS_PROTECTION_MANAGE_DEVICES: "Manage Devices",
  SETTINGS_REMOTE_ACCESS_PROTECTION_REMOVE_PROGRAM: "Remove from Approved List",
  SETTINGS_NOTIFICATIONS: "Notifications",
  SETTINGS_NOTIFICATIONS_NETWORK_ATTACKS_BLOCKED: "Network Attacks Blocked",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION: "Remote Access Protection",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_NONE: "No Notifications",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_BLOCKED: "Notify me when remote access connections are blocked",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_ALL: "Notify me for all remote access connections",
  SETTINGS_NOTIFICATIONS_DANGEROUS_WEBSITE_BLOCKED: "Dangerous Websites Blocked",
  SETTINGS_NOTIFICATIONS_DANGEROUS_FILE_BLOCKED: "Dangerous Files Blocked",
  SETTINGS_NOTIFICATIONS_DEVICE_VULNERABILITIES_FOUND: "Device Vulnerabilities Found",
  SETTINGS_NOTIFICATIONS_LICENSE_RENEWAL: "Subscription Renewal",
  SETTINGS_NOTIFICATIONS_SURVEYS: "Surveys",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_NONE: "No Notifications",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_HIGH_SEVERITY: "Only Notify Me for High Severity Attacks",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_ALL: "Notify Me for All Attacks",
  SETTINGS_SECURITY_WARNINGS: "Security Warnings",
  SETTINGS_NEW_DEVICE_ADDED: "New Devices Added",
  SETTINGS_ACCOUNT: "ACCOUNT",
  SETTINGS_ACCOUNT_TRENDMICRO: "Trend Micro Account",
  SETTINGS_ACCOUNT_SUBSCRIPTION: "Subscription",
  SETTINGS_ACCOUNT_SUBSCRIPTION_EXPIRES: "Expires: {0}",
  SETTINGS_ACCOUNT_SUBSCRIPTION_EXPIRED: "Expired: {0}",
  SETTINGS_ACCOUNT_SUBSCRIPTION_MONTHLY: "Monthly Subscription",
  SETTINGS_ACCOUNT_SUBSCRIPTION_YEARLY: "Yearly Subscription",
  SETTINGS_ACCOUNT_SUBSCRIPTION_ACTIVATED: "Activated",
  SETTINGS_ACCOUNT_SUBSCRIPTION_DETAILS: "Subscription Details",
  SETTINGS_ACCOUNT_GO_TO_MY_ACCOUNT: "Go to My Account",
  SETTINGS_ACCOUNT_RENEW: "Renew Now",
  SETTINGS_ABOUT_AND_HELP: "ABOUT AND HELP",
  SETTINGS_PAIRING_CODE: "Pairing Code",
  SETTINGS_STATION_CODE: "Station Code",
  SETTINGS_ABOUT: "About",
  SETTINGS_HELP: "Help",
  SETTINGS_SEND_LOG: "Send Troubleshooting Logs",
  SETTINGS_SEND_LOG_SUBJECT: PROD_NAME_SHORT + " Troubleshooting Logs",
  SETTINGS_SEND_LOG_BODY: "Support ID: {0}\nTime: {1}",
  SETTINGS_SUPPORT: "Support ID: {0} - Sent: {1}",
  SETTINGS_CRASH_REPORT: "Share Crash Data with Trend Micro",
  SETTINGS_UBM: "Help Improve This App",
  SETTINGS_UBM_DETAIL: "Share Anonymous Data with Trend Micro",
  SETTINGS_STATION: "Station Management",
  SETTINGS_STATION_DISCONNECT: "End Station Management",
  SETTINGS_STATION_DISCONNECT_DESC: "Stop this device from managing the Station",
  SETTINGS_STATION_RESET: "Reset the Station",
  SETTINGS_STATION_RESET_DESC: "Erase all data from the station",
  SETTINGS_SET_UP_A_NEW_STATION: "End Station Management?",
  SETTINGS_SET_UP_A_NEW_STATION_DIALOG_MESSAGE: "You may need to pair a new device in order to manage the Station. Are you sure that you want to end Station management for this device?",
  SETTINGS_RESET_STATION: "Reset the Station?",
  SETTINGS_RESET_STATION_DIALOG_MESSAGE: "Are you sure that you want to reset the Station? All of your data will be deleted.",
  SETTINGS_COMPATIBILITY_MODE: "Compatibility Mode",
  SETTINGS_COMPATIBILITY_MODE_DETAIL: "Turn on if you are experiencing network issues or are having problems connecting to the Internet.\n<a href=http://compatibility-off>Learn more</a>",
  SETTINGS_COMPATIBILITY_MODE_DETAIL_ON: "If you have customized your router settings, please click <a href=http://compatibility-on>here</a> to learn more.",
  SETTINGS_DHCP_MODE_DETAIL: "The Station is now the DHCP server. <a href=http://dhcp>Learn more</a>",
  SETTINGS_FEEDBACK: "Give Feedback",
  SETTINGS_UNSECURED_DEVICES: "Unsecured Devices",
  SETTINGS_UNSECURED_DEVICES_OTHER: "Other Devices",
  SETTINGS_UNSECURED_DEVICES_DESC: "Traffic to Unsecured Devices is not scanned for network threats. Unsecured Devices are not tracked, and cannot be controlled by Parental Controls.",
  SETTINGS_UNSECURED_DEVICES_LEARN_MORE: "Find out more about Unsecured Devices <a href=http://Unsecured_Devices>here</a>.",
  SETTINGS_UNSECURED_DEVICES_EMPTY: "No Unsecured Devices",
  SETTINGS_UNSECURED_DEVICES_EMPTY_DESC: "Adding Unsecured Devices is not generally recommended.",
  SETTINGS_UNSECURED_DEVICES_ADD: "Add Devices",
  SETTINGS_UNSECURED_DEVICES_MANAGE: "Manage Devices",
  ABOUT_TITLE: "Trend Micro",
  ABOUT_FIRMWARE_VER_TITLE: "Firmware Version",
  ABOUT_APP_VER_TITLE: "App Version",
  ABOUT_DPI_VER_TITLE: "DPI Pattern Version",
  ABOUT_MAC_TITLE: "MAC ID (Station)",
  ABOUT_LICENSE: "Third-party License Information",
  ABOUT_EULA: "Trend Micro License Agreement",
  ABOUT_TRADEMARK: "(C) 2018 by Trend Micro Incorporated. All rights reserved. Trend Micro, Home Network Security Logo and the t-ball logo are trademarks or registered trademarks of Trend Micro Incorporated. All other company and/or product names may be trademarks or registered trademarks of their respective owners.",
  TIMEZONE: "UTC{0}",
  TIMEZONE_DESC: "Current Time at Home:",
  TIMEZONE_POPUP_TITLE: "Time Zone",
  TIMEZONE_POPUP_MSG: "The time zone for notifications is based on the first location where your Station was activated.",
  LAST_UPDATED: "Last Update: {0}",
  TIMELINE_CARD_APP_LIMIT_REACHED: "Daily {0} {1} limit reached",
  FAMILY_REPORT_APP_LIMIT_REACHED: "Daily {0} {1} limit reached by {2}",
  TIMELINE_CARD_DIAMOND_TITLE: PROD_NAME,
  TIMELINE_CARD_DIAMOND_DESC: PROD_NAME + " is protecting your family",
  TIMELINE_CARD_FIRST_TIME_DEVICE: "{0} device found and is connected to the secure home network",
  TIMELINE_CARD_FIRST_TIME_DEVICES: "{0} devices found and are connected to the secure home network",
  TIMELINE_CARD_DEFAULT_PASSWORD_ROUTER: "The password on this device needs to be changed to keep your home network safe",
  TIMELINE_CARD_DEFAULT_PASSWORD: "The password on this device needs to be changed",
  TIMELINE_CARD_DEFAULT_PASSWORD_FIXED: "Password changed",
  TIMELINE_CARD_WEB_THREAT: "{0} web threat blocked",
  TIMELINE_CARD_WEB_THREATS: "{0} web threats blocked",
  TIMELINE_CARD_APP_INSTALL: "Used 1 {0} app:",
  TIMELINE_CARD_APP_INSTALL2: "Used 2 {0} apps:",
  TIMELINE_CARD_APP_INSTALL2_AND: "{0} and {1}",    
  TIMELINE_CARD_APP_INSTALLS: "Used {0} {1} apps:",
  TIMELINE_CARD_NETWORK_CONTROL: "1 attempt to use the Internet at {0}",
  TIMELINE_CARD_NETWORK_CONTROLS: "Attempted to use the Internet between {0} and {1}",
  TIMELINE_CARD_NETWORK_CONTROLS_AT: "Attempted to use the Internet at {0}",
  TIMELINE_CARD_NETWORK_CONTROLS_LIST: "Attempted to use the Internet at blocked times, including:",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT: "Used the Internet from {0} to {1}",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT_AT: "Used the Internet at {0}",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT_LIST: "Used the Internet at the times you selected, including:",
  TIMELINE_CARD_DEVICE_JOIN: "Joined the secure home network",
  TIMELINE_CARD_NETWORK_ATTACK: "{0} network attack blocked",
  TIMELINE_CARD_NETWORK_ATTACKS: "{0} network attacks blocked",
  TIMELINE_CARD_WEBSITE_FILTER: "Attempted to visit {0} {category} website",
  TIMELINE_CARD_WEBSITE_FILTERS: "Attempted to visit {0} {category} websites",
  TIMELINE_CARD_WEBSITE_VISITED: "Visited {0} {category} website",
  TIMELINE_CARD_WEBSITE_VISITEDS: "Visited {0} {category} websites",
  TIMELINE_CARD_WEBSITE_ON_DENIED_LIST: "Attempted to visit {0} website on Denied List",
  TIMELINE_CARD_WEBSITES_ON_DENIED_LIST: "Attempted to visit {0} websites on Denied List",
  TIMELINE_CARD_CONNECT_AT_HOME: "Used {device} to connect to the secure home network",
  TIMELINE_CARD_REMOVE_DEVICE: "{0} was removed from Devices",
  TIMELINE_CARD_REMOVE_MEMBER: "{0} was removed from Family",
  TIMELINE_CARD_EOL: "Service for " + PROD_NAME + " is being discontinued on {0}. If you have any questions, please contact {1}.",
  TIMELINE_CARD_DIAMOND_APP_INSTALL: PROD_NAME + " app is installed on another device",
  TIMELINE_CARD_DAILY_SCAN_TITLE: "Daily Security Check",
  TIMELINE_CARD_DAILY_SCAN_NO_ISSUE: "Security check successfully completed at {0}, and no issues were found. Your devices are automatically checked daily.",
  TIMELINE_CARD_DAILY_SCAN: "Security check successfully completed at {0}. Your devices are automatically checked daily.",
  TIMELINE_CARD_OWNED_BY: "Owned by {0}",
  TIMELINE_CARD_RANSOMWARE: "1 ransomware website blocked",
  TIMELINE_CARD_RANSOMWARES: "{0} ransomware websites blocked",  
  TIMELINE_CARD_RAP_CONNECTION_BLOCKED: "1 remote access connection blocked",
  TIMELINE_CARD_RAP_CONNECTIONS_BLOCKED: "{0} remote access connections blocked",
  TIMELINE_CARD_RAP_CONNECTION_ALLOWED: "{0} opened a remote access connection",
  TIMELINE_CARD_RAP_CONNECTIONS_ALLOWED: "{0} opened {1} remote access connections",
  TIMELINE_CARD_TIME_LIMIT_REACHED: "Daily {0} Internet limit reached",
  TIMELINE_CARD_TAP_TO_LEARN_MORE: "Tap to learn more.",
  TIMELINE_CARD_CONTINUE_BROWSING: "{0} wants to open a {1} website",
  TIMELINE_CARD_CONTINUE_BROWSING_ALLOW: "Visit to 1 {0} website was allowed",
  TIMELINE_CARD_CONTINUE_BROWSING_ALLOWS: "Visit to {0} {1} websites were allowed",
  TIMELINE_CARD_BOX_STATUS_CHANGED_OFFLINE: "Your Station is offline",
  TIMELINE_CARD_BOX_STATUS_CHANGED_ONLINE: "Your Station disconnected, and is now back online",
  TIMELINE_CARD_FEATURE_UPDATED: "Features updated",
  TIMELINE_CARD_FIRMWARE_UPDATED: "Security updates installed",
  TIMELINE_CARD_RENEWED: PROD_NAME + " is protecting your home network.",
  TIMELINE_CARD_STATION_TITLE: PROD_NAME_SHORT + " Station",
  TIMELINE_CARD_NETWORK_ACCESS: "Request to join the secure home network",
  TIMELINE_CARD_NETWORK_ACCESS_APPROVED: "Approved to join the secure home network",
  TIMELINE_CARD_NETWORK_ACCESS_BLOCKED: "Blocked from home network",
  TIMELINE_STATUS_CHECKING_DEVICE_TITLE_1: "Starting",
  TIMELINE_STATUS_CHECKING_DEVICE_TITLE_2: "Protection",
  TIMELINE_STATUS_ACTION_REQUIRED_TITLE_1: "Action",
  TIMELINE_STATUS_ACTION_REQUIRED_TITLE_2: "Required",
  TIMELINE_STATUS_DISCONNECT_TITLE_1: "No Internet",
  TIMELINE_STATUS_DISCONNECT_TITLE_2: "Connection",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE: "Device",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE_1: "Devices",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE_2: "Protected",
  TIMELINE_STATUS_DEVICE_BLOCKED_TITLE_1: "Device Is",
  TIMELINE_STATUS_DEVICE_BLOCKED_TITLE_2: "Blocked",
  TIMELINE_STATUS_PROTECTION_DISABLED_TITLE_1: "Protection",
  TIMELINE_STATUS_PROTECTION_DISABLED_TITLE_2: "Disabled",
  TIMELINE_STATUS_EXPIRED_TITLE_1: "Subscription",
  TIMELINE_STATUS_EXPIRED_TITLE_2: "Expired",
  TIMELINE_STATUS_NEW_NOTIFICATIONS_ABOVE: "New Notifications Above",
  TIMELINE_SCANBTN_CHECK_TITLE_1: "Check Devices",
  TIMELINE_SCANBTN_CHECK_TITLE_2: "Security",
  TIMELINE_SCANBTN_SCAN_TITLE_1: "Checking Progress",
  TIMELINE_SCANBTN_REPORT_TITLE_1: "See Results",
  TIMELINE_DIALOG_SCAN: "Checking your devices for settings that might make them more vulnerable to network attack.",
  TIMELINE_POPOVER_ISSUE_FOUND: "{0} Issues Found",
  TIMELINE_POPOVER_ISSUE_FOUND_SINGLE: "{0} Issue Found",
  TIMELINE_POPOVER_SCANNING_STRING: "Checking the security of connected devices...",
  TIMELINE_POPOVER_SCANNING_CHECK_DEVICE: "Checking device: {0}",
  TIMELINE_POPOVER_SCANNING_ISSUE_FOUND: "Issues found: {0}",
  TIMELINE_POPOVER_NO_ISSUE: "No Issues Found",
  TIMELINE_POPOVER_SCANNED_DEVICES: "Scanned Devices:",
  TIMELINE_POPOVER_LICENSE_EXPIRED: "License Expired",
  TIMELINE_POPOVER_CHECKING_DEVICE: "Starting network check",
  TIMELINE_POPOVER_CHECKING_DEVICE_1: "Checking your network",
  TIMELINE_POPOVER_CHECKING_DEVICE_2: "Almost done",
  TIMELINE_POPOVER_FIRST_TIME_DESC: PROD_NAME + " has detected this device on your network and is protecting it.",
  TIMELINE_POPOVER_FIRST_TIME_DESC_1: PROD_NAME + " has detected these devices on your network and is protecting them.",
  TIMELINE_POPOVER_FIRST_TIME_ACTION: "View Devices",
  TIMELINE_POPOVER_OFFLINE_DESC: "Your Station is offline. Reconnect the Station to resume protection.",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_TOP: PROD_NAME + " cannot be used if the following device is connected to the network:",
  TIMELINE_POPOVER_ANOTHER_ARP_DEVICE: "Device:",
  TIMELINE_POPOVER_ANOTHER_ARP_DEVICE_IP: "Device IP: {0}",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_BOTTOM: "To enable protection, please disconnect the device or contact <a href=http://vendor>{0}</a> for help.",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_MID: "This device is monitoring your network.",
  TIMELINE_POPOVER_BOX_UPDATING: "The firmware is being updated on the Station. The update should take less than one minute. Once the update is complete, your protection will restart.",
  TIMELINE_POPOVER_SURVEY_TITLE: "Give Us Your Opinion",
  TIMELINE_POPOVER_SURVEY_MESSAGE: "Please share your ideas so we can improve " + PROD_NAME + ".",
  TIMELINE_POPOVER_SURVEY_ACTION: "Start Survey",
  TIMELINE_POPOVER_WHATSNEW_SEE_MORE: "See more",
  TIMELINE_POPOVER_EXPIRED_RENEW: "Please renew your subscription to restart protection.",
  TIMELINE_POPOVER_EXPIRED_RENEW_JP: "To restart protection, please sign into your Trend Micro Account or tap Renew Now to renew your subscription.",
  TIMELINE_POPOVER_EXPIRED: "Please check your email or contact {0} for assistance.",
  TIMELINE_POPOVER_EXPIRED_JP: "Please check your email or sign into your Trend Micro Account to renew your subscription.",
  TIMELINE_POPOVER_EXPIRED_ANZ: "Sign into your Trend Micro Account to renew. <a href=http://expired>Learn more</a>",
  TIMELINE_POPOVER_EXPIRED_CONTACT_SUPPORT: "Contact {0}",
  TIMELINE_OFFLINE_DESC: "Connect to the Internet to check the security of your home network.",
  TIMELINE_BTN_TRY_AGAIN: "Try Again",
  TIMELINE_PROMOTION_WTP_CONTENT: "All connected devices are protected from web threats by " + PROD_NAME_SHORT + ".",
  TIMELINE_PROMOTION_WTP_LINK: "Test it now",
  TIMELINE_TIP: "You Can Find Your Timeline Here",
  TIMELINE_TIP_MESSAGE: "Tap here to view the Timeline",
  TIMELINE_ACTION_TITLE_NETWORK_ATTACK: "Network Attacks",
  TIMELINE_ACTION_TITLE_WEB_THREAT: "Web Threats",
  TIMELINE_ACTION_TITLE_RANSOMWARE: "Ransomware Websites",
  TIMELINE_ACTION_TITLE_WEB_FILTERING: "Inappropriate Websites",
  TIMELINE_ACTION_TITLE_NETWROK_CONTROL: "Attempts to Use the Internet",
  TIMELINE_ACTION_TITLE_APP_INSTALL: "Inappropriate Apps",
  TIMELINE_ACTION_TITLE_RAP_BLOCKED: "Remote Connections",
  TIMELINE_ACTION_TITLE_TIME_LIMIT_REACHED: "Internet Limit Reached",
  DASHBOARD_TIP: "Welcome to the Dashboard",
  DASHBOARD_TIP_MESSAGE: "Your Dashboard shows your " + PROD_NAME_SHORT + " status at a glance.",
  DASHBOARD_CARD_SUMMARY: "Summary",
  DASHBOARD_CARD_SUMMARY_LAST_7_DAYS: "Last 7 days",
  DASHBOARD_CARD_SUMMARY_LAST_30_DAYS: "Last 30 days",
  DASHBOARD_CARD_SUMMARY_SHOW_MORE: "Show More",
  DASHBOARD_CARD_SUMMARY_SHOW_LESS: "Show Less",
  DASHBOARD_CARD_SUMMARY_TAG_SECURITY: "Security",
  DASHBOARD_CARD_SUMMARY_TAG_FAMILY: "Family",
  DASHBOARD_CARD_BLOCKED_UNIT: "",
  DASHBOARD_CARD_DEVICE_UNIT: "",
  DASHBOARD_CARD_VISITED_UNIT: "",
  DASHBOARD_CARD_USED_UNIT: "",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_EVENTS: "There were no Parental Control events or threats blocked.",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_SECURITY_EVENTS: "Device protected and no threats blocked.",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_SECURITY_EVENTS_PLURAL: "Devices protected and no threats blocked.",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_PARENTAL_CONTROL_EVENTS: "There were no Parental Control events.",
  DASHBOARD_CARD_SUMMARY_EVENT_NETWORK_ATTACK: "Network Attack\nBlocked", // NETWORK_ATTACK : 4,
  DASHBOARD_CARD_SUMMARY_EVENT_NETWORK_ATTACKS: "Network Attacks\nBlocked",
  DASHBOARD_CARD_SUMMARY_EVENT_INTERNAL_ATTACK: "Internal Attack Blocked", // Not in this revision
  DASHBOARD_CARD_SUMMARY_EVENT_WEB_THREAT: "Web Threat Blocked",  // WEB_THREAT : 5,
  DASHBOARD_CARD_SUMMARY_EVENT_WEB_THREATS: "Web Threats Blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_RANSOMWARE: "Ransomware Website Blocked", // RANSOMWARE : 15,
  DASHBOARD_CARD_SUMMARY_EVENT_RANSOMWARES: "Ransomware Websites Blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_REMOTE_ACCESS_BLOCKED: "Remote Connection Blocked", // RAP_BLOCKED : 24,
  DASHBOARD_CARD_SUMMARY_EVENT_REMOTE_ACCESSES_BLOCKED: "Remote Connections Blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_DEVICE_PROTECT: "Total Device Protected",
  DASHBOARD_CARD_SUMMARY_EVENT_DEVICES_PROTECT: "Total Devices Protected",
  DASHBOARD_CARD_SUMMARY_EVENT_WEBSITE_BLOCK: "Inappropriate Website\nBlocked or Visited", // WEB_FILTERING : 6,
  DASHBOARD_CARD_SUMMARY_EVENT_WEBSITES_BLOCK: "Inappropriate Websites\nBlocked or Visited",
  DASHBOARD_CARD_SUMMARY_EVENT_ATTEMPT_BLOCK: "Attempt to Use\nthe Internet Blocked",  // NETWROK_CONTROL : 8,
  DASHBOARD_CARD_SUMMARY_EVENT_ATTEMPTS_BLOCK: "Attempts to Use\nthe Internet Blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_DAY_TIME_LIMIT_REACH: "Time That the Internet Limit Was Reached", // TIME_LIMIT_REACH :25   
  DASHBOARD_CARD_SUMMARY_EVENT_DAYS_TIME_LIMIT_REACH: "Times That the Internet Limit Was Reached", 
  DASHBOARD_CARD_SUMMARY_EVENT_INAPPROPRATE_APP_USE: "Time Inappropriate Apps Used", // APP_INSTALL : 7,
  DASHBOARD_CARD_SUMMARY_EVENT_INAPPROPRATE_APPS_USE: "Times Inappropriate Apps Used",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_ATTACK_BLOCKED: "new attack blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_ATTACKS_BLOCKED: "new attacks blocked",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_EVENT: "new event",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_EVENTS: "new events",
  DASHBOARD_CARD_SUMMARY_EVENT_NAME_REMOVED: "Name Removed",
  DASHBOARD_CARD_FAMILY_MEMBERS: "Family Members",
  DASHBOARD_CARD_FAMILY_MEMBERS_NO_FAMILY_MEMBER: "Assign devices to your family to manage how they use the Internet.",
  DASHBOARD_CARD_FAMILY_MEMBERS_ASSIGN_NOW: "Assign Now",
  DASHBOARD_CARD_TOP_ATTACKED_DEVICES: "Top Attacked Devices",
  DASHBOARD_CARD_TOP_ATTACKED_DEVICES_NO_DEVICE: "No devices were attacked",
  DASHBOARD_CARD_NETWORK_USAGE:"Network Usage",
  DASHBOARD_CARD_NETWORK_USAGE_NO_DATA: "There were no usages to show",
  DASHBOARD_MEMBER_PAUSED: "Paused {0}",
  DASHBOARD_MEMBER_NO_TIME_LEFT: "No Time Left",
  DASHBOARD_MEMBER_OUT_TIME_PERIOD: "Out of Time Period",

  NETWORK_USAGE_TAB_SEVEN_DAY: 'Last 7 Days',
  NETWORK_USAGE_TAB_THIRTY_DAY: 'Last 30 Days',
  NETWORK_USAGE_IPV6_NOTICE: "Wondering about your results? Some extra data may be included in upload traffic. <a href=''>Learn more</a>",

  MINI_SURVEY_OPTION_OTHER: "Other comments",
  MINI_SURVEY_OPTION_LATER: "Ask me later",
  MINI_SURVEY_ACTION_SEND: "Send",
  MINI_SURVEY_COMMENT_HINT: "Please type your comments here...",
  DHCP_DIALOG_TITLE: "Update Router Settings",
  DHCP_DIALOG_DESC: "Your router settings need to be changed for your protection. Please tap Get Help to begin. ",
  DHCP_POPOVER_DESC: "Your router settings need to be changed for your protection. <a href=http://dhcpHelp>Get Help</a>",
  DHCP_DIALOG_DESC_NABU: "Your router settings need to be changed for your protection.",
  DHCP_LEARN_MORE: "<a href=http://dhcpHelp>Learn more</a>",
  COMPATIBILITY_DIALOG_TITLE: "Compatibility Mode Is On",
  COMPATIBILITY_DIALOG_DESC: "Compatibility Mode is turned on to allow the Station to work with your router. If you have customized your router settings, please click <a href=http://compatibilityHelp>here</a> to learn more",
  PULLDOWN_REFRESH_LOADING: "Loading...",
  DIAGNOSTIC_TITLE: "Diagnostic Tool",
  DIAGNOSTIC_TAB_COMPATIBILITY: "Compatibility",
  DIAGNOSTIC_TAB_HOSTS: "Hosts",
  DIAGNOSTIC_TAB_INFO: "Info",
  DIAGNOSTIC_STATION: "Station",
  DIAGNOSTIC_LOCALHOST: "Localhost",
  DIAGNOSTIC_STATUS: "Status",
  DIAGNOSTIC_COMPATIBILITY_ACTION: "Diagnose Compatibility",
  DIAGNOSTIC_HOSTS_ACTION: "Discover Hosts",
  DIAGNOSTIC_NOTES: "Notes",
  DIAGNOSTIC_NOTES_HINT: "ex: Router Model",
  DIAGNOSTIC_SUBMIT: "Submit",
  DIAGNOSTIC_RESULT_SUBJECT: PROD_NAME_SHORT + " Compatibility Diagnosis",
  DIAGNOSTIC_SPEED_TEST_TITLE: "Speed Test (Optional)",
  DIAGNOSTIC_SPEED_TEST_DESC: "You can provide a speed test result to help us understand your home network further. <a href=''>Test Now</a>",
  DIAGNOSTIC_SPEED_TEST_RESULT: "Paste result url here",
  BOX_STATUS_LOG_TITLE: "Station Status",
  WHATS_NEW_DETAIL_TITLE: "New Features",
  INTRANET_PROTECT_INFO_TITLE: "Network Recovery Guide",
  INTRANET_PROTECT_INFO_SUBJECT: "Restart your network connection by using the following steps:",
  INTRANET_PROTECT_INFO_CONTENT: "1. Connect to a mobile network, using the device running the " + PROD_NAME + " app.\n\n2. In Settings, turn off Internal Attack Blocking.\n\n3. Wait for 10 seconds, then unplug the router from the power outlet.\n\n4. Wait another 15 seconds, then plug the router back into the power outlet and allow it to restart.",
  
  PMAC_OFFLINE_CALL_NOW: "Call Now",
  PMAC_OFFLINE_REQUEST_CALLBACK: "Request Callback",
  PMAC_OFFLINE_LINK: "View Troubleshooting Guide",
  
  PUSH_NOTIFICATION_MARKET_SURVEY: "Please give Trend Micro your feedback about " + PROD_NAME,
  PUSH_NOTIFICATION_PROMOTION_FAMILY: "Assign devices to your family to manage how they use the Internet",

  // NABU only
  CALL_SUPPORT_DIRECTLY: "Call Support directly: <a href=''>{0}</a>",
  PHONE_EXT: "option {0}",
  REQUEST_CALL_FROM_SUPPORT: "Request a call from Support",
  REQUEST_CALL_FROM_SUPPORT_HINT: "Support will call by {0} {1}.",
  REQUEST_SUPPORT_CALL_DIALOG_TITLE: "Request a Support Call",
  REQUEST_SUPPORT_CALL_DIALOG_MESSAGE: "Please provide your name and phone number. Support will contact you within 30 minutes.",
  REQUEST_SUPPORT_CALL_DIALOG_CONFIRMATION_TITLE: "Is This Information Correct?",
  REQUEST_SUPPORT_CALL_DIALOG_CONFIRMATION_MESSAGE: "Name: {0}\nPhone Number: {1}",
  REQUEST_SUPPORT_CALL_REQUESTED_DIALOG_TITLE: "Support Call Requested",
  REQUEST_SUPPORT_CALL_REQUESTED_DIALOG_MESSAGE: "Support will call by {0} {1}.",
  REQUEST_SUPPORT_CALL_SENT_DIALOG_TITLE: "Request Sent",
  REQUEST_SUPPORT_CALL_SENT_DIALOG_MESSAGE: "Your request is being processed by Support. If necessary, please make a new request {0} after {1}.",

  //Help Page
  HELP_CONTACT_SUPPORT: "CONTACT SUPPORT",
  HELP_CALL_SUPPORT_DIRECTLY: "Support number: <a href=''>{0}</a>",
  HELP_SECTION_TITLE_TROUBLESHOOTING: "TROUBLESHOOTING",
  HELP_SECTION_TITLE_HOW: "HOW DO I...",
  HELP_ITEM_TROUBLE_SLOW_INTERNET: "The Internet is slow",
  HELP_ITEM_TROUBLE_DEVICE_NETWORK_ISSUE: "Some devices have network issues",
  HELP_ITEM_TROUBLE_PLAY_GAME: "I am having trouble playing games",
  HELP_ITEM_TROUBLE_STREAMING: "I am having trouble streaming videos",
  HELP_ITEM_TROUBLE_OTHER: "Other troubleshooting guides",
  HELP_ITEM_HOW_PROTECT_KIDS: "Protect my kids on the Internet",
  HELP_ITEM_HOW_MANAGE_DEVICES: "Manage devices",
  HELP_ITEM_HOW_BLOCK_DEVICES: "Block devices from connecting to the network",
  HELP_ITEM_HOW_IDENTIFY_DEVICES: "Identify unknown devices",
  HELP_ITEM_HOW_HNS_PROTECT: "Learn more about how " + PROD_NAME_SHORT + " protects my devices",

  DIALOG_SETTING_COMPAT_TITLE: "Network Settings",
  DIALOG_SETTING_COMPAT_MESSAGE: "Select the mode chosen by Support.",
  SETTING_COMPAT_MODE_0: "Normal Mode",
  SETTING_COMPAT_MODE_1: "Compatibility Mode",
  SETTING_COMPAT_MODE_2: "Special Compatibility Mode",

  ANDROID_PERMISSION_CAMERA: "Camera",
  ANDROID_PERMISSION_STORAGE: 'Storage',
  ANDROID_PERMISSION_REQUIRED: "{0} Permission Required",
  ANDROID_PERMISSION_REQUIRED_DETAIL: "The {0} permission is required to scan. Tap Settings to allow the permission.",

  // FOR FILTER TYPES
  FILTERING_ITEMS_SELECT_ALL: "Select All",
  FILTERING_ITEMS_EROTIC: "Erotic / Mature",
  FILTERING_ITEMS_INTIME_APPAREL: "Intimate Apparel / Swimsuit",
  FILTERING_ITEMS_NUDITY: "Nudity",
  FILTERING_ITEMS_PRONOGRAPY: "Pornography",
  FILTERING_ITEMS_SEX_EDUCATION: "Sex Education",
  FILTERING_ITEMS_BLOGS: "Blogs / Web Communications",
  FILTERING_ITEMS_INSTANT_MSG: "Chat / Instant Messaging",
  FILTERING_ITEMS_EMAIL: "Email",
  FILTERING_ITEMS_HACKING: "Hacking / Proxy Avoidance",
  FILTERING_ITEMS_NEWSGROUPS: "Newsgroups / Forums",
  FILTERING_ITEMS_P2P: "Peer-to-Peer (P2P) Networks",
  FILTERING_ITEMS_PHTOTO: "Photo Searches",
  FILTERING_ITEMS_SHARING_SERVICE: "Sharing Services",
  FILTERING_ITEMS_SOFTWARE_DOWNLOAD: "Software Downloads",
  FILTERING_ITEMS_STREAMING_MEDIA: "Streaming Media",
  FILTERING_ITEMS_SOCIAL_NETWORKKING: "Social Networking",
  FILTERING_ITEMS_WEB_AD: "Web Advertisement",
  FILTERING_ITEMS_ABORTION: "Abortion",
  FILTERING_ITEMS_CULT_OCCULT: "Cult / Occult",
  FILTERING_ITEMS_GUN_CLUBS: "Gun Clubs / Hunting ",
  FILTERING_ITEMS_ILLEAGE: "Illegal / Questionable ",
  FILTERING_ITEMS_TASTELESS: "Tasteless",
  FILTERING_ITEMS_VIOLENCE: "Violence / Hate / Racism ",
  FILTERING_ITEMS_WEAPONS: "Weapons / Military",
  FILTERING_ITEMS_ALCOHOL: "Alcohol / Tobacco",
  FILTERING_ITEMS_AUCTIONS: "Auctions",
  FILTERING_ITEMS_GAMBLING: "Gambling",
  FILTERING_ITEMS_SHOPPING: "Shopping",
};
