'use strict';

var PROD_NAME = "ウイルスバスター for Home Network";
var PROD_NAME_SHORT = "ｳｲﾙｽﾊﾞｽﾀｰHN";

module.exports = {
  PROD_NAME: PROD_NAME,
  PROD_NAME_SHORT: PROD_NAME_SHORT,
  SPLASH_LOGO: 'image_hns_lockup_jp',
  UNKNOWN: "検知したデバイス",
  ON: "オン",
  OFF: "オフ",

  PRIVACY_POLICY_LINK: "https://www.trendmicro.com/ja_jp/about/legal/privacy-policy-product.html",

  LEARN_MORE: "詳しく見る",
  TURN_ON_NOW: "有効にする",
  OR: "または",
  CLOSE: "閉じる",
  COUNTRY_DATA: {
    '248': 'Aland',
    '4': 'Afghanistan',
    '8': 'Albania',
    '12': 'Algeria',
    '16': 'American Samoa',
    '20': 'Andorra',
    '24': 'Angola',
    '660': 'Anguilla',
    '28': 'Antigua and Barbuda',
    '32': 'Argentina',
    '51': 'Armenia',
    '533': 'Aruba',
    '36': 'オーストラリア',
    '40': 'Austria',
    '31': 'Azerbaijan',
    '44': 'Bahamas',
    '48': 'Bahrain',
    '50': 'Bangladesh',
    '52': 'Barbados',
    '112': 'Belarus',
    '56': 'Belgium',
    '84': 'Belize',
    '204': 'Benin',
    '60': 'Bermuda',
    '64': 'Bhutan',
    '68': 'Bolivia',
    '70': 'Bosnia and Herzegovina',
    '72': 'Botswana',
    '76': 'Brazil',
    '96': 'Brunei',
    '100': 'Bulgaria',
    '854': 'Burkina Faso',
    '104': 'Burma (Myanmar)',
    '108': 'Burundi',
    '116': 'Cambodia',
    '120': 'Cameroon',
    '124': 'Canada',
    '132': 'Cape Verde',
    '136': 'Cayman Islands',
    '140': 'Central African Republic',
    '148': 'Chad',
    '152': 'Chile',
    '156': 'China',
    '170': 'Colombia',
    '162': 'Christmas Island',
    '166': 'Cocos (Keeling) Islands',
    '174': 'Comoros',
    '180': 'Congo, Democratic Republic of',
    '178': 'Congo, Republic of',
    '184': 'Cook Islands',
    '188': 'Costa Rica',
    '384': "Cote d'Ivoire",
    '191': 'Croatia',
    '196': 'Cyprus',
    '203': 'Czech Republic',
    '208': 'Denmark',
    '262': 'Djibouti',
    '212': 'Dominica',
    '214': 'Dominican Republic',
    '626': 'East Timor',
    '218': 'Ecuador',
    '818': 'Egypt',
    '222': 'El Salvador',
    '226': 'Equatorial Guinea',
    '232': 'Eritrea',
    '233': 'Estonia',
    '231': 'Ethiopia',
    '238': 'Falkland Islands',
    '234': 'Faroe Islands',
    '242': 'Fiji',
    '246': 'Finland',
    '250': 'France',
    '254': 'French Guiana',
    '258': 'French Polynesia',
    '266': 'Gabon',
    '270': 'Gambia',
    '268': 'Georgia',
    '276': 'Germany',
    '288': 'Ghana',
    '292': 'Gibraltar',
    '300': 'Greece',
    '304': 'Greenland',
    '308': 'Grenada',
    '316': 'Guam',
    '320': 'Guatemala',
    '831': 'Guernsey',
    '324': 'Guinea',
    '624': 'Guinea-Bissau',
    '328': 'Guyana',
    '332': 'Haiti',  
    '340': 'Honduras',
    '344': 'Hong Kong',
    '348': 'Hungary',
    '352': 'Iceland',
    '356': 'India',
    '360': 'Indonesia',
    '368': 'Iraq',
    '372': 'Ireland',
    '833': 'Isle of Man',
    '376': 'Israel',
    '380': 'Italy',
    '388': 'Jamaica',
    '392': '日本',
    '832': 'Jersey',
    '400': 'Jordan',
    '398': 'Kazakhstan',
    '404': 'Kenya',
    '296': 'Kiribati',
    '410': 'Korea, Republic of (South)',
    '414': 'Kuwait',
    '417': 'Kyrgyzstan',
    '418': 'Laos',
    '428': 'Latvia',
    '422': 'Lebanon',
    '426': 'Lesotho',
    '430': 'Liberia',
    '438': 'Liechtenstein',
    '440': 'Lithuania',
    '442': 'Luxembourg',
    '446': 'Macao',
    '807': 'Macedonia',
    '450': 'Madagascar',
    '454': 'Malawi',
    '458': 'Malaysia',
    '462': 'Maldives',
    '466': 'Mali',
    '470': 'Malta',
    '584': 'Marshall Islands',
    '478': 'Mauritania',  
    '480': 'Mauritius',
    '175': 'Mayotte',
    '484': 'Mexico',
    '583': 'Micronesia, Federated States of',
    '498': 'Moldova',
    '492': 'Monaco',
    '496': 'Mongolia',
    '9891': 'Montenegro',
    '500': 'Montserrat',
    '504': 'Morocco',
    '508': 'Mozambique',
    '580': 'N. Mariana Islands',
    '516': 'Namibia',
    '520': 'Nauru',
    '524': 'Nepal',
    '528': 'Netherlands',
    '530': 'Netherlands Antilles',
    '540': 'New Caledonia',
    '554': 'ニュージーランド',
    '558': 'Nicaragua',
    '562': 'Niger',
    '566': 'Nigeria',
    '570': 'Niue',
    '574': 'Norfolk Island',
    '578': 'Norway',
    '512': 'Oman',
    '586': 'Pakistan',
    '585': 'Palau',
    '591': 'Panama',
    '598': 'Papua New Guinea',
    '600': 'Paraguay',
    '604': 'Peru',
    '608': 'Philippines',  
    '612': 'Pitcairn',
    '616': 'Poland',
    '620': 'Portugal',
    '630': 'Puerto Rico',
    '634': 'Qatar',
    '638': 'Reunion',
    '642': 'Romania',
    '643': 'Russia Federation',
    '646': 'Rwanda',
    '654': 'Saint Helena',
    '659': 'Saint Kitts and Nevis',
    '662': 'Saint Lucia',
    '666': 'Saint Pierre and Miquelon',
    '670': 'Saint Vincent and the Grenadines',
    '882': 'Samoa',
    '674': 'San Marino',
    '678': 'Sao Tome and Principe',
    '682': 'Saudi Arabia',
    '686': 'Senegal',
    '891': 'Serbia',
    '690': 'Seychelles',
    '694': 'Sierra Leone',
    '702': 'Singapore',
    '703': 'Slovakia',
    '705': 'Slovenia',
    '90': 'Solomon Islands',
    '706': 'Somalia',
    '710': 'South Africa',
    '724': 'Spain',
    '144': 'Sri Lanka',
    '740': 'Suriname',
    '744': 'Svalbard',
    '748': 'Swaziland',
    '752': 'Sweden',
    '756': 'Switzerland',
    '158': '台湾',
    '762': 'Tajikistan',
    '834': 'Tanzania',
    '764': 'Thailand',
    '768': 'Togo',
    '772': 'Tokelau',
    '776': 'Tonga',
    '780': 'Trinidad and Tobago',
    '788': 'Tunisia',
    '792': 'Turkey',
    '795': 'Turkmenistan',
    '796': 'Turks and Caicos Islands',
    '798': 'Tuvalu',
    '800': 'Uganda',
    '804': 'Ukraine',
    '784': 'United Arab Emirates',
    '826': 'United Kingdom',
    '840': 'アメリカ合衆国',
    '858': 'Uruguay',
    '860': 'Uzbekistan',
    '548': 'Vanuatu',
    '336': 'Vatican City State',
    '862': 'Venezuela',
    '704': 'Vietnam',
    '92': 'Virgin Islands, British',
    '850': 'Virgin Islands, US',
    '876': 'Wallis and Futuna',
    '732': 'Western Sahara',
    '887': 'Yemen',
    '894': 'Zambia',
    '716': 'Zimbabwe',
  },
  FROM_TO: "{0} から {1} の間",
  TO: "{0} から {1}",
  AT: "{0}",
  AND: "および",
  VIEW_ALL: "全て見る",
  LOCALE_H: "Ah時",
  LOCALE_LT: "A hh:mm",
  LOCALE_L: "MMMDD日",
  LOCALE_LL: "YYYY年MMM",
  LOCALE_LLL: "YYYY年MMMDD日",
  LOCALE_LLLL: "YYYY年MMMDD日 HH:mm:ss",
  LOCALE_TODAY: "今日",
  LOCALE_YESTERDAY: "昨日",
  LOCALE_TOMORROW: "明日",
  HOUR_UNIT: "{0}時間",
  HOUR: "1時間",
  HOURS: "{0}時間",
  MINUTE_UNIT: "{0}分",
  MINUTE: "1分",
  MINUTES: "{0}分",
  MINUTE_CAP:"1分",
  MINUTES_CAP:"{0}分",
  HOUR_CAP:"1時間",
  HOURS_CAP:"{0}時間",
  DURATION_H: "{0}時間",
  DURATION_M: "{0}分",
  YEARLY: "年契約",
  MONTHLY: "月契約",
  LESS_THAN:"未満",
  INTERNET_USE_ONLINE:"インターネットを利用",
  DURATION_ONLINE: "オンライン {0}",
  DURATION_OFFLINE: "オフライン {0}",
  UPDATED: "New",
  UPDATING: "アップデートしています",
  PAUSE: "一時停止",
  RESUME: "再開",
  STATUS_BAR_STATION_OFFLINE_TITLE: "本体がオフラインです",
  STATUS_BAR_STATION_OFFLINE_TITLE_POPUP: "本体がオフラインです",
  STATUS_BAR_STATION_OFFLINE_DESC: "本体をインターネットに接続し、\n再度お試しください。",
  STATUS_BAR_NO_INTERNET_TITLE: "インターネットに接続されていません。",
  STATUS_BAR_NO_INTERNET_TITLE_POPUP: "インターネットに接続してください。",
  STATUS_BAR_NO_INTERNET_DESC: "デバイスがインターネットに接続されていることを確認し、再度お試しください。",
  STATUS_BAR_STATION_UPDATING_TITLE: "本体のアップデート中です。",
  STATUS_BAR_STATION_UPDATING_DESC: "本体のアップデートが完了するまでお待ちいただき、後ほど再度お試しください。",
  STATUS_BAR_STATION_EXPIRED_RENEW_TITLE: "有効期限が終了しています。<a href=http://renew>更新してください</a>",
  STATUS_BAR_STATION_EXPIRED_TITLE: "有効期限が終了しています。<a href=http://contact-support>お問い合わせ</a>",
  STATUS_BAR_STATION_EXPIRED_TITLE_ANZ: "更新するには<a href=http://sso>トレンドマイクロアカウント</a>にログインしてください",
  TOAST_THANKS_FEEDBACK: "ご協力ありがとうございました",
  TOAST_SAVED: "保存完了",
  TOAST_CACHE_CLEARED: "Cache cleared",
  TOAST_SUBSCRIPTION_EXPIRES: "サービス有効期限",
  TOAST_SUBSCRIPTION_EXPIRES_JP: "有効期限",
  TOAST_SUBSCRIPTION_EXPIRED: "有効期間終了",
  TOAST_SUBSCRIPTION_EXPIRED_JP: "有効期間終了",
  TOAST_SUBSCRIPTION_EXPIRE_JP: "<a href=http://sso>トレンドマイクロアカウント</a>にログインするか [更新する] をタップして更新してください。",
  TOAST_SUBSCRIPTION_EXPIRE_ANZ: "更新するには、<a href=http://sso>トレンドマイクロアカウント</a>にログインしてください。",
  TOAST_CONTACT_SUPPORT: "メールをご確認いただくか、<a href=http://contact-support>こちら</a>からお問い合わせください。",
  TOAST_CONTACT_SUPPORT_JP: "メールをご確認いただくか、<a href=http://sso>トレンドマイクロアカウント</a>にログインし、更新してください",
  TOAST_ONE_RULE_PER_DAY: "1ルール/曜日",
  TOAST_REMOVED_FROM_APPROVED_LIST: "許可リストから削除されました",
  TOAST_DEVICE_SETTING_SAVED: "{0}の設定を保存しました",
  TOAST_DEVICE_BLOCKED: "{0}をブロックしました",
  TITLE_SECTION_DASHBOARD: "ダッシュボード",
  TITLE_SECTION_TIMELINE: "タイムライン",
  TITLE_SECTION_DEVICES: "デバイス一覧",
  TITLE_SECTION_FAMILY: "家族一覧",
  TITLE_SECTION_NETWORK: "ネットワーク",
  TITLE_SECTION_SETTINGS: "設定",
  TITLE_SECTION_TUTORIALS: "チュートリアル",
  TITLE_SECTION_COMMUNITY: "コミュニティサイトへ",
  TITLE_SECTION_HELP: "ヘルプ",
  ACTION_BAR_DONE: "完了",
  ACTION_BAR_SKIP: "スキップ",
  ACTION_BAR_NEXT: "次へ",
  ACTION_BAR_OK: "OK",
  DIALOG_CONFIRM_YES: "はい",
  DIALOG_CONFIRM_NO: "いいえ",
  DIALOG_CONFIRM_OK: "OK",
  DIALOG_CONFIRM_CANCEL: "キャンセル",
  DIALOG_CONFIRM_DISCONNECT: "解除",
  DIALOG_CONFIRM_RESET: "リセット",
  DIALOG_CONFIRM_NOT_NOW: "後で行う",
  DIALOG_CONFIRM_SET_UP: "設定する",
  DIALOG_CONFIRM_CHANGE: "変更",
  DIALOG_CONFIRM_CLOSE: "閉じる",
  DIALOG_CONFIRM_ASSIGN: "実施する",
  DIALOG_CONFIRM_JOIN: "OK",
  DIALOG_CONFIRM_REFRESH: "再試行",    
  DIALOG_CONFIRM_GET_HELP: "ヘルプ",
  DIALOG_CONFIRM_SELECT: "今すぐ",
  DIALOG_CONFIRM_CONTINUE: "続行",
  DIALOG_CONFIRM_CONTINUE_ALTER: "次へ",
  DIALOG_CONFIRM_ACCEPT_AND_CONTINUE: "同意して次へ",
  DIALOG_CONFIRM_DELETE:"削除",
  DIALOG_CONFIRM_NEXT: "次へ",
  DIALOG_CONFIRM_EDIT: "編集",
  DIALOG_CONFIRM_BACK: "戻る",
  DIALOG_LINK_LEARNMORE: "詳しく見る",
  DIALOG_LINK_FEEDBACK: "製品を評価する",
  ERROR_MAINTENENCE: "メンテナンス中です",
  ERROR_MAINTENENCE_DETAIL: "本システムはメンテナンス中のためご利用できません。再度お試しください。",
  ERROR_MAINTENENCE_UNKNOWN_DETAIL: "本システムはメンテナンス中のためご利用できません。再度お試しください。",
  ERROR_NO_MAIL_ACCOUNT: "メールアカウントが見つかりません",
  ERROR_NO_MAIL_ACCOUNT_DETAIL: "メールアカウントを設定の上、再度お試しください。",
  ERROR_CAMERAROLL_UNAVAILABLE: "写真にアクセスできません",
  ERROR_CAMERAROLL_UNAVAILABLE_DETAIL: "お使いのデバイスのプライバシー設定で、写真へのアクセスを承認してください。繰り返し表示される場合はサポートにお問い合わせください。",
  ERROR_GENERAL: "ご利用継続できません。",
  ERROR_GENERAL_DETAIL: "再度お試しください。<a href=http://help>ヘルプ</a> (Error code: {0})",
  WELCOME_TITLE: "ようこそ",
  WELCOME_SUBTITLE: PROD_NAME + "はあなたのデバイスとデータを不正な攻撃から守ります。",
  WELCOME_ACCEPT: "同意して次へ",
  WELCOME_EULA: "「<a href=http://agree>サービス利用規約、お客さまへの注意事項およびプライバシーと個人データの収集に関する規定</a>」および「<a href=http://privacy>お客さまから収集する個人情報の取り扱いについて</a>」をご確認いただき、同意したうえでご利用ください。",
  WELCOME_UBM_TITLE: "製品の機能向上にご協力ください",
  WELCOME_UBM_DETAIL: "下のチェックボックスをオンにすると、製品使用データおよびクラッシュ情報を匿名でトレンドマイクロに送信し、本製品の機能向上のために役立てることもできます。チェックボックスをオンにしない場合でも、本製品の機能と動作には影響はありません。",
  GDPR_TITLE: "プライバシーと個人データの収集に関する規定",
  GDPR_DETAIL: PROD_NAME + "の一部の機能は、お客さまの製品の利用状況や検出にかかわる情報を収集してトレンドマイクロに送信します。この情報は一定の管轄区域内および特定の法令等において個人データとみなされることがあります。\n\n本製品をインストールすると、お客さまのインターネット上のアクティビティを保護するために次の情報がトレンドマイクロに送信されます。\n\nアカウントIDとなるメールアドレス\nパスワード\n名\n姓\n言語\n電話番号\n\nこれらの情報の一部は、お客さまが関連機能を無効にすることで、トレンドマイクロによるデータの収集を停止することができます。データ収集機能の無効化の詳細な方法については、本製品の<a href=DCN>データ収集について</a>をご確認ください。一部のデータ収集機能は無効にできません。\n\nデータの収集についての詳細は、トレンドマイクロの<a href=privacy>プライバシーポリシー</a>をご確認ください。",
  GDPR_MESSAGE: "",
  GDPR_UBM: "本製品の機能向上のため、製品使用データを匿名でトレンドマイクロに送信することに同意する",
  GDPR_CRASH_REPORT: "本製品の機能向上のため、クラッシュ情報を匿名でトレンドマイクロに送信することに同意する",
  PRIVACY_POLICY: "プライバシーポリシー",
  DATA_COLLECTION: "データ収集について",
  REMOTE_PAIRING_TITLE: "本体への接続",
  REMOTE_PAIRING_INSTRUCTION: "ペアリングコードを入力してください。ペアリングコードは大文字と小文字を分けて入力してください。",
  REMOTE_PAIRING_HINT: "ペアリングコードが分からない場合はこちら",
  LAN_PAIRING_TITLE: "接続中です",
  LAN_PAIRING_INSTRUCTION: "本体のインターネット接続を維持し、お使いのスマートフォンを本体と同じWi-Fiネットワークに接続したままお待ちください。本体への接続には時間がかかる場合があります。<a href='pairing'>詳しく見る</a>",
  LAN_PAIRING_ERROR_NO_INTERNET: "無線LANに接続してください。",
  LAN_PAIRING_ERROR_NO_INTERNET_DETAIL: "お使いのスマートフォンを無線LANに接続し、再度お試しください。",
  LAN_PAIRING_ERROR_OVERSEAT: "接続に失敗しました。",
  LAN_PAIRING_ERROR_OVERSEAT_DETAIL: "ペアリングコードをご確認いただくか、正しい本体とペアリングの上、再度お試しください。<a href=http://overseat>ヘルプ</a> (Error code: {0})",
  LAN_PAIRING_ERROR_INCORRECT_PAIRING_CODE: "ペアリングコードが誤っています。",
  LAN_PAIRING_ERROR_INCORRECT_PAIRING_CODE_DETAIL: "ペアリングコードをお確かめの上、再度お試しください。<a href=http://incorrect-pairing-code>ヘルプ</a> (Error code: {0})",
  LAN_PAIRING_ERROR_INCORRECT_STATION_CODE: "ステーションコードが誤っています。",
  LAN_PAIRING_ERROR_INCORRECT_STATION_CODE_DETAIL: "ステーションコードをお確かめの上、再度お試しください。<a href=http://incorrect-station-code>ヘルプ</a> (Error code: {0})",
  LAN_PAIRING_ERROR_BOX_OFFLINE: "接続に失敗しました。",
  LAN_PAIRING_ERROR_BOX_OFFLINE_DETAIL: "1. 本体がお使いのLANポートに正しく接続されていることを確認してください\n2. 本体のステータスランプがグリーンになるまでお待ちください",
  LAN_PAIRING_ERROR_NOT_SAME_WIFI: "本体をご確認ください。",
  LAN_PAIRING_ERROR_NOT_SAME_WIFI_DETAIL: "本体背面に表示されているステーションコードをスキャンする必要があります。",
  LAN_PAIRING_ERROR_RETURNED_PAIRING_CODE: "無効化されたペアリングコードです",
  LAN_PAIRING_ERROR_RETURNED_PAIRING_CODE_DETAIL: "このペアリングコードは無効化されています。別のペアリングコードで再度お試しください。<a href=http://returned-pairing-code>ヘルプ</a> (Error code: {0})",
  BOX_STATUS_TITLE: "本体をアップデートしています",
  BOX_STATUS_DESC_1: "アップデート中は本体がオフラインになり、ステータスランプが赤に変わります。<a href='updating'>詳しく見る</a>",
  BOX_STATUS_DESC_2: "アップデート中は本体がオフラインになり、ステータスランプが赤に変わります。本体をLANポートおよび電源に接続したままお待ちください。<a href='waiting'>詳しく見る</a>",
  BOX_STATUS_ERROR: "次のエラーコードを<a href='support'>サポート</a>までご連絡ください: {0}",
  BOX_STATUS_OFFLINE_TITLE: "本体を再接続してください",
  BOX_STATUS_OFFLINE_DESC: "本体のLANケーブルがルータのLANポートと正しく接続されているかお確かめの上、再度お試しください。<a href='offline'>詳しく見る</a>",
  BOX_STATUS_NO_INTERNET_TITLE: "インターネットに接続されていません",
  BOX_STATUS_NO_INTERNET_DESC: "本体のアップデートを完了するには、このデバイスをインターネットに再接続してください。<a href='no-internet'>詳しく見る</a>",
  BOX_STATUS_UPDATED: "本体のアップデートが完了しました",
  BOX_STATUS_STATION_DETECTING: "本体を検出しています",
  BOX_STATUS_CHECKING_STATION: "本体を確認しています",
  BOX_STATUS_EXTRACTING: "データを抽出しています",
  BOX_STATUS_DECRYPTING: "データを復号しています",
  BOX_STATUS_VERIFYING: "データを検証しています",
  BOX_STATUS_STATION_UPDATING: "本体をアップデートしています",
  BOX_STATUS_UPDATING: "アップデートしています",
  BOX_STATUS_CONTINUE_UPDATE: "アップデートしています",
  BOX_STATUS_KEEP_PLUG_IN: "このままお待ちください",
  PAIRING_TITLE: "ステーションコードのスキャン",
  PAIRING_SUBTITLE_SCAN: "本体背面に表示されているステーションコードをスキャンしてください。<a href=http://more>詳しく見る</a>",
  PAIRING_SCAN_NOW: "スキャンする",
  PAIRING_SUCCESS: "接続が完了しました",
  PAIRING_CAMERA_UNAVAILABLE_TITLE: "カメラにアクセスできません",
  PAIRING_CAMERA_UNAVAILABLE_MESSAGE: "アプリがカメラにアクセスできるかをご確認ください。本エラーが継続する場合はサポートセンターにお問い合わせください。",
  ACCOUNT_INFO_EMAIL: "メールアドレス",
  ACCOUNT_INFO_EMAIL_ALTER: "メール",
  ACCOUNT_INFO_PWD: "パスワード",
  ACCOUNT_INFO_FNAME: "名",
  ACCOUNT_INFO_LNAME: "姓",
  ACCOUNT_INFO_FULLNAME: "姓名",
  ACCOUNT_INFO_COUNTRY: "国",
  ACCOUNT_INFO_PHONE: "電話番号",
  ACCOUNT_INFO_ERROR_NO_DATA: "必須入力です",
  ACCOUNT_INFO_ERROR_WRONG_EMAIL_FORMAT: "メールアドレスのフォーマットが正しくありません",
  ACCOUNT_INFO_ERROR_EMAIL_EXIST: "既に利用されています。<a href='http://signin'>サインインを行ってください。</a>",
  ACCOUNT_INFO_ERROR_WRONG_NAME_FORMAT: "/ \\ * ? “ < > | & :は利用できません。",
  ACCOUNT_INFO_ERROR_WRONG_PWD_FORMAT: "8文字以上で設定してください。",
  ACCOUNT_INFO_ERROR_WRONG_PWD_FORMAT2: "利用できない文字が含まれています。",
  ACCOUNT_INFO_ERROR_WRONG_PWD_NOT_MATCH: "パスワードが一致しません。",
  ACCOUNT_INFO_ERROR_WRONG_PHONE_FORMAT: "3文字以上で入力してください。",
  ACCOUNT_INFO_ERROR_NUMBER_ONLY: "使用できるのは数字のみです",
  SIGNIN_TITLE: "サインイン",
  SIGNIN_DESC: PROD_NAME + "を使用するには、トレンドマイクロアカウントでのログインが必要です。",
  SIGNIN_DESC_ALTER: PROD_NAME + "を使用するには、トレンドマイクロアカウントでのログインが必要です。",
  SIGNIN_FORGET_PWD: "パスワードを忘れた場合",
  SIGNIN_BUTTON: "サインイン",
  SIGNIN_NEED_ACCOUNT: "トレンドマイクロをお持ちでない場合",
  SIGNIN_CREATE_ACCOUNT: "アカウント新規作成",
  SIGNIN_ERROR: "サインインできません",
  SIGNIN_ERROR_DETAIL: "登録されているメールアドレスとパスワードをご利用ください。",
  SIGNIN_ERROR_DETAIL_ALTER: "パスワードをお確かめの上、再度お試しください。",
  SIGNUP_TITLE: "アカウント新規作成",
  SIGNUP_DESC: PROD_NAME + "のご利用開始のためにトレンドマイクロアカウントを作成してください。",
  SIGNUP_DESC_LINK: "若しくは<a href='http://signin'>サインインを行ってください。</a>",
  SIGNUP_PWD_DESC: "メールアドレスの確認",
  SIGNUP_CREATE_PWD: "パスワードの作成",
  SIGNUP_PWD: "パスワード",
  SIGNUP_CONFIRM_PWD: "パスワードの確認",
  SIGNUP_PWD_HINT: "8文字以上を入力してください。",
  SIGNUP_RECEIVE_NEWS: "トレンドマイクロからのニュースや最新情報を受け取る。",
  SIGNUP_BUTTON: "アカウント新規作成",
  LOGIN: "ログイン",
  TUTORIAL_TIMELINE: "攻撃やリスクの可視化",
  TUTORIAL_TIMELINE_DESC: "ご家庭のネットワークに発生している攻撃やセキュリティ上のリスクをタイムラインで見ることができます。",
  TUTORIAL_DEVICE: "接続デバイスを可視化",
  TUTORIAL_DEVICE_DESC: "ご家庭のネットワークに接続されたデバイスを確認し、デバイスや利用者別にセキュリティ設定を行うことができます。",
  TUTORIAL_FAMILY: "ご家族に安全なインターネット利用を提供",
  TUTORIAL_FAMILY_DESC: "ご家族が閲覧するWebサイトや、インターネットの利用時間を設定できます。",
  TUTORIAL_ANTIVIRUS: "セキュリティソフトと併せてご利用ください",
  TUTORIAL_ANTIVIRUS_DESC: "USBメモリ経由のウイルスなど、ネットワーク外の攻撃リスクから守るため、従来のPCやスマートフォン向けのセキュリティソフトと併せてご利用ください。",
  TUTORIAL_TRY_IT_NOW: "このデバイスで試してみる",
  TUTORIAL_TRY_DIFF_DEVICE: "別の接続デバイスで試してみる",
  TUTORIAL_WTP_TITLE: "安全でない可能性のあるWebサイトから保護します",
  TUTORIAL_WTP_DESC: PROD_NAME_SHORT + "は世界的に広く認められたWeb脅威対策により、ホームネットワーク内のデバイスを攻撃から保護します。",
  TUTORIAL_WTP_STEP1: "デバイスを本体と同じネットワークに接続してください。",
  TUTORIAL_WTP_STEP2: "接続したデバイスから次のWebサイトにアクセスすれば" + PROD_NAME + "の保護機能を確認できます。",
  TUTORIAL_CONNECT_TO_TEST_TITLE: "接続テスト",
  TUTORIAL_CONNECT_TO_TEST_MESSAGE: "デバイスが本体と同じWi-Fiネットワークに接続していることを確認し、再度お試しください。",
  BOX_RESET_TITLE: "本体への接続",
  BOX_RESET_DESC: "本体がリセットされました。再度ペアリングを行ってください。<a href=http://set-up-new>ヘルプ</a>",
  AFTER_RMA_TITLE: "本体への接続",
  AFTER_RMA_DESC: "返品されました。新しい本体へ接続してください。<a href=http://set-up-new>ヘルプ</a>",
  REFUND_TITLE: "本体への接続",
  REFUND_DESC: PROD_NAME + "が交換されました。再接続を行ってください。<a href=http://set-up-new>ヘルプ</a>",
  EOLA_TITLE: "ご利用期限切れです",
  EOLA_DESC: "<a href=http://vendor>{0}</a>にお問い合わせください。",
  EOLA_PAIRING_CODE: "ペアリングコード",
  EOLA_SET_UP_NEW: "<a href=http://set-up-new>若しくは、別の本体をセットアップしてください。</a>",
  EOLB_TITLE: "ご利用ありがとうございました",
  EOLB_DESC: "ご利用ありがとうございました。本サービスは終了しました。ご不明な点は<a href=http://vendor>{0}</a>にお問い合わせください。",
  UPDATE_NEEDED_TITLE: "最新版をご利用ください",
  UPDATE_NEEDED_DESC: "以下のボタンから最新版を入手してください。<a href=http://update-needed>詳しく見る</a>",
  UPDATE_NEEDED_ACTION: "最新版を入手する",
  DEVICE_UPDATE_NEEDED_TITLE: "最新版をご利用ください",
  DEVICE_UPDATE_NEEDED_DESC: PROD_NAME + "アプリを継続してご利用いただくにはデバイスを{0} {1}に更新してください。<a href=http://update-needed>詳しく見る</a>",
  PUG_BLOCK_OPTIN_TITLE: "管理用アプリ (共創コミュニティ向け) が必要です",
  PUG_BLOCK_OPTIN_DESC: PROD_NAME + " 共創コミュニティに参加しました。管理用アプリ (共創コミュニティ向け) をインストールしてください。",
  PUG_BLOCK_OPTOUT_TITLE: "ありがとうございました",
  PUG_BLOCK_OPTOUT_DESC: PROD_NAME + " 共創コミュニティを退会しました。製品版" + PROD_NAME + "アプリをインストールしてください。",
  ACTION_REQUIRED_TITLE: "ご確認ください",
  UNSECURED: "保護対象外",
  DEVICE_ADDME_TITLE_0: "デバイスを特定したいですか？",
  DEVICE_ADDME_SUBTITLE_0: "特定したいデバイスを本体のネットワークに接続し、http://addme.tmにアクセスします。デバイス名の追加または更新ができます。",
  DEVICE_ADDME_IMAGE_0: "bg_device_identify_a0_jp",
  DEVICE_ADDME_TITLE_1: "デバイスをかんたんに見つけるには",
  DEVICE_ADDME_SUBTITLE_1: "ご家庭のネットワーク内にあるデバイスの電源を入れると、" + PROD_NAME + "はより高い精度でデバイスを見つけることができます。",
  DEVICE_ADDME_TITLE_2: "デバイスを追加しますか？",
  DEVICE_ADDME_SUBTITLE_2: "追加するデバイスを使用して本体のネットワークに接続し、http://addme.tmにアクセスします。デバイス名は追加することも更新することもできます。",
  DEVICE_ADDME_DESC: PROD_NAME + "は{0}件のデバイスを認識しています...",
  DEVICE_ADDME_DESC_SINGLE: PROD_NAME + "は{0}件のデバイスを認識しています...",
  DEVICE_ACCESS_REQUEST: "{0}がネットワークへの参加を要求しています",
  DEVICE_ACCESS_UNKNOWN: "新しいデバイス",
  DEVICE_ACCESS_DETECTED: "検出日時",
  DEVICE_ACCESS_ALLOW: "接続を承認する",
  DEVICE_ACCESS_BLOCK: "ブロックする",
  DEVICE_UNASSIGNED: "利用者が未設定のデバイス",
  DEVICE_UNASSIGNED_SUBTITLE: "これらのデバイスにも保護機能は適用されています",
  DEVICE_PRIMARY_ROUTER: "メインルータ",
  DEVICE_NO_DEVICES: "接続されているデバイスがありません",
  DEVICE_NO_ONLINE_DEVICES: "接続中のデバイスはありません",
  DEVICE_SHOW_ALL_DEVICES: "すべてのデバイス",
  DEVICE_BTN_SHOW_ALL_DEVICES: "すべてのデバイスを表示",
  DEVICE_BTN_SHOW_ONLINE_DEVICES: "接続中のデバイスのみを表示",
  DEVICE_SHOW_ONLINE_DEVICES: "接続中のデバイス",
  DEVICE_TAB_REPORT: "レポート",
  DEVICE_TAB_SETTINGS: "設定",
  DEVICE_SETTINGS_OWNER: "利用者",
  DEVICE_SETTINGS_OWNER_HINT: "利用者を選択する",
  DEVICE_SETTINGS_OWNER_NEW_DEVICE: "利用者を設定してください",
  DEVICE_SETTINGS_OWNER_ALLOWED_HINT: "{0}の接続を承認しました。このデバイスの利用者を設定してください。",
  DEVICE_SETTINGS_REMOVE_OWNER: "利用者を設定しない",
  DEVICE_SETTINGS_DEVICE_NAME: "デバイス名",
  DEVICE_SETTINGS_DEVICE_NAME_HINT: "デバイス名を登録する",
  DEVICE_SETTINGS_DEVICE_NAME_DETECTED: PROD_NAME_SHORT + "により検出されたデバイスのホスト名: {0}",
  DEVICE_SETTINGS_TYPE: "デバイス種類",
  DEVICE_SETTINGS_TYPE_HINT: "デバイスの種類を登録する",
  DEVICE_SETTINGS_TYPE_OTHER: "その他",
  DEVICE_SETTINGS_TYPE_CAMERA: "IPカメラ",
  DEVICE_SETTINGS_TYPE_NAS: "ファイルサーバー",
  DEVICE_SETTINGS_TYPE_ROUTER: "ルーター",
  DEVICE_SETTINGS_TYPE_PC: "Windows PC",
  DEVICE_SETTINGS_TYPE_MAC: "Mac",
  DEVICE_SETTINGS_TYPE_IPHONE: "iPhone",
  DEVICE_SETTINGS_TYPE_PRINTER: "プリンター",
  DEVICE_SETTINGS_TYPE_GAME_CONSOLE: "ゲーム機",
  DEVICE_SETTINGS_TYPE_TV: "テレビ",
  DEVICE_SETTINGS_TYPE_ANDROID_PHONE: "Android スマートフォン",
  DEVICE_SETTINGS_TYPE_IPAD: "iPad",
  DEVICE_SETTINGS_TYPE_TABLET: "タブレット",
  DEVICE_SETTINGS_TYPE_NOTEBOOK: "Windows ノートブック",
  DEVICE_SETTINGS_TYPE_JEWELRY_BOX: "JewelryBox",
  DEVICE_SETTINGS_TYPE_KINDLE: "電子書籍リーダー",
  DEVICE_SETTINGS_TYPE_PHONE: "電話",
  DEVICE_SETTINGS_TYPE_MEDIA_DEVICE: "メディアデバイス",
  DEVICE_SETTINGS_TYPE_MACBOOK: "MacBook",
  DEVICE_SETTINGS_TYPE_HOME_CONTROLLER: "スマートホームコントローラー",
  DEVICE_SETTINGS_TYPE_WIFI_SPEAKER: "無線スピーカー",
  DEVICE_SETTINGS_TYPE_HUB: "ハブ",
  DEVICE_SETTINGS_TYPE_ROBOT: "ロボット",
  DEVICE_SETTINGS_TYPE_PLUG: "スマートプラグ",
  DEVICE_SETTINGS_TYPE_WATCH: "スマートウォッチ",
  DEVICE_SETTINGS_TYPE_THERMOSTAT: "サーモスタット",
  DEVICE_SETTINGS_TYPE_LIGHT_BULB: "スマート電球",
  DEVICE_SETTINGS_TYPE_WEIGHT_METER: "体重計",
  DEVICE_SETTINGS_TYPE_AIR_PURIFIER: "空気清浄器",
  DEVICE_SETTINGS_TYPE_3DS: "3DS",
  DEVICE_SETTINGS_TYPE_REFRIGERATOR: "冷蔵庫",
  DEVICE_SETTINGS_TYPE_PLAYSTATION: "PlayStation",
  DEVICE_SETTINGS_TYPE_AMAZON_ECHO: "Echo",
  DEVICE_SETTINGS_TYPE_GOOGLE_HOME: "Home",
  DEVICE_SETTINGS_TYPE_NINTENDO_SWITCH: "Nintendo Switch",
  DEVICE_SETTINGS_TYPE_XBOX_ONE: "Xbox One",
  DEVICE_SETTINGS_TYPE_HOME_POD: "HomePod",
  DEVICE_SETTINGS_TYPE_DOORBELL: "スマートドアベル",
  DEVICE_SETTINGS_TYPE_BABY_MONITOR: "ベビーモニター",
  DEVICE_SETTINGS_TYPE_COOKING: "スマート調理器具",
  DEVICE_SETTINGS_TYPE_DOOR_SECURITY_CAMERA: "屋内防犯カメラ",
  DEVICE_SETTINGS_TYPE_IROBOT: "電気掃除機",
  DEVICE_SETTINGS_TYPE_LIGHTS_SWITCH: "電灯スイッチ",
  DEVICE_SETTINGS_TYPE_OUTDOOR_SECURITY_CAMERA: "屋外防犯カメラ",
  DEVICE_SETTINGS_TYPE_REMOTE_CONTROL: "リモコン",
  DEVICE_SETTINGS_TYPE_SMART_SPRINKLERS: "スプリンクラー",
  DEVICE_SETTINGS_TYPE_SMART_BTN: "スマートボタン",
  DEVICE_SETTINGS_TYPE_SMART_CAR: "車",
  DEVICE_SETTINGS_TYPE_PET_CAMERA_FEEDER: "ペット自動給餌器/カメラ",
  DEVICE_SETTINGS_TYPE_SMART_DOOR_LOCK: "スマートロック",
  DEVICE_SETTINGS_TYPE_TV_STICK: "TVスティック",
  DEVICE_SETTINGS_TYPE_AUDIO_RECEIVER: "オーディオレシーバー",
  DEVICE_SETTINGS_TYPE_SMART_HOME_HUB: "スマートホームハブ",
  DEVICE_SETTINGS_TYPE_SMOKE_DETECTOR: "煙感知器",
  DEVICE_SETTINGS_TYPE_BLURAY_PLAYER: "ブルーレイディスク/DVDプレーヤー",
  DEVICE_SETTINGS_TYPE_SMART_SPEAKER_GENERIC: "スマートスピーカー",
  DEVICE_SETTINGS_ADDME_TITLE: "このデバイスを認識",
  DEVICE_SETTINGS_ADDME_DESC: "[詳しく見る] をタップしてデバイスを認識する方法を確認してください。",
  DEVICE_SETTINGS_SIMILAR_TITLE: "デバイス概要の変更",
  DEVICE_SETTINGS_SIMILAR_DESC: "タップして、このデバイス概要を変更する方法を確認します",
  DEVICE_SETTINGS_UNSECURED_TITLE: "保護対象外のデバイス",
  DEVICE_SETTINGS_UNSECURED_DESC: "保護対象外のデバイスのリストから削除し、保護を有効にするには、[解除] をタップします。",
  DEVICE_SETTINGS_UNSECURED_REMOVE: "解除",
  DEVICE_SETTINGS_UNSECURED_MODIFY_HINT: "設定が変更されました",
  DEVICE_SETTINGS_UNSECURED_MODIFY_HINT_DETAIL: "本機能の設定変更が有効になるまで時間がかかる場合があります。すぐに有効にするには、デバイスを再起動してください。",
  DEVICE_SETTINGS_BRAND: "メーカー",
  DEVICE_SETTINGS_BRAND_HINT: "メーカー名を登録する",
  DEVICE_SETTINGS_MODEL: "型番",
  DEVICE_SETTINGS_MODEL_HINT: "型番を登録する",
  DEVICE_SETTINGS_PORTS: "有効なポート",
  DEVICE_SETTINGS_PORTS_DESC: "使用中または開いているポートの一覧",
  DEVICE_SETTINGS_PORTS_PORT: "ポート番号",
  DEVICE_SETTINGS_PORTS_PROTOCOL: "プロトコル",
  DEVICE_SETTINGS_DEVICE_ADDRESS: "IPアドレス",
  DEVICE_SETTINGS_DEVICE_HOSTNAME: "ホスト名",
  DEVICE_SETTINGS_DEVICE_IPV6_ADDRESS: "IPv6アドレス",
  DEVICE_SETTINGS_DEVICE_MAC: "MACアドレス",
  DEVICE_SETTINGS_ALLOW_CONNECT: "ネットワークへの接続を許可",
  DEVICE_SETTINGS_GUIDE: "デバイス情報をカスタマイズする方法については、<a href=''>こちら</a>をタップしてください。",                          
  DEVICE_SETTINGS_DELETE: "このデバイスを一覧から削除",
  DEVICE_SETTINGS_DELETE_DIALOG_TITLE: "このデバイスを一覧から削除しますか？",
  DEVICE_SETTINGS_DELETE_CONFIRM_MESSAGE: "このデバイスがネットワークに接続すると再度認識されます。",
  DEVICE_SETTINGS_BLOCK_TITLE: "ネットワークから切断",
  DEVICE_SETTINGS_BLOCK_MESSAGE: "このデバイスをネットワークから切断しますか？",
  DEVICE_SETTINGS_FOOTER_PRIMARY_ROUTER: "安定性の確保のために、メインルータは必ずネットワークに接続し、所有者の割り当てをしないでください。",
  DEVICE_SETTINGS_TUTORIAL: "編集したい項目をタップしてください。",
  DEVICE_SETTINGS_ACCESS_PERMISSION: "ネットワークアクセスの許可",
  DEVICE_REPORT_VULNERABILITY: "セキュリティ上の問題",
  DEVICE_REPORT_NETWORK_ATTACK: "ネットワーク攻撃",
  DEVICE_REPORT_WEB_THREAT: "Web脅威",
  DEVICE_REPORT_RANSOMWARE: "ランサムウェアに関連するWebサイト",
  DEVICE_REPORT_REMOTE_ACCESS: "リモートアクセス",
  DEVICE_REPORT_NUMBER_FOUND: "{0}件",
  DEVICE_REPORT_NUMBER_PREVENTED: "{0}件",
  DEVICE_REPORT_NUMBER_FIXED: "{0} 件",
  DEVICE_REPORT_NUMBER_BLOCKED: "{0} 件",
  DEVICE_REPORT_FOUND_LAST_MONTH: "過去30日間に検出",
  DEVICE_REPORT_PREVENTED_LAST_MONTH: "過去30日間にブロック",
  DEVICE_REPORT_FIXED_LAST_MONTH: "過去30日間に修正",
  DEVICE_REPORT_BLOCKED_LAST_MONTH: "過去30日間にブロック",
  DEVICE_REPORT_NO_NETWORK_ATTACK: "ネットワーク攻撃は検知されていません",
  DEVICE_REPORT_NO_WEB_THREAT: "Web脅威は検知されていません",
  DEVICE_REPORT_NO_VULNERABILITY: "セキュリティ上の問題は検知されていません",
  DEVICE_REPORT_NO_RANSOMWARE: "ランサムウェアに関連するWebサイトは検知されていません",
  DEVICE_REPORT_NO_REMOTE_ACCESS: "リモートアクセスは検知されていません",
  DEVICE_REPORT_ADD_TO_WTP_LIST: "許可リストに追加",
  DEVICE_REPORT_ADDED_TO_WTP_LIST: "許可リストに追加されました。（<a href=''>リスト一覧へ</a>）",
  DEVICE_REPORT_ADD_TO_WTP_DIALOG_TITLE: "許可リストに追加しますか？",
  DEVICE_REPORT_ADD_TO_WTP_DIALOG_MESSAGE: "リストに追加されると、このWebサイトへのアクセスは常に許可されます。\n\nこのWebサイトは安全でない可能性があります。",
  DEVICE_REPORT_ADD_TO_RAP_LIST: "今後このプログラムをブロックしない",
  DEVICE_REPORT_ADDED_TO_RAP_LIST: "許可リストに追加しました。 (<a href=''>詳細を表示</a>)",
  DEVICE_REPORT_ADD_TO_RAP_DIALOG_TITLE: "{0}を{1}の許可リストに追加しますか?",
  DEVICE_REPORT_ADD_TO_RAP_DIALOG_MESSAGE: "許可リストのプログラムは、{0}へのリモートアクセスが可能になります。",
  DEVICE_REPORT_PROGRAM_NOTIFICATION_ON: "このプログラムの接続については今後通知しない",
  DEVICE_REPORT_PROGRAM_NOTIFICATION_OFF: "通知はオフです (<a href=''>通知をオンにする</a>)",
  DEVICE_OFFLINE_DESC: "デバイスを確認するには、インターネットへ接続してください。",
  DEVICE_POPOVER_DISCOVER_TITLE: "デバイスをより正確に探索しましょう",
  DEVICE_POPOVER_DISCOVER_MESSAGE: "ご家庭のネットワーク内にあるデバイスの電源を入れると、 " + PROD_NAME + " はより高い精度でデバイスを見つけることができます。 <a href=http://discover-device>詳細はこちら</a>",
  ISSUE_TITLE_PASSWORDLESS: "安全性の高いパスワードが必要です。",
  IMAGE_CROPPER_TITLE: "移動と拡大",
  FAMILY_HOUSEHOLD: '家族共用',
  FAMILY_GUEST: 'ゲスト',
  FAMILY_ADD_MEMBER: "メンバーの登録",
  FAMILY_ADD_HINT: "デバイスを家族メンバーに割り当て、インターネットの使い方を設定できます。",
  FAMILY_NO_FAMILY: "表示できません。スマートフォンと本体をインターネットに接続してください。",
  FAMILY_TAB_REPORT: "レポート",
  FAMILY_TAB_SETTINGS: "設定",
  FAMILY_TAB_DEVICE: "デバイス",
  FAMILY_SETTINGS_NAME: "名前",
  FAMILY_SETTINGS_WEB_FILTER: "あんしんフィルタリング",
  FAMILY_SETTINGS_WEB_FILTER_HINT: "不適切なWebサイトやコンテンツへのアクセスをブロックします。",
  FAMILY_SETTINGS_APP_INSTALL: "特定アプリの利用通知",
  FAMILY_SETTINGS_APP_INSTALL_HINT: "指定したアプリを{0}が利用した際に通知します。",
  FAMILY_SETTINGS_NETWORK_CONTROL: "インターネットタイマー",
  FAMILY_SETTINGS_NETWORK_CONTROL_HINT: "{0}がインターネットを利用する時間を設定します。",
  FAMILY_SETTINGS_CONNECT_HOME: "帰宅通知",
  FAMILY_SETTINGS_CONNECT_HOME_HINT: "{0}のデバイスが午後0:00～午後10:00の間に自宅のネットワークにつながった際に通知します",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_HINT: "{0}に割り当てられたデバイスはありません。<a href=''>ここから</a>デバイスを割り当ててください。",                                              
  FAMILY_SETTINGS_SET_UP_NOW: "今すぐ設定",
  FAMILY_SETTINGS_REMOVE: "このメンバーの登録を解除",
  FAMILY_SETTINGS_REMOVE_CONFIRM_MESSAGE: "このメンバーの登録を解除してもよろしいですか？",
  FAMILY_SETTINGS_GET_NOTIFICATION: "管理アプリに通知する",
  FAMILY_SETTINGS_BLOCK: "ブロックする",
  FAMILY_SETTINGS_TIME_LIMIT: "インターネットタイマー",
  FAMILY_SETTINGS_WEB_FILTER_WEB_TITLE: "Webサイト",
  FAMILY_SETTINGS_WEB_FILTER_CONTENT_TITLE: "コンテンツ",
  FAMILY_SETTINGS_CONTENT_FILTER_GOOGLE_TITLE: "Googleのセーフサーチを有効にする",
  FAMILY_SETTINGS_CONTENT_FILTER_GOOGLE_MESSAGE: "露骨な表現を含む検索結果をブロックします。<a href=''>詳しく見る</a>",
  FAMILY_SETTINGS_CONTENT_FILTER_YOUTUBE_TITLE: "YouTubeの制限付きモードを有効にする",
  FAMILY_SETTINGS_CONTENT_FILTER_YOUTUBE_MESSAGE: "成人向けのコンテンツをブロックします。<a href=''>詳しく見る</a>",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_TITLE: "コンテンツフィルタリング",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_MESSAGE: "GoogleのセーフサーチやYouTubeの制限付きモードを有効にできるようになりました",
  FAMILY_SETTINGS_CONTENT_FILTER_DIALOG_ACTION: "有効にする",
  FAMILY_SETTINGS_WEB_FILTER_SUBTITLE: "特定のWebサイトにアクセスしたとき",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY: "Webサイトのカテゴリ",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_INFO: "カテゴリの説明",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_ADULT: "アダルト/成人向け",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_PERSONAL: "出会い",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_CRIME: "違法と思われる行為",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_DRUG: "違法と思われる薬物",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_USERDEFINED: "ブロックリストに登録されたWebサイト",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_ADULT_INFO: "子どもが閲覧するのに不適切だと広く一般に思われている、性的に露骨なコンテンツを表示する成人向けコンテンツのあるWebサイトです。",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_PERSONAL_INFO: "恋愛、デート、交際などの目的で人と出会うためのWebサイトです。",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_CRIME_INFO: "違法行為 (強盗、窃盗、法の適用の回避、詐欺、盗作など) に関連すると思われるWebサイトです。違法行為を擁護するWebサイト、アドバイスするWebサイト、レポートを販売するWebサイトが含まれます。",
  FAMILY_SETTINGS_WEB_FILTER_CATEGORY_DRUG_INFO: "違法と思われる薬物の宣伝、販売および、処方薬などの不適切な使用や方法に関するWebサイトです。",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIST: "例外リスト",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS: "承認済み/ブロックリストの設定",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_ADD: "新しいWebサイトを登録",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_OPEN: "このWebサイトを開く",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_REMOVE: "このWebサイトを削除する",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_REACH: "上限に達しました",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_URL: "リストに登録されたすべてのWebサイト数が上限の1024件に達しました。新しいWebサイトを追加するには、リストからWebサイトを削除してください。<a href=http://exception-limit-url>もっと見る</a>",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_LIMIT_MEMBER: "例外リストは最大31名分まで作成できます。新しいリストを作成するには、既存1名分のリストに登録されたすべてのWebサイトを削除し、リストを空の状態にしてください。<a href=''>詳細はこちら</a>",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_INVALID_CHARS: "使用できるのは文字、数字、およびハイフン「-」のみです",
  FAMILY_SETTINGS_WEB_FILTER_EXCEPTIONS_INVALID_FORMAT: "有効なWebサイトアドレスを入力してください",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST: "ブロックリストに追加できません",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST_WTP: "このWebサイトを{0}のブロックリストに追加するには、許可リストから削除する必要があります。許可リストは [設定] 画面にあります。<a href=''>もっと見る</a>",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_DENIED_LIST_MEMBER: "このWebサイトを{0}のブロックリストに追加するには、{1}の承認済みリストから削除する必要があります。{2}の承認済みリストは{3}の [設定] 画面にあります。<a href=''>もっと見る</a>",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_ALLOWED_LIST: "承認済みリストに追加できません",
  FAMILY_SETTINGS_WEB_FILTER_CONFLICT_ALLOWED_LIST_MEMBER: "このWebサイトを{0}の承認済みリストに追加するには、{1}のブロックリストから削除する必要があります。{2}のブロックリストは{3}の [設定] 画面にあります。<a href=''>もっと見る</a>",
  FAMILY_SETTINGS_WEB_FILTER_INVALID_FORMAT_TITLE: "Webサイトアドレスが正しくありません",
  FAMILY_SETTINGS_WEB_FILTER_INVALID_FORMAT_DETAIL: "Webサイトの名前を編集するには、有効なWebサイトアドレスを入力してください。",
  FAMILY_SETTINGS_FILTERING_UP_TO: "{0}歳以下",
  FAMILY_SETTINGS_FILTERING_AGE_LEVEL: "保護レベル",
  FAMILY_SETTINGS_FILTERING_PRETEEN: "中",
  FAMILY_SETTINGS_FILTERING_TEEN: "低",
  FAMILY_SETTINGS_FILTERING_CHILD: "高",
  FAMILY_SETTINGS_FILTERING_CUSTOM: "カスタム",
  FAMILY_SETTINGS_FILTERING_FILTERED_CATEGORTIES: "カテゴリのフィルタ",
  FAMILY_SETTINGS_FILTERING_CATES_MEDIA: "コミュニケーション/メディア",
  FAMILY_SETTINGS_FILTERING_CATES_CONTROVERSIAL: "議論の余地がある話題",
  FAMILY_SETTINGS_FILTERING_CATES_SHOPPING: "ショッピング/エンターテインメント",
  FAMILY_SETTINGS_FILTERING_WEBSITE_EXCEPT: "Webサイトの例外設定",
  FAMILY_SETTINGS_FILTERING_DIALOG_NO_CATES: "カテゴリが選択されていません",
  FAMILY_SETTINGS_FILTERING_DIALOG_NO_CATES_MESSAGE: "「URLフィルタリング」を開始するには保護レベルまたはカテゴリを選択してください。",
  FAMILY_SETTINGS_ALLOWED_LIST: "承認済みリスト",
  FAMILY_SETTINGS_ALLOWED_WEBSITE: "承認済みリスト",
  FAMILY_SETTINGS_DENIED_LIST: "ブロックリスト",
  FAMILY_SETTINGS_DENIED_WEBSITE: "ブロック対象のWebサイト",
  FAMILY_SETTINGS_APP_FILTER_CATEGORY: "アプリのカテゴリ",
  FAMILY_SETTINGS_APP_FILTER_GAMES: "ゲーム",
  FAMILY_SETTINGS_APP_FILTER_GAMES_INFO: "ゲームのアプリです。",
  FAMILY_SETTINGS_APP_FILTER_ADULT: "アダルト/成人向け",
  FAMILY_SETTINGS_APP_FILTER_ADULT_INFO: "子どもが閲覧するのに不適切だと広く一般に思われている、性的に露骨なコンテンツを表示する成人向けコンテンツのあるアプリです。",
  FAMILY_SETTINGS_APP_FILTER_SOCIAL: "ソーシャルネットワーク/チャット",
  FAMILY_SETTINGS_APP_FILTER_SOCIAL_INFO: "人と人とのつながりを促進/サポートする、コミュニティ型のアプリです。インスタントメッセージやチャット機能を有するアプリも含まれます。",
  FAMILY_SETTINGS_APP_FILTER_DATING: "出会い",
  FAMILY_SETTINGS_APP_FILTER_DATING_INFO: "出会いやマッチングに関連するアプリです。",
  FAMILY_SETTINGS_APP_FILTER_SHOPPING: "ショッピング/広告",
  FAMILY_SETTINGS_APP_FILTER_SHOPPING_INFO: "物品やサービスを売買するためのアプリです。",
  FAMILY_SETTINGS_APP_FILTER_P2P: "ピアツーピア/ファイル転送",
  FAMILY_SETTINGS_APP_FILTER_P2P_INFO: "ピアツーピア(P2P)ネットワーク内で音楽、動画などのファイルを共有/転送するためのアプリです。",
  FAMILY_SETTINGS_APP_FILTER_VIEW_APP_LIST: "アプリのリストを見る。",
  FAMILY_SETTINGS_APP_INSTALL_SUBTITLE: "指定したアプリが通信を行った時に通知します",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY: "アプリのカテゴリ",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_GAME: "ゲーム",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_ADULT: "アダルト/成人向け",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_CHAT: "ソーシャルネットワーキング/チャット",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_SHOPPING: "ショッピング/広告",
  FAMILY_SETTINGS_APP_INSTALL_CATEGORY_P2P: "ピアツーピア/ファイル転送",
  FAMILY_SETTINGS_APP_INSTALL_NO_SELECTED_DIALOG_TITLE: "カテゴリが選択されていません",
  FAMILY_SETTINGS_APP_INSTALL_NO_SELECTED_DIALOG_MESSAGE: PROD_NAME +"は選択されたアプリの利用を検知することができます。アプリを選択しますか？",
  FAMILY_SETTINGS_NETWORK_CONTROL_SUBTITLE: "以下の時間帯にインターネットが利用されたときに通知を表示します",
  FAMILY_SETTINGS_NETWORK_CONTROL_BLOCK: "インターネット接続を規制",
  FAMILY_SETTINGS_NETWORK_CONTROL_BLOCK_SUBTITLE: "以下の時間帯におけるインターネットへの接続を規制します",
  FAMILY_SETTINGS_NETWORK_CONTROL_FROM: "開始",
  FAMILY_SETTINGS_NETWORK_CONTROL_TO: "終了",
  FAMILY_SETTINGS_NETWORK_CONTROL_ENTIRE_DAY_DIALOG: "タイマーが設定されていません",
  FAMILY_SETTINGS_NETWORK_CONTROL_ENTIRE_DAY_DIALOG_MESSAGE: "時間が適切に指定されていないため、{0}に対するインターネットタイマーは無効です。",
  FAMILY_SETTINGS_NETWORK_CONTROL_TAB_SCHOOL_NIGHTS: "平日",
  FAMILY_SETTINGS_NETWORK_CONTROL_TAB_WEEKEND: "週末 (金、土)",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE: "規制時間",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_SCHOOL_NIGHTS: "日曜日から木曜日",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_WEEKEND: "金曜日から土曜日",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_DESC_SCHOOL_NIGHTS: "日曜日から木曜日までの指定された時間内、インターネット利用の規制や監視を行います。",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_DESC_WEEKEND: "金曜日と土曜日の指定された時間内、インターネット利用の規制や監視を行います。",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_EXAMPLE: "設定例:",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_RESTRICT: "インターネット利用規制時間:",
  FAMILY_SETTINGS_NETWORK_CONTROL_SCHEDULE_PERIOD: "{0}の10:00 PMから{1}の05:00 AMの間",
  FAMILY_PARENTAL_CONTROL_FEATURES_DIALOG: "保護者による使用制限機能",
  FAMILY_PARENTAL_CONTROL_FEATURES_DIALOG_MESSAGE: "トレンドマイクロが提供する情報を参照して、保護者による使用制限機能についてご家族で話し合われることをお勧めします。",
  FAMILY_SETTINGS_TIME_LIMITS: "インターネットタイマー",
  FAMILY_SETTINGS_TIME_CONTROL_INTERNET: "インターネット",
  FAMILY_SETTINGS_TIME_CONTROL_TIME_PERIOD_TO: " ～ ",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_DAYS: "曜日:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_HOURS: "利用可能な合計時間:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_MINUTES: "利用可能な合計時間 (分):",
  FAMILY_SETTINGS_TIME_CONTROL_TIME_ALLOWED: "利用可能合計時間:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_TIME_PERIOD: "利用可能な時間帯:",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_COUNT: "ルール{0}",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_TEXT: "新しいルールを追加",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_BUTTON: "最初のルールの追加",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_HINT: "インターネットタイマーを使用すると、ご家族のインターネット利用時間を設定できます。",
  FAMILY_SETTINGS_TIME_CONTROL_ADD_RULE_DELETE: "このルールを削除",
  FAMILY_SETTINGS_TIME_CONTROL_TIP: "インターネットタイマー機能を活用しましょう",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_MESSAGE: "ルールを追加すると、インターネットの利用時間や利用時間帯を設定することができます",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DAYS: "ルールの作成",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DAYS_MESSAGE: "家族のスケジュールに合わせてルールを設定します",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_LIMIT: "インターネット利用時間の設定",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_LIMIT_MESSAGE: "インターネット利用可能合計時間を設定します",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_ALLOWED: "インターネット利用時間帯の指定",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_TIME_ALLOWED_MESSAGE: "インターネット利用可能な時間帯を選択します",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DONE: "最初のルール",
  FAMILY_SETTINGS_TIME_CONTROL_TIP_DONE_MESSAGE: "選択した内容に基づいてルールが設定されます",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS: "曜日の選択",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_TITLE:"このルールを設定する曜日を選択します。",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_MON: "月",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_TUE: "火",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_WED: "水",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_THU: "木",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_FRI: "金",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_SAT: "土",
  FAMILY_SETTINGS_TIME_CONTROL_SELECT_DAYS_SUN: "日",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS: "合計時間の設定",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TITLE:"{0}が1日にインターネットを利用できる合計時間を選択します。",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TITLE_HINT:"インターネット利用をブロックするまでの合計時間",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_TIME_LIMIT:"インターネット利用可能合計時間",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_NOTIFICATION_HINT: "合計時間に達した場合、管理アプリに通知します",
  FAMILY_SETTINGS_TIME_CONTROL_SET_HOURS_UNLIMITED: "設定なし",
  FAMILY_SETTINGS_TIME_CONTROL_BLOCK_APP_AFTER: "{0}利用をブロックするまでの合計時間",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED: "時間帯の設定",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_TITLE: "{0}がインターネットを利用する時間帯を選択します。",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_PERIOD_TITLE:"時間帯{0}:",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_FROM: "開始",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_TO: "終了",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_ADD_BUTTON: "別の時間帯を追加",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_BLOCK_INTERNET: "インターネット利用をブロック",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_NOTIFICATION_HINT: "(指定時間帯以外にインターネットを利用した場合)",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_ALLOWED_DELETE: "削除",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_NOT_SPECIFIED: "指定されていません",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_NOT_ALLOWED: "この時間帯は選択できません",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_NOT_ALLOWED_MESSAGE: "日付をまたいで時間帯を選択することはできません。",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_ACCESS_UNCHANGED: "タイマーが設定されていません",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_ACCESS_UNCHANGED_MESSAGE: "インターネットタイマーは無効です。",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_OVERLAY: "この時間帯はすでに選択されています",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_PERIOD_OVERLAY_MESSAGE: "別の時間帯を選択してください",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_NEEDED: "曜日が選択されていません",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_NEEDED_MESSAGE: "曜日を少なくとも1つ選択してください。",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_CONFLICT: "この曜日はすでに選択されています",
  FAMILY_SETTINGS_TIME_CONTROL_SET_TIMES_DIALOG_DAY_CONFLICT_MESSAGE: "別の曜日を選択してください。",
  FAMILY_SETTINGS_TIME_CONTROL_DELETE_RULE_DIALOG: "このルールを削除",
  FAMILY_SETTINGS_TIME_CONTROL_DELETE_RULE_DIALOG_MESSAGE: "このルールを削除してもよろしいですか?",
  FAMILY_SETTINGS_TIME_CONTROL_EVERYDAY_HAS_RULE: "すべての曜日にルールが設定されています",
  FAMILY_SETTINGS_TIME_CONTROL_EVERYDAY_HAS_RULE_MESSAGE: "1日に設定可能なルールは1つのみです。<a href=http://more>もっと見る</a>",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE: "設定内容の確認",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_HOUR_ALLOWED: "のインターネットの利用が可能です",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_TIME_PERIOD: "利用可能な時間帯: ",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_NOTIFICATION_ONLY: "次の時間帯を除き通知が送信されます:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_NO_TIME_LIMIT_BLOCK: "インターネットの利用が可能な時間帯:",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_AM: "午前",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_PM: "午後",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_YOUTUBE: "{0}のYouTube利用が可能です",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_COMPLETE_INTERNET: "{0}のインターネットの利用が可能です ({1}のYouTube利用を含む)",
  FAMILY_SETTINGS_TIME_CONTROL_EDIT_RULE_NAME: "ルール名",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_ALLOWED: "利用可能",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_NOTIFICATION_ONLY: "通知のみ",
  FAMILY_SETTINGS_TIME_CONTROL_PERIOD_BLOCKED:"利用不可",
  FAMILY_SETTINGS_PROMOTE_FILTERING: "新しいフィルタリングの設定ができます",
  FAMILY_SETTINGS_PROMOTE_TIME_LIMITS: "YouTube利用時間を設定できます",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_CANCELED_DIALOG: "ルールは翌日に更新されます",
  FAMILY_SETTINGS_TIME_CONTROL_RULE_CANCELED_DIALOG_MESSAGE: "本日のタイマー設定はキャンセルされているため、変更はルール適用の翌日に有効になります。",
  FAMILY_TIME_LIMITS_PROMOTE_YOUTUBE: "ここをタップするとYouTube利用時間を設定できます",
  FAMILY_SETTINGS_CONNECT_HOME_SUBTITLE: "選択したデバイスが午後0:00～午後10:00の間に自宅のネットワークにつながった際に通知します。",
  FAMILY_SETTINGS_CONNECT_HOME_SELECT: "デバイスの選択",
  FAMILY_SETTINGS_CONNECT_HOME_NO_SELECTED_DIALOG_TITLE: "デバイスが選択されていません",
  FAMILY_SETTINGS_CONNECT_HOME_NO_SELECTED_DIALOG_MESSAGE: " デバイスを選択しない場合、" + PROD_NAME + "から帰宅通知を送信できません。今すぐデバイスを選択しますか。",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_DIALOG_TITLE: "デバイスが割り当てられていません",
  FAMILY_SETTINGS_CONNECT_HOME_NO_DEVICE_DIALOG_MESSAGE: PROD_NAME + "は家族に割り当てられたデバイスがある場合のみ、帰宅通知を送信できます。デバイスを割り当てますか？",
  FAMILY_INTERNET_USE_REPORT:"インターネット利用状況レポート",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT: "インターネット利用状況レポート",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT_HINT: "家族が利用したアプリや閲覧したWebサイトを記録します",
  FAMILY_SETTINGS_CREATE_USAGE_REPORT_TOAST: "インターネット利用状況が{0}さんのレポートに記録されます",
  FAMILY_SETTINGS_YOUTUBE_LIMIT: "{0}利用時間",
  FAMILY_SETTINGS_YOUTUBE_NO_LIMIT: "ブロックしない",
  FAMILY_SETTINGS_YOUTUBE_DURING_LIMIT: "利用可能合計時間 ({0}) 中:",
  FAMILY_REPORT_WEB_FILTER_TITLE: "{1}のWebサイトに{0}回アクセスしようとしました。",
  FAMILY_REPORT_WEB_FILTER_TITLE_SINGLE: "{0}のカテゴリのWebサイトに1回アクセスしようとしました。",
  FAMILY_REPORT_WEBSITE_ON_DENIED_LIST: "ブロックリストにある{0}件のWebサイトを閲覧しようとしました",
  FAMILY_REPORT_WEBSITES_ON_DENIED_LIST: "ブロックリストにある{0}件のWebサイトを閲覧しようとしました",
  FAMILY_REPORT_WEB_FILTER_TIME: "{0} と {1}の間に保護されました",
  FAMILY_REPORT_WEB_FILTER_TIME_AT: "{0}に保護されました",
  FAMILY_REPORT_WEB_FILTER_TITLE_VISIT: "{1}のカテゴリのWebサイトに{0}回アクセスしました。",
  FAMILY_REPORT_WEB_FILTER_TITLE_VISIT_SINGLE: "{0}のカテゴリのWebサイトに1回アクセスしました。",
  FAMILY_REPORT_WEB_FILTER_TIME_VISIT: "{0} と {1}の間にアクセスされました",
  FAMILY_REPORT_WEB_FILTER_TIME_AT_VISIT: "{0}にアクセスしました",
  FAMILY_REPORT_WEB_FILTER_TIME_AT_ALLOW: "承認された時刻: {0}",
  FAMILY_REPORT_APP_INSTALL_TITLE: "{0} つの{1}アプリがインストールされました。",
  FAMILY_REPORT_APP_INSTALL_TITLE_SINGLE: "{0}アプリが見つかりました。",
  FAMILY_REPORT_APP_INSTALL_TIME: "{0} と {1}の間に利用されました",
  FAMILY_REPORT_APP_INSTALL_TIME_AT: "{0}に利用されました",
  FAMILY_REPORT_NET_CONTROL_DETAIL_TITLE: "{0}にインターネットを利用しようとしました。",
  FAMILY_REPORT_CONNECT_HOME_TITLE: "自宅のネットワークにつながりました",
  FAMILY_REPORT_CONNECT_HOME_DETAIL_TITLE: "{0}に自宅のネットワークへつながりました。",
  FAMILY_REPORT_EMPTY: "レポートがありません。",
  FAMILY_REPORT_EMPTY_NO_RULE: "{0}へのルールが設定されていません。\nルールを追加してください。",
  FAMILY_REPORT_INTERNET_USE_TODAY:"本日のインターネット利用状況: ",
  FAMILY_REPORT_DAILY_LIMIT:"1日の利用可能時間",
  FAMILY_REPORT_INTERNET_PAUSE:"インターネット利用を一時停止",
  FAMILY_REPORT_INTERNET_RESUME: "インターネット利用を再開",
  FAMILY_REPORT_APP_RESUME: "再開: ",
  FAMILY_REPORT_APP_PAUSE: "一時停止: ",
  FAMILY_REPORT_LIMIT: "利用可能時間",
  FAMILY_REPORT_USED:"利用",
  FAMILY_REPORT_TOTAL:"合計利用時間",
  FAMILY_REPORT_INTERNET_BLOCK: "インターネット利用をブロック",
  FAMILY_REPORT_OUT_OF_ALLOWED_PERIODS: "利用可能時間外",
  FAMILY_REPORT_CURRENT_ALLOWED_PERIODS: "現在の利用可能な時間帯",
  FAMILY_REPORT_CANCEL_TIME_LIMITS: "本日のタイマー設定をキャンセル",
  FAMILY_REPORT_DAY_LIMIT_REACHED: "1日の利用可能合計時間に達しました",
  FAMILY_REPORT_CANCEL_LIMITS_DIALOG_MESSAGE:"キャンセル後も、{0}のインターネット利用を一時停止することができます。",
  FAMILY_REPORT_CURRENT_TIME:"現在時刻",
  FAMILY_DEVICE_EMPTY: "{0}が利用しているデバイスはありません。",
  FAMILY_DEVICE_EMPTY_ADD: "デバイスの割り当て",
  FAMILY_DEVICE_MANAGE: "デバイスの管理",
  FAMILY_DEVICE_MANAGE_EMPTY: "ご家庭内のすべてのデバイスの利用者が設定されています。タップしてデバイス利用者の確認や変更を行うことができます。",
  FAMILY_DEVICE_MANAGE_OTHER: "その他のデバイス",
  FAMILY_DEVICE_MANAGE_SHOW_ALL: "全てのデバイスを表示",
  FAMILY_DEVICE_MANAGE_SHOW_UNASSIGNED: "利用者が未設定のデバイスを表示",
  FAMILY_DEVICE_MANAGE_ALL_DEVICE_ASSIGNED: "ご家庭内のすべてのデバイスの利用者が設定されています。タップしてデバイスの利用者の確認や変更を行うことができます。",
  FAMILY_DEVICE_NO_DEVICES_ASSIGNED: "デバイスが割り当てられていません",
  FAMILY_DEVICE_NO_DEVICES_ASSIGNED_MESSAGE: PROD_NAME + " は家族に割り当てられたデバイスに応じた保護を行います。デバイスの割り当てを行いますか？",
  FAMILY_EDIT_TITLE_NAME: "名前の入力",
  FAMILY_EDIT_TITLE_STICKER: "アイコンの選択",
  FAMILY_STICKER_UNSUPPORTED_FILE_DIALOG: "サポートされていないファイルです",
  FAMILY_STICKER_UNSUPPORTED_FILE_DIALOG_MESSAGE: "アイコンを追加してください。",
  FAMILY_EDIT_TITLE_DEVICE: "デバイスの選択",
  FAMILY_EDIT_ADD_PHOTO: "画像の追加",
  FAMILY_EDIT_CHANGE_PHOTO: "画像を変更しますか？",
  FAMILY_EDIT_CHANGE_PHOTO_DETAIL: "「変更」をタップすると画像を選択できます。",
  FAMILY_EDIT_DEVICE_REASSIGN_TITLE: "デバイス利用者の変更",
  FAMILY_EDIT_DEVICE_REASSIGN_MESSAGE: "{0}から{1}へ、デバイスの利用者を変更しますか？",
  FAMILY_OFFLINE_DESC: "家族がご利用のデバイスの設定を確認するには、インターネットへ接続してください。",
  FAMILY_REPORT_OFFLINE_DESC: "レポートを確認するには、インターネットへ接続してください。",
  FAMILY_EVENT_CONTINUE_BROWSING_TITLE: "{0}からの閲覧申請があります: {1}カテゴリのWebサイト",
  FAMILY_EVENT_CONTINUE_BROWSING_DEFAULT_REASON: "このWebサイトへのアクセスが必要です。",
  FAMILY_EVENT_CONTINUE_BROWSING_ALLOW: "承認済みリストに追加",
  FAMILY_EVENT_CONTINUE_BROWSING_DISALLOW: "承認しない",
  SCAN_RESULT_TITLE_AR: "ご確認ください",
  SCAN_RESULT_DETAIL_TITLE_PASSWORD: "{0}のパスワードを変更してください。",
  SCAN_RESULT_DETAIL_DETAILS_PASSWORD: "{0}は初期パスワードを利用しています。初期パスワードを利用し続けると、ご家庭のネットワークへの攻撃リスクが高まります。",
  SCAN_RESULT_DETAIL_PASSWORD_INTRO: "現在の設定:",
  SCAN_RESULT_DETAIL_PASSWORD_URL: "サーバー : {0}",
  SCAN_RESULT_DETAIL_PASSWORD_ACCOUNT: "アカウント: {0}",
  SCAN_RESULT_DETAIL_PASSWORD_PASSWORD: "パスワード: {0}",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_TITLE: "以下の案内に従ってパスワードを変更してください。",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP1: "1. コンピュータまたはスマートフォンをルーターと同じネットワークに接続します。",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP1_ROUTER: "1. お使いのコンピュータやスマートフォン等をルータに接続してください。",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP2: "2. {0}を開き、パスワードを変更します。",
  SCAN_RESULT_DETAIL_PASSWORD_GUIDE_STEP3: "3. パスワードを変更してください。８文字以上で、文字や数字や記号を組み合わせて設定することを推奨します。",
  SCAN_RESULT_DETAIL_SKIP: "後で行う",
  SCAN_RESULT_DETAIL_RESOLVE: "完了済",
  SCAN_RESULT_FEEDBACK_HELPFUL: "お役にたちましたか？",
  SCAN_RESULT_FEEDBACK_YES: "はい",
  SCAN_RESULT_FEEDBACK_NO: "いいえ",
  SCAN_IDENTIFYING_DEVICES: "デバイス認識中",
  SCAN_LOOKING_WEAK_PASSWORD: "パスワードの安全性チェック中",
  SCAN_SCANNING_PORTS: "ポート検索中",    
  SECURITY_LOG_TITLE_IP: "IPアドレス: {0}",
  SECURITY_LOG_ACTION_STOP: "停止",
  SECURITY_LOG_ACTION_FILTER: "フィルタ済み",
  SECURITY_LOG_ACTION_BLOCK: "保護済み",
  SECURITY_LOG_ACTION_VISIT: "アクセス済み",
  SECURITY_LOG_TIME: "{0} と {1}の間に保護されました",
  SECURITY_LOG_TIME_AT: "{0}に保護されました",
  SECURITY_LOG_TIME_CONNECTED: "{0}～{1}の間に接続しました",
  SECURITY_LOG_BLOCKED_ATTACKS: "{0}件の攻撃をブロックしました",
  SECURITY_LOG_BLOCKED_ATTACK: "{0}件の攻撃をブロックしました",
  SECURITY_LOG_BLOCKED_ATTEMPTS: "({1}件の攻撃に含まれる攻撃試行回数: 合計{0}回)",
  SECURITY_LOG_BLOCKED_ATTEMPTS_SINGLE: "({1}件の攻撃に含まれる攻撃試行回数: 合計{0}回)",
  SECURITY_LOG_BLOCKED_ATTEMPT: "({1}件の攻撃に含まれる攻撃試行回数: 合計{0}回)",
  SECURITY_LOG_CATEGORY: "カテゴリ: ",
  SECURITY_LOG_RISK: "潜在的な危険: ",
  SECURITY_LOG_RISK_FREE: "処理は不要です。" + PROD_NAME + "が継続してこの種類の攻撃からデバイスを保護します。",
  SECURITY_LOG_SOURCE: "攻撃試行元: {0}",
  SECURITY_LOG_TARGET: "攻撃試行先: {0}",
  SECURITY_LOG_SEVERITY: "危険度: ",
  SECURITY_LOG_SUGGESTIONS: "アドバイス",
  SECURITY_LOG_SAFE_BROWSING: "<a href=''>ここ</a>をタップして安全なWebサイト閲覧についての情報を確認できます。",
  SECURITY_LOG_OS: "OS: ",
  SECURITY_LOG_LOCATION_FROM: "次の地域から攻撃されました",
  SECURITY_LOG_LOCATION_TO: "次の地域を攻撃しようとしました",
  SECURITY_LOG_SEE_DETAILS: "詳しく見る",
  SECURITY_LOG_GET_HELP: "ヘルプの表示",
  SECURITY_LOG_TUTORIAL: "タップすると詳細が表示されます。",
  SECURITY_LOG_NETWORK_ATTACK_ACCESS_CONTROL_TITLE: "不正アクセス",
  SECURITY_LOG_NETWORK_ATTACK_BUFFER_OVERFLOW_TITLE: "バッファオーバーフロー攻撃",
  SECURITY_LOG_NETWORK_ATTACK_DOS_TITLE: "DoS攻撃",
  SECURITY_LOG_NETWORK_ATTACK_TITLE: "ネットワーク攻撃",
  SECURITY_LOG_NETWORK_ATTACK_SCAN_TITLE: "ポートスキャン攻撃",
  SECURITY_LOG_NETWORK_ATTACK_VIRUS_TITLE: "ワームに関するネットワーク攻撃",
  SECURITY_LOG_NETWORK_ATTACK_WEB_TITLE: "サーバやクライアント端末の脆弱性を悪用した攻撃",
  SECURITY_LOG_NETWORK_ATTACK_ACCESS_CONTROL: "ハッカーによるネットワーク内のデバイスへのアクセスが試行されました。",
  SECURITY_LOG_NETWORK_ATTACK_BUFFER_OVERFLOW: "デバイスに対し、バッファオーバーフロー攻撃が試行されました。",
  SECURITY_LOG_NETWORK_ATTACK_DOS: "ネットワークに対する不要なリクエストでインターネットアクセスを中断させる攻撃が試行されました。",
  SECURITY_LOG_NETWORK_ATTACK: "ネットワークやデバイスに対する不正アクセスや不正操作が試行されました",
  SECURITY_LOG_NETWORK_ATTACK_SCAN: "攻撃者がネットワークに侵入できるオープンポートの有無が検索されました",
  SECURITY_LOG_NETWORK_ATTACK_VIRUS: "感染したデバイスによる不正通信が試行されました",
  SECURITY_LOG_NETWORK_ATTACK_WEB: "インターネットを閲覧しているユーザへの攻撃が試行されました。",
  SECURITY_LOG_REMOTE_ACCESS_ALLOWED: "{0}への接続が承認されました",
  SECURITY_LOG_REMOTE_ACCESS_CONNECTION_ALLOWED: "1件の接続が承認されました",
  SECURITY_LOG_REMOTE_ACCESS_CONNECTIONS_ALLOWED: "{0}件の接続が承認されました",
  SECURITY_LOG_REMOTE_ACCESS_BLOCKED: "{0}への接続をブロックしました",
  SECURITY_LOG_REMOTE_ACCESS_ATTEMPT_BLOCKED: "1件の接続の試行をブロックしました",
  SECURITY_LOG_REMOTE_ACCESS_ATTEMPTS_BLOCKED: "{0}件の接続の試行をブロックしました",
  SECURITY_LOG_REMOTE_ACCESS_RISK: "このソフトウェアの接続を承認すると、ご使用のネットワークやデバイスに第三者が直接接続できるようになり、個人情報などにアクセスされる可能性があります。",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE: "不明なリクエストは拒否してください",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE_REMOVE: "不要な接続の試行に注意してください",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_TITLE_NOTIFY: "外部からのネットワーク接続を制限できます",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC: "テクニカルサポートを名乗る人物からの電話にご注意ください。連絡元のテクニカルサポートに心あたりがあるか、今一度ご確認ください。<a href=http://Remote_Access>もっと見る</a>",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC_REMOVE: "ハッカーがこの接続を悪用してネットワークやデバイスに不正にアクセスすることが疑われる場合は、{0}を許可リストから削除してください。",
  SECURITY_LOG_REMOTE_ACCESS_SUGGESTION_DESC_NOTIFY: "リモートアクセスツールを普段利用しない場合は、ネットワーク保護のために [リモートアクセスをブロック] を有効にしてください。<a href=http://Remote_Access>有効にする</a>",
  SECURITY_LOG_CATEGORY_ILLEGAL: "違法または禁止されたコンテンツ",
  SECURITY_LOG_CATEGORY_ILLEGAL_DESC: "このWebサイトは、違法なファイルを共有および転送するための情報またはソフトウェアを提供している可能性があります。",
  SECURITY_LOG_CATEGORY_INSECURE_IOT_CONNECTION: "安全でないIoT機器の接続",
  SECURITY_LOG_CATEGORY_INSECURE_IOT_CONNECTION_DESC: "IoTデバイスにダメージを与えたり、感染させる潜在的な可能性のある、安全でないインターネット接続です。",
  SECURITY_LOG_CATEGORY_PROXY_AVOIDANCE: "プロキシ回避システム",
  SECURITY_LOG_CATEGORY_PROXY_AVOIDANCE_DESC: "このWebサイトは、プロキシサーバやWebフィルタリングシステムを回避するように設計されている可能性があります。",
  SECURITY_LOG_CATEGORY_MALICIOUS_SOFTWARE: "不正と思われるプログラム (グレーウェア)",
  SECURITY_LOG_CATEGORY_SPYWARE: "スパイウェア",
  SECURITY_LOG_CATEGORY_SPYWARE_DESC: "このWebサイトは、ユーザに無断でデータを収集し転送するソフトウェアをダウンロードする可能性があります。",
  SECURITY_LOG_CATEGORY_PHISHING: "フィッシング",
  SECURITY_LOG_CATEGORY_PHISHING_DESC: "このWebサイトは、個人情報を収集するために正規のWebサイトに偽装している可能性があります。",
  SECURITY_LOG_CATEGORY_SPAM: "スパム",
  SECURITY_LOG_CATEGORY_SPAM_DESC: "このWebサイトのURLは、スパムメールメッセージ内で使用されている可能性があります。",
  SECURITY_LOG_CATEGORY_ADWARE: "アドウェア",
  SECURITY_LOG_CATEGORY_ADWARE_DESC: "このWebサイトにより、広告などの宣伝用コンテンツを表示するためのソフトウェアがインストールされる可能性があります。",
  SECURITY_LOG_CATEGORY_VIRUS_MALWARE: "不正プログラムによる外部アクセス",
  SECURITY_LOG_CATEGORY_VIRUS_MALWARE_DESC: "このWebサイトは、不正プログラムによって利用される、盗み取った情報の格納に使用される可能性があります。",
  SECURITY_LOG_CATEGORY_DISEASE_VECTOR: "不正プログラム配信",
  SECURITY_LOG_CATEGORY_DISEASE_VECTOR_DESC: "このWebサイトは、有害なプログラムやソースコードの配布を直接的または間接的に促す可能性があります。",
  SECURITY_LOG_CATEGORY_COOKIES: "Cookie",
  SECURITY_LOG_CATEGORY_DIALERS: "ダイアラー",
  SECURITY_LOG_CATEGORY_HACKING: "ハッキング",
  SECURITY_LOG_CATEGORY_JOKE: "ジョークプログラム",
  SECURITY_LOG_CATEGORY_PASSWORD_CRACKING: "パスワードクラックアプリ",
  SECURITY_LOG_CATEGORY_REMOTE_ACCESS: "リモートアクセスツール",
  SECURITY_LOG_CATEGORY_ADSENSE: "MFA (Made for AdSense) サイト",
  SECURITY_LOG_CATEGORY_WEB_ADVERTISEMENT: "Web広告",
  SECURITY_LOG_CATEGORY_MALICIOUS_DOMAIN: "不正ドメイン",
  SECURITY_LOG_CATEGORY_MALICIOUS_DOMAIN_DESC: "不正なコンテンツが含まれている可能性のあるドメインです。",
  SECURITY_LOG_CATEGORY_C_C_SERVER: "C&Cサーバ",
  SECURITY_LOG_CATEGORY_C_C_SERVER_DESC: "コマンド&コントロール (C&C) サーバをホストしている可能性のあるサーバです。",
  SECURITY_LOG_CATEGORY_COIN_MINER: "コインマイナー",
  SECURITY_LOG_CATEGORY_COIN_MINER_DESC: "このWebサイトは、仮想通貨に関する処理を実行する不正なスクリプトやファイルをホストしている可能性があります。",
  SECURITY_LOG_CATEGORY_SCAM: "詐欺サイト",
  SECURITY_LOG_CATEGORY_SCAM_DESC: "このWebサイトは、詐欺サイトの可能性があります。",
  SECURITY_LOG_SEVERITY_HIGH: "高",
  SECURITY_LOG_SEVERITY_LOW: "低",
  SECURITY_LOG_ONLINE_STATUS: "再接続されました",
  SECURITY_LOG_OFFLINE_STATUS: "接続が切断されました",
  LOCATION_TITLE: "場所",
  LOCATION_DESCRIPTION: "場所はトレンドマイクロのサーバが検出した最新のIPアドレスから推測したものです。\n\nプロキシサーバが使用されている場合など、場所に関する情報は正確でないことがあります。",
  SETTINGS_NETWORK_AND_SECURITY: "ネットワークとセキュリティ",
  SETTINGS_NETWORK_AND_SECURITY_DESC: "これらの設定はすべてのデバイスに適用されます。",
  SETTINGS_NETWORK_SECURITY: "ネットワーク攻撃からの保護",
  SETTINGS_PRODUCT_INFORMATION: "製品情報",
  SETTINGS_WEB_THREAT_PROTECTION: "不正サイトへのアクセスブロック",
  SETTINGS_NETWORK_MANAGEMENT: "ネットワーク管理",
  SETTINGS_NETWORK_PROTECTION: "ネットワーク保護",
  SETTINGS_NETWORK_PROTECTION_DESC: "外部からの攻撃やホームネットワーク内の不審な挙動を防ぎます。",
  SETTINGS_WEBSITE_BLOCKING: "危険なWebサイトのブロック",
  SETTINGS_WEBSITE_BLOCKING_DESC: "安全ではない可能性があるWebサイトへのアクセスから保護します。",
  SETTINGS_APPROVED_LIST: "許可リスト",
  SETTINGS_APPROVED_WEBSITE: "許可されたWebサイト",
  SETTINGS_APPROVED_WEBSITE_CONFLICT: "許可リストに追加できません",
  SETTINGS_APPROVED_WEBSITE_CONFLICT_DETAIL: "このWebサイトを許可リストに追加するには、この家族メンバーのブロックリストから削除する必要があります。ブロックリストはこの家族メンバーの [設定] 画面で変更できます。<a href=http://conflict-wtp-black>もっと見る</a>",
  SETTINGS_INTRANET_PROTECTION: "ホームネットワーク内の通信保護機能",
  SETTINGS_INTRANET_PROTECTION_DESC: "ホームネットワーク内のデバイス間の不審な通信をブロックします。",
  SETTINGS_INTRANET_PROTECTION_DIALOG_TITLE: "ご注意ください:",
  SETTINGS_INTRANET_PROTECTION_DIALOG_MESSAGE: "一部の環境では、この機能をオンにすることによってネットワークが不安定になる場合があります。\n\nホームネットワーク内の通信保護機能を有効にしますか?",
  SETTINGS_SMART_FIREWALL: "大規模感染予防 (Beta)",
  SETTINGS_SMART_FIREWALL_DESC: "大規模感染の脅威からのリアルタイムでの保護を提供します。",
  SETTINGS_SMART_FIREWALL_LEARN_MORE: "この機能の詳細について",
  SETTINGS_NETWORK_ACCESS_CONTROL: "ネットワークアクセス管理",
  SETTINGS_NETWORK_ACCESS_PERMISSION: "新しいデバイスの許可",
  SETTINGS_NETWORK_ACCESS_PERMISSION_DESC: "新しいデバイスがネットワークに参加する場合は許可が必要になります",
  SETTINGS_NETWORK_ACCESS_NOTIFY_POPUP: "管理アプリに通知しますか?",
  SETTINGS_NETWORK_ACCESS_NOTIFY_POPUP_DESC: "新しいデバイスが自宅のネットワークに参加した場合に通知しますか?",
  SETTINGS_REMOTE_ACCESS_PROTECTION: "リモートアクセスからの保護",
  SETTINGS_REMOTE_ACCESS_PROTECTION_DESC: "ご使用のデバイスへのリモートアクセス接続を制限します",
  SETTINGS_REMOTE_ACCESS_PROTECTION_BLOCK: "リモートアクセスをブロック",
  SETTINGS_REMOTE_ACCESS_PROTECTION_MESSAGE: "ご使用のデバイスへのリモートアクセス接続を制限します",
  SETTINGS_REMOTE_ACCESS_PROTECTION_ADD: "プログラムを追加",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED: "1件のデバイスで許可されています",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED_PLURAL: "{0}件のデバイスで許可されています",
  SETTINGS_REMOTE_ACCESS_PROTECTION_UNAPPROVED: "許可されていません",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_PROGRAM: "プログラムの選択",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_DEVICE: "デバイスの選択",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECT_DEVICE_DESC: "{0}を許可するデバイスを選択します:",
  SETTINGS_REMOTE_ACCESS_PROTECTION_SELECTED_DEVICES: "{0}を承認しているデバイス:",
  SETTINGS_REMOTE_ACCESS_PROTECTION_OTHER_DEVICES: "その他のデバイス",
  SETTINGS_REMOTE_ACCESS_PROTECTION_EMPTY: "{0}を許可しているデバイスはありません。\nデバイスを追加するには、[デバイスの管理] をタップします。",
  SETTINGS_REMOTE_ACCESS_PROTECTION_APPROVED_PROGRAM: "許可されたプログラム",
  SETTINGS_REMOTE_ACCESS_PROTECTION_MANAGE_DEVICES: "デバイスの管理",
  SETTINGS_REMOTE_ACCESS_PROTECTION_REMOVE_PROGRAM: "許可リストから削除",
  SETTINGS_NOTIFICATIONS: "通知",
  SETTINGS_NOTIFICATIONS_NETWORK_ATTACKS_BLOCKED: "ネットワーク攻撃から保護されたとき",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION: "リモートアクセスからの保護",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_NONE: "通知しない",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_BLOCKED: "リモートアクセス接続がブロックされたときに通知する",
  SETTINGS_NOTIFICATIONS_REMOTE_ACCESS_PROTECTION_ALL: "すべてのリモートアクセス接続について通知する",
  SETTINGS_NOTIFICATIONS_DANGEROUS_WEBSITE_BLOCKED: "安全でないWebサイトをブロック",
  SETTINGS_NOTIFICATIONS_DANGEROUS_FILE_BLOCKED: "安全でないファイルをブロック",
  SETTINGS_NOTIFICATIONS_DEVICE_VULNERABILITIES_FOUND: "デバイスのセキュリティ上の問題が発見されたとき",
  SETTINGS_NOTIFICATIONS_LICENSE_RENEWAL: "サービス有効期限の更新",
  SETTINGS_NOTIFICATIONS_SURVEYS: "サーベイ",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_NONE: "通知しない",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_HIGH_SEVERITY: "攻撃の深刻度が高いものだけ通知",
  SETTINGS_NETWORK_ATTACK_NOTIFICATION_ALL: "全ての攻撃を通知する",
  SETTINGS_SECURITY_WARNINGS: "セキュリティに関する通知",
  SETTINGS_NEW_DEVICE_ADDED: "新しいデバイスの通知",
  SETTINGS_ACCOUNT: "アカウント情報",
  SETTINGS_ACCOUNT_TRENDMICRO: "トレンドマイクロアカウント",
  SETTINGS_ACCOUNT_SUBSCRIPTION: "ライセンス",
  SETTINGS_ACCOUNT_SUBSCRIPTION_EXPIRES: "有効期限: {0}",
  SETTINGS_ACCOUNT_SUBSCRIPTION_EXPIRED: "有効期限終了: {0}",
  SETTINGS_ACCOUNT_SUBSCRIPTION_MONTHLY: "サービス版 (月)",
  SETTINGS_ACCOUNT_SUBSCRIPTION_YEARLY: "サービス版 (年)",
  SETTINGS_ACCOUNT_SUBSCRIPTION_ACTIVATED: "有効",
  SETTINGS_ACCOUNT_SUBSCRIPTION_DETAILS: "登録情報の詳細",
  SETTINGS_ACCOUNT_GO_TO_MY_ACCOUNT: "こちらからご確認ください",
  SETTINGS_ACCOUNT_RENEW: "更新する",
  SETTINGS_ABOUT_AND_HELP: "ヘルプとバージョン",
  SETTINGS_PAIRING_CODE: "ペアリングコード",
  SETTINGS_STATION_CODE: "ステーションコード",
  SETTINGS_ABOUT: "バージョン情報",
  SETTINGS_HELP: "ヘルプ",
  SETTINGS_SEND_LOG: "ログを送信",
  SETTINGS_SEND_LOG_SUBJECT: PROD_NAME_SHORT + " トラブルシューティングログ",
  SETTINGS_SEND_LOG_BODY: "サポート ID: {0}\n時刻: {1}",
  SETTINGS_SUPPORT: "サポート ID: {0} - 送信済: {1}",
  SETTINGS_CRASH_REPORT: "端末のクラッシュ情報をトレンドマイクロに送信する",
  SETTINGS_UBM: "製品使用データをトレンドマイクロに送信する",
  SETTINGS_UBM_DETAIL: "これらの情報は匿名でトレンドマイクロに送信されます",
  SETTINGS_STATION: "本体の管理",
  SETTINGS_STATION_DISCONNECT: "本体との接続を解除する",
  SETTINGS_STATION_DISCONNECT_DESC: "この管理アプリを本体との接続から解除します",
  SETTINGS_STATION_RESET: "本体をリセットする",
  SETTINGS_STATION_RESET_DESC: "全てのデータを本体から削除します",
  SETTINGS_SET_UP_A_NEW_STATION: "本体との接続を解除しますか？",
  SETTINGS_SET_UP_A_NEW_STATION_DIALOG_MESSAGE: "本体を管理するには、本アプリの利用が必要です。本体との接続を解除しますか？",
  SETTINGS_RESET_STATION: "リセットしますか？",
  SETTINGS_RESET_STATION_DIALOG_MESSAGE: "アカウント情報など、本体に保存されているすべてのデータが削除されます。リセットを実行しますか？",
  SETTINGS_COMPATIBILITY_MODE: "互換モード",
  SETTINGS_COMPATIBILITY_MODE_DETAIL: "本製品ご利用後、インターネットが不安定になる場合などにオンにしてください。適合するよう動作を変更します。\n<a href=http://compatibility-off>詳しく見る</a>",
  SETTINGS_COMPATIBILITY_MODE_DETAIL_ON: "ルータに対して特別な設定をされている場合は<a href=http://compatibility-on>こちら</a>から詳細をご確認ください。",
  SETTINGS_DHCP_MODE_DETAIL: "本体はDHCPモードで起動しています。<a href=http://dhcp>詳細はこちら</a>",
  SETTINGS_FEEDBACK: "製品を評価する",
  SETTINGS_UNSECURED_DEVICES: "保護対象外のデバイス",
  SETTINGS_UNSECURED_DEVICES_OTHER: "その他のデバイス",
  SETTINGS_UNSECURED_DEVICES_DESC: "保護対象外のデバイスで送受信されるトラフィックについては、ネットワーク脅威のスキャンは行われません。これらのデバイスは脅威の追跡の対象にならず、また、保護者による使用制限で管理することができません。",
  SETTINGS_UNSECURED_DEVICES_LEARN_MORE: "保護対象外のデバイスの詳細については、<a href=http://Unsecured_Devices>ここ</a>をクリックしてください。",
  SETTINGS_UNSECURED_DEVICES_EMPTY: "保護対象外のデバイスはありません",
  SETTINGS_UNSECURED_DEVICES_EMPTY_DESC: "デバイスを保護対象外とすることは一般に推奨されません。",
  SETTINGS_UNSECURED_DEVICES_ADD: "デバイスの追加",
  SETTINGS_UNSECURED_DEVICES_MANAGE: "デバイスの管理",
  ABOUT_TITLE: "トレンドマイクロ",
  ABOUT_FIRMWARE_VER_TITLE: "本体のバージョン",
  ABOUT_APP_VER_TITLE: "アプリのバージョン",
  ABOUT_DPI_VER_TITLE: "DPIパターンファイルのバージョン",
  ABOUT_MAC_TITLE: "本体MACアドレス",
  ABOUT_LICENSE: "サードパーティのライセンス情報",
  ABOUT_EULA: "使用許諾契約書",
  ABOUT_TRADEMARK: "(C) 2018 by Trend Micro Incorporated. All rights reserved. TRENDMICRO、ウイルスバスター for Home Networkのロゴ、およびt-ballロゴは、トレンドマイクロ株式会社の商標または登録商標です。その他のすべての製品または会社名は、各社の商標または登録商標です。",
  TIMEZONE: "世界標準時刻{0}",
  TIMEZONE_DESC: "自宅の現在時刻",
  TIMEZONE_POPUP_TITLE: "時間帯",
  TIMEZONE_POPUP_MSG: "時間帯は本体を最初に設定した場所に基づいて表示されます。",    
  LAST_UPDATED: "最終更新時間: {0}",
  TIMELINE_CARD_APP_LIMIT_REACHED: "1日の{1}利用可能合計時間 ({0}) に達しました",
  FAMILY_REPORT_APP_LIMIT_REACHED: "1日の{2}の{1}利用可能合計時間 ({0}) に達しました",
  TIMELINE_CARD_DIAMOND_TITLE: PROD_NAME,
  TIMELINE_CARD_DIAMOND_DESC: PROD_NAME + "によって保護されています。",
  TIMELINE_CARD_FIRST_TIME_DEVICE: "{0}件のデバイスが接続されています。",
  TIMELINE_CARD_FIRST_TIME_DEVICES: "{0}件のデバイスが接続されています。",
  TIMELINE_CARD_DEFAULT_PASSWORD_ROUTER: "ネットワークを安全に保つために、本デバイスのパスワードを変更してください。",
  TIMELINE_CARD_DEFAULT_PASSWORD: "本デバイスのパスワードを変更してください。",
  TIMELINE_CARD_DEFAULT_PASSWORD_FIXED: "パスワードは変更されました。",
  TIMELINE_CARD_WEB_THREAT: "{0}件のWeb脅威から保護されました。",
  TIMELINE_CARD_WEB_THREATS: "{0}件のWeb脅威から保護されました。",
  TIMELINE_CARD_APP_INSTALL: "{0}カテゴリのアプリ利用: 1件",
  TIMELINE_CARD_APP_INSTALL2: "{0}カテゴリのアプリ利用: 2件",
  TIMELINE_CARD_APP_INSTALLS: "{1}カテゴリのアプリ利用: {0}件",
  TIMELINE_CARD_APP_INSTALL2_AND: "{0} と {1}",
  TIMELINE_CARD_NETWORK_CONTROL: "{0}にインターネットを利用しようとしました。",
  TIMELINE_CARD_NETWORK_CONTROLS: "{0}から{1}の間にインターネットを利用しようとしました。",
  TIMELINE_CARD_NETWORK_CONTROLS_AT: "{0}にインターネットを利用しようとしました。",
  TIMELINE_CARD_NETWORK_CONTROLS_LIST: "以下の利用可能時間外でのインターネットの利用を試みました:",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT: "{0}から{1}の間にインターネットへの接続をしました。",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT_AT: "{0}にインターネットへの接続をしました。",
  TIMELINE_CARD_NETWORK_CONTROLS_VISIT_LIST: "以下の時間内にインターネットを利用しました:",
  TIMELINE_CARD_DEVICE_JOIN: "デバイスが追加されました。",
  TIMELINE_CARD_NETWORK_ATTACK: "{0} つのネットワーク攻撃から保護されました",
  TIMELINE_CARD_NETWORK_ATTACKS: "{0} つのネットワーク攻撃から保護されました",
  TIMELINE_CARD_WEBSITE_FILTER: "{category}のカテゴリのWebサイトへのアクセスを{0}回検知しました。",
  TIMELINE_CARD_WEBSITE_FILTERS: "{category}のカテゴリのWebサイトへのアクセスを{0}回検知しました。",
  TIMELINE_CARD_WEBSITE_VISITED: "{0}つの{category}のWebサイトにアクセスしました。",
  TIMELINE_CARD_WEBSITE_VISITEDS: "{0}つの{category}のWebサイトにアクセスしました。",
  TIMELINE_CARD_WEBSITE_ON_DENIED_LIST: "ブロックリストにある{0}件のWebサイトを閲覧しようとしました",
  TIMELINE_CARD_WEBSITES_ON_DENIED_LIST: "ブロックリストにある{0}件のWebサイトを閲覧しようとしました",
  TIMELINE_CARD_CONNECT_AT_HOME: "{device}が自宅のネットワークにつながりました",
  TIMELINE_CARD_REMOVE_DEVICE: "{0}がデバイス一覧から削除されました。",
  TIMELINE_CARD_REMOVE_MEMBER: "{0}が家族一覧から削除されました。",
  TIMELINE_CARD_EOL: PROD_NAME +"のサービスが{0}に停止しています。ご不明な点は{1}にお問い合わせください。",
  TIMELINE_CARD_DIAMOND_APP_INSTALL: PROD_NAME + "アプリが他のデバイスにインストールされています。",
  TIMELINE_CARD_DAILY_SCAN_TITLE: "定期セキュリティチェック",
  TIMELINE_CARD_DAILY_SCAN_NO_ISSUE: "{0}にセキュリティチェックが完了し、脅威は発見されませんでした。ご利用のデバイスは自動的に毎日チェックされます。",
  TIMELINE_CARD_DAILY_SCAN: "{0}にセキュリティチェックが完了しました。ご利用のデバイスは自動的に毎日チェックされます。",
  TIMELINE_CARD_OWNED_BY: "{0}が利用",    
  TIMELINE_CARD_RANSOMWARE: "1件のランサムウェアに関するWebサイトから保護されました。",
  TIMELINE_CARD_RANSOMWARES: "{0}件のランサムウェアに関するWebサイトから保護されました。",  
  TIMELINE_CARD_RAP_CONNECTION_BLOCKED: "1件のリモートアクセス接続をブロックしました",
  TIMELINE_CARD_RAP_CONNECTIONS_BLOCKED: "{0}件のリモートアクセス接続をブロックしました",
  TIMELINE_CARD_RAP_CONNECTION_ALLOWED: "{0}でリモートアクセス接続が開始されました",
  TIMELINE_CARD_RAP_CONNECTIONS_ALLOWED: "{0}で{1}件のリモートアクセス接続が開始されました",
  TIMELINE_CARD_TIME_LIMIT_REACHED: "1日のインターネット利用可能合計時間 ({0}) に達しました",
  TIMELINE_CARD_TAP_TO_LEARN_MORE: "詳細を見る",
  TIMELINE_CARD_CONTINUE_BROWSING: "{0}からの閲覧申請があります: {1}カテゴリのWebサイト",
  TIMELINE_CARD_CONTINUE_BROWSING_ALLOW: "{0}カテゴリに属する1件のWebサイトの閲覧申請が承認されました。",
  TIMELINE_CARD_CONTINUE_BROWSING_ALLOWS: "{1}カテゴリに属する{0}件のWebサイトの閲覧申請が承認されました。",
  TIMELINE_CARD_BOX_STATUS_CHANGED_OFFLINE: "本体がインターネットに接続されていません",
  TIMELINE_CARD_BOX_STATUS_CHANGED_ONLINE: "本体の接続が切断されていましたが、現在再接続されています。",
  TIMELINE_CARD_FEATURE_UPDATED: "機能が更新されました",
  TIMELINE_CARD_FIRMWARE_UPDATED: "セキュリティの最新パターンがインストールされました",
  TIMELINE_CARD_RENEWED: "ホームネットワークは" + PROD_NAME + "により保護されています。",
  TIMELINE_CARD_STATION_TITLE: PROD_NAME_SHORT + "本体",
  TIMELINE_CARD_NETWORK_ACCESS: "ホームネットワークへの参加を要求しました",
  TIMELINE_CARD_NETWORK_ACCESS_APPROVED: "ホームネットワークへの参加が許可されました",
  TIMELINE_CARD_NETWORK_ACCESS_BLOCKED: "ホームネットワークからブロックされました",
  TIMELINE_STATUS_CHECKING_DEVICE_TITLE_1: "保護を",
  TIMELINE_STATUS_CHECKING_DEVICE_TITLE_2: "開始しています",
  TIMELINE_STATUS_ACTION_REQUIRED_TITLE_1: "確認",
  TIMELINE_STATUS_ACTION_REQUIRED_TITLE_2: "してください",
  TIMELINE_STATUS_DISCONNECT_TITLE_1: "インターネットに",
  TIMELINE_STATUS_DISCONNECT_TITLE_2: "接続されていません",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE: "デバイスは",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE_1: "デバイスは",
  TIMELINE_STATUS_DEVICE_PROTECTED_TITLE_2: "保護されています",
  TIMELINE_STATUS_DEVICE_BLOCKED_TITLE_1: "デバイスが",
  TIMELINE_STATUS_DEVICE_BLOCKED_TITLE_2: "ブロックされました",
  TIMELINE_STATUS_PROTECTION_DISABLED_TITLE_1: "保護機能が",
  TIMELINE_STATUS_PROTECTION_DISABLED_TITLE_2: "無効です",
  TIMELINE_STATUS_EXPIRED_TITLE_1: "サービス有効期限が",
  TIMELINE_STATUS_EXPIRED_TITLE_2: "終了しています",
  TIMELINE_STATUS_NEW_NOTIFICATIONS_ABOVE: "新しい通知があります",
  TIMELINE_SCANBTN_CHECK_TITLE_1: "安全性を確認する",
  TIMELINE_SCANBTN_CHECK_TITLE_2: "安全性を確認する",
  TIMELINE_SCANBTN_SCAN_TITLE_1: "進捗を確認する",
  TIMELINE_SCANBTN_REPORT_TITLE_1: "確認結果を見る",
  TIMELINE_DIALOG_SCAN: "ネットワークからの攻撃を受けやすいデバイスの設定等をチェックします。",
  TIMELINE_POPOVER_ISSUE_FOUND: "{0}件の問題が発見されました。",
  TIMELINE_POPOVER_ISSUE_FOUND_SINGLE: "{0}件の問題が発見されました。",
  TIMELINE_POPOVER_SCANNING_STRING: "接続されたデバイスの\nセキュリティを確認しています。",
  TIMELINE_POPOVER_SCANNING_CHECK_DEVICE: "デバイスのチェック中: {0}",
  TIMELINE_POPOVER_SCANNING_ISSUE_FOUND: "検出された問題 : {0}",
  TIMELINE_POPOVER_NO_ISSUE: "問題は検出されませんでした",
  TIMELINE_POPOVER_SCANNED_DEVICES: "スキャンされたデバイス :",
  TIMELINE_POPOVER_LICENSE_EXPIRED: "ご利用期限が過ぎています",
  TIMELINE_POPOVER_CHECKING_DEVICE: "ネットワークの確認を開始します",
  TIMELINE_POPOVER_CHECKING_DEVICE_1: "ネットワークを確認しています",
  TIMELINE_POPOVER_CHECKING_DEVICE_2: "もうしばらくお待ちください",
  TIMELINE_POPOVER_FIRST_TIME_DESC: PROD_NAME + "がデバイスを検出し、保護を開始しています。",
  TIMELINE_POPOVER_FIRST_TIME_DESC_1: PROD_NAME + "がデバイスを検出し、保護を開始しています。",
  TIMELINE_POPOVER_FIRST_TIME_ACTION: "デバイスを見る",
  TIMELINE_POPOVER_OFFLINE_DESC: "本体がインターネットに接続されていません。本体をルータに接続し、保護を継続してください。",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_TOP: PROD_NAME + "は以下のデバイスが接続されているとご利用できません。",
  TIMELINE_POPOVER_ANOTHER_ARP_DEVICE: "デバイス :",
  TIMELINE_POPOVER_ANOTHER_ARP_DEVICE_IP: "デバイスIP : {0}",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_BOTTOM: "保護を行うために、こちらのデバイスを切断するか<a href=http://vendor>{0}</a>にお問い合わせください。",
  TIMELINE_POPOVER_ANOTHER_ARP_DESC_MID: "こちらのデバイスはあなたのネットワークを監視しています。",
  TIMELINE_POPOVER_BOX_UPDATING: "本体にアップデートがあります。アップデートは1分以内に完了します。アップデートが完了したら再度保護が開始されます。",
  TIMELINE_POPOVER_SURVEY_TITLE: "ご意見・ご感想お待ちしております",
  TIMELINE_POPOVER_SURVEY_MESSAGE: PROD_NAME + "の改良のためにご意見をお寄せください。",
  TIMELINE_POPOVER_SURVEY_ACTION: "サーベイを行う",
  TIMELINE_POPOVER_WHATSNEW_SEE_MORE: "上記以外にも多数の新機能があります",
  TIMELINE_POPOVER_EXPIRED_RENEW: "サービス有効期限が終了しています。再度保護を開始するために更新を行ってください。",
  TIMELINE_POPOVER_EXPIRED_RENEW_JP: "再度保護を開始するために、トレンドマイクロアカウントにログインまたは下の [更新する] をタップして更新してください。",
  TIMELINE_POPOVER_EXPIRED: "メールをご確認いただくか、サポートにお問い合わせください。",
  TIMELINE_POPOVER_EXPIRED_JP: "メールをご確認いただくか、トレンドマイクロアカウントにログインし、更新してください。",
  TIMELINE_POPOVER_EXPIRED_ANZ: "更新するには、トレンドマイクロアカウントにログインしてください。<a href=http://expired>詳しく見る</a>",
  TIMELINE_POPOVER_EXPIRED_CONTACT_SUPPORT: "お問い合わせ",
  TIMELINE_OFFLINE_DESC: "ホームネットワークのセキュリティ状態を確認するには、インターネットへ接続してください。",
  TIMELINE_BTN_TRY_AGAIN: "再試行",
  TIMELINE_PROMOTION_WTP_CONTENT: "すべての接続されたデバイスは" + PROD_NAME_SHORT + "によってWeb脅威から保護されています。",
  TIMELINE_PROMOTION_WTP_LINK: "今すぐテストする",
  TIMELINE_TIP: "ここからタイムラインを確認できます",
  TIMELINE_TIP_MESSAGE: "ここをタップするとタイムラインが表示されます",
  TIMELINE_ACTION_TITLE_NETWORK_ATTACK: "ネットワーク攻撃",
  TIMELINE_ACTION_TITLE_WEB_THREAT: "Web脅威",
  TIMELINE_ACTION_TITLE_RANSOMWARE: "ランサムウェアに関連するWebサイト",
  TIMELINE_ACTION_TITLE_WEB_FILTERING: "不適切なWebサイト",
  TIMELINE_ACTION_TITLE_NETWROK_CONTROL: "利用可能時間外での使用",
  TIMELINE_ACTION_TITLE_APP_INSTALL: "不適切なアプリ",
  TIMELINE_ACTION_TITLE_RAP_BLOCKED: "リモート接続",
  TIMELINE_ACTION_TITLE_TIME_LIMIT_REACHED: "利用可能合計時間に到達",
  DASHBOARD_TIP: "ダッシュボードへようこそ",
  DASHBOARD_TIP_MESSAGE: "ダッシュボードには" + PROD_NAME_SHORT + "のステータスが表示されます。",
  DASHBOARD_CARD_SUMMARY: "概要",
  DASHBOARD_CARD_SUMMARY_LAST_7_DAYS: "過去7日間",
  DASHBOARD_CARD_SUMMARY_LAST_30_DAYS: "過去30日間",
  DASHBOARD_CARD_SUMMARY_SHOW_MORE: "さらに見る",
  DASHBOARD_CARD_SUMMARY_SHOW_LESS: "概要を見る",
  DASHBOARD_CARD_SUMMARY_TAG_SECURITY: "セキュリティ",
  DASHBOARD_CARD_SUMMARY_TAG_FAMILY: "家族一覧",
  DASHBOARD_CARD_BLOCKED_UNIT: "回",
  DASHBOARD_CARD_DEVICE_UNIT: "台",
  DASHBOARD_CARD_VISITED_UNIT: "件",
  DASHBOARD_CARD_USED_UNIT: "個",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_EVENTS: "保護者による使用制限イベントまたはブロックした脅威はありません。",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_SECURITY_EVENTS: "台のデバイスが保護されています。ブロックした脅威はありません。",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_SECURITY_EVENTS_PLURAL: "台のデバイスが保護されています。ブロックした脅威はありません。",
  DASHBOARD_CARD_SUMMARY_EVENT_NO_PARENTAL_CONTROL_EVENTS: "保護者による使用制限イベントはありません。",
  DASHBOARD_CARD_SUMMARY_EVENT_NETWORK_ATTACK: "ネットワーク攻撃をブロック", // NETWORK_ATTACK : 4,
  DASHBOARD_CARD_SUMMARY_EVENT_NETWORK_ATTACKS: "ネットワーク攻撃をブロック",
  DASHBOARD_CARD_SUMMARY_EVENT_INTERNAL_ATTACK: "ホームネットワーク内にあるデバイスからの攻撃をブロック", // Not in this revision
  DASHBOARD_CARD_SUMMARY_EVENT_WEB_THREAT: "Webからの脅威をブロック",  // WEB_THREAT : 5,
  DASHBOARD_CARD_SUMMARY_EVENT_WEB_THREATS: "Webからの脅威をブロック",
  DASHBOARD_CARD_SUMMARY_EVENT_RANSOMWARE: "ランサムウェアに関連するWebサイトをブロック", // RANSOMWARE : 15,
  DASHBOARD_CARD_SUMMARY_EVENT_RANSOMWARES: "ランサムウェアに関連するWebサイトをブロック",
  DASHBOARD_CARD_SUMMARY_EVENT_REMOTE_ACCESS_BLOCKED: "リモート接続をブロック", // RAP_BLOCKED : 24,
  DASHBOARD_CARD_SUMMARY_EVENT_REMOTE_ACCESSES_BLOCKED: "リモート接続をブロック",
  DASHBOARD_CARD_SUMMARY_EVENT_DEVICE_PROTECT: "保護されているデバイスの総数", // 
  DASHBOARD_CARD_SUMMARY_EVENT_DEVICES_PROTECT: "保護されているデバイスの総数",
  DASHBOARD_CARD_SUMMARY_EVENT_WEBSITE_BLOCK: "不適切なWebサイトをブロックまたは閲覧", // WEB_FILTERING : 6,
  DASHBOARD_CARD_SUMMARY_EVENT_WEBSITES_BLOCK: "不適切なWebサイトをブロックまたは閲覧",
  DASHBOARD_CARD_SUMMARY_EVENT_ATTEMPT_BLOCK: "利用可能時間外のインターネット利用をブロック",  // NETWROK_CONTROL : 8,
  DASHBOARD_CARD_SUMMARY_EVENT_ATTEMPTS_BLOCK: "利用可能時間外のインターネット利用をブロック",
  DASHBOARD_CARD_SUMMARY_EVENT_DAY_TIME_LIMIT_REACH: "インターネット利用可能合計時間に達した回数", // TIME_LIMIT_REACH :25   
  DASHBOARD_CARD_SUMMARY_EVENT_DAYS_TIME_LIMIT_REACH: "インターネット利用可能合計時間に達した回数", 
  DASHBOARD_CARD_SUMMARY_EVENT_INAPPROPRATE_APP_USE: "不適切なアプリの使用回数", // APP_INSTALL : 7,
  DASHBOARD_CARD_SUMMARY_EVENT_INAPPROPRATE_APPS_USE: "不適切なアプリの使用回数",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_ATTACK_BLOCKED: "件のブロックした新しい攻撃",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_ATTACKS_BLOCKED: "件のブロックした新しい攻撃",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_EVENT: "件の新しいイベント",
  DASHBOARD_CARD_SUMMARY_EVENT_NEW_EVENTS: "件の新しいイベント",
  DASHBOARD_CARD_SUMMARY_EVENT_NAME_REMOVED: "削除済みの利用者",
  DASHBOARD_CARD_FAMILY_MEMBERS: "家族一覧",
  DASHBOARD_CARD_FAMILY_MEMBERS_NO_FAMILY_MEMBER: "デバイスを家族メンバーに割り当て、インターネット利用に関するルールを設定することができます。",
  DASHBOARD_CARD_FAMILY_MEMBERS_ASSIGN_NOW: "割り当てる",
  DASHBOARD_CARD_TOP_ATTACKED_DEVICES: "最も攻撃を受けたデバイス",
  DASHBOARD_CARD_TOP_ATTACKED_DEVICES_NO_DEVICE: "攻撃を受けたデバイスはありません。",
  DASHBOARD_CARD_NETWORK_USAGE:"ホームネットワーク使用量レポート",
  DASHBOARD_CARD_NETWORK_USAGE_NO_DATA: "There were no usages to show",
  DASHBOARD_MEMBER_PAUSED: "一時停止 {0}",
  DASHBOARD_MEMBER_NO_TIME_LEFT: "利用可能時間なし",
  DASHBOARD_MEMBER_OUT_TIME_PERIOD: "利用可能時間外",

  NETWORK_USAGE_TAB_SEVEN_DAY: "過去7日間",
  NETWORK_USAGE_TAB_THIRTY_DAY: "過去30日間",
  NETWORK_USAGE_IPV6_NOTICE: "結果にご不明点がありますか? 一部のデータはアップロードトラフィックに含まれている可能性があります。<a href=''>もっと見る</a>",

  MINI_SURVEY_OPTION_OTHER: "その他",
  MINI_SURVEY_OPTION_LATER: "後で",
  MINI_SURVEY_ACTION_SEND: "送信",
  MINI_SURVEY_COMMENT_HINT: "ここにコメントを入力してください...",
  DHCP_DIALOG_TITLE: "ルーターの設定を変更してください",
  DHCP_DIALOG_DESC: "ご利用になるには、先にお使いのルーターの設定を変更する必要があります。ルーターの設定変更後、再度お試しください。",
  DHCP_POPOVER_DESC: "ご利用になるには、先にお使いのルーターの設定を変更する必要があります。ルーターの設定変更後、再度お試しください。<a href=http://dhcpHelp>ヘルプ</a>",
  DHCP_DIALOG_DESC_NABU: "ご利用になるには、先にお使いのルーターの設定を変更する必要があります。ルーターの設定変更後、再度お試しください。",    
  DHCP_LEARN_MORE: "<a href=http://dhcpHelp>詳しく見る</a>",    
  COMPATIBILITY_DIALOG_TITLE: "互換モードをオンにします",
  COMPATIBILITY_DIALOG_DESC: "ご利用のネットワークで正しく動作するために互換モードをオンにします。\nもしルーターの設定を変更していた場合には <a href=http://compatibilityHelp>こちら</a>を参照してください。",
  PULLDOWN_REFRESH_LOADING: "読込中",
  DIAGNOSTIC_TITLE: "自己診断ツール",
  DIAGNOSTIC_TAB_COMPATIBILITY: "互換性",
  DIAGNOSTIC_TAB_HOSTS: "ホスト",
  DIAGNOSTIC_TAB_INFO: "環境情報",
  DIAGNOSTIC_STATION: "本体",
  DIAGNOSTIC_LOCALHOST: "本デバイス",
  DIAGNOSTIC_STATUS: "状態",
  DIAGNOSTIC_COMPATIBILITY_ACTION: "互換性を診断する",
  DIAGNOSTIC_HOSTS_ACTION: "ホストの確認",
  DIAGNOSTIC_NOTES: "備考",
  DIAGNOSTIC_NOTES_HINT: "例）ルータのモデル番号など",
  DIAGNOSTIC_SUBMIT: "送信",
  DIAGNOSTIC_RESULT_SUBJECT: PROD_NAME_SHORT + " 互換性診断ログ",
  DIAGNOSTIC_SPEED_TEST_TITLE: "スピードテスト (任意)",
  DIAGNOSTIC_SPEED_TEST_DESC: "スピードテストの結果を提供して頂くことによって、事前調査にかかる時間を短縮できます。<a href=''>今すぐ測定</a>",
  DIAGNOSTIC_SPEED_TEST_RESULT: "結果のURLをここにコピーしてください",
  BOX_STATUS_LOG_TITLE: "本体のステータス",
  WHATS_NEW_DETAIL_TITLE: "新機能",
  INTRANET_PROTECT_INFO_TITLE: "ネットワーク回復ガイド",
  INTRANET_PROTECT_INFO_SUBJECT: "ネットワークに再接続するには:",
  INTRANET_PROTECT_INFO_CONTENT: "1. " + PROD_NAME + " アプリを実行している端末をほかの接続方法 (4G/LTEなど) でインターネットに接続してください。\n\n2. 設定画面でホームネットワーク内の通信保護機能をオフにしてください。\n\n3. 10秒ほど待ってから、ルータを電源から取り外してください。\n\n4.さらに15秒ほど待ってから、ルータを電源に接続し、再起動してください。",

  PMAC_OFFLINE_CALL_NOW: "電話する",
  PMAC_OFFLINE_REQUEST_CALLBACK: "電話サポートを予約する",
  PMAC_OFFLINE_LINK: "ヘルプとサポートを参照する",

  PUSH_NOTIFICATION_MARKET_SURVEY: PROD_NAME + "についてのご意見をお聞かせください",
  PUSH_NOTIFICATION_PROMOTION_FAMILY: "ご家族別のセキュリティを設定するためには、デバイスの振り分けを行ってください。",

  // NABU only
  CALL_SUPPORT_DIRECTLY: "電話でのお問い合わせ: <a href=''>{0}</a>",
  PHONE_EXT: "内線{0}",
  REQUEST_CALL_FROM_SUPPORT: "電話サポートを予約する",
  REQUEST_CALL_FROM_SUPPORT_HINT: "サポート対応期限: {1} {0}",
  REQUEST_SUPPORT_CALL_DIALOG_TITLE: "電話サポートの予約",
  REQUEST_SUPPORT_CALL_DIALOG_MESSAGE: "お名前、お電話番号をご入力ください。30分以内に折り返しご連絡させていただきます。",
  REQUEST_SUPPORT_CALL_DIALOG_CONFIRMATION_TITLE: "入力情報に間違いはありませんか?",
  REQUEST_SUPPORT_CALL_DIALOG_CONFIRMATION_MESSAGE: "お名前: {0}\nお電話番号: {1}",
  REQUEST_SUPPORT_CALL_REQUESTED_DIALOG_TITLE: "予約を受け付けました",
  REQUEST_SUPPORT_CALL_REQUESTED_DIALOG_MESSAGE: "サポート対応期限: {1} {0}",
  REQUEST_SUPPORT_CALL_SENT_DIALOG_TITLE: "サポートからの連絡をお待ちください",
  REQUEST_SUPPORT_CALL_SENT_DIALOG_MESSAGE: "現在対応中です。必要な場合は、{0}の{1}以降に再度ご予約ください。",

  //Help Page
  HELP_CONTACT_SUPPORT: "サポートへのお問い合わせ",
  HELP_CALL_SUPPORT_DIRECTLY: "電話番号: <a href=''>{0}</a>",
  HELP_SECTION_TITLE_TROUBLESHOOTING: "トラブルシューティング",
  HELP_SECTION_TITLE_HOW: "操作方法",
  HELP_ITEM_TROUBLE_SLOW_INTERNET: "インターネット接続が遅い",
  HELP_ITEM_TROUBLE_DEVICE_NETWORK_ISSUE: "ネットワーク接続時に一部のデバイスがうまく動作しない",
  HELP_ITEM_TROUBLE_PLAY_GAME: "ゲーム中にエラーが発生する",
  HELP_ITEM_TROUBLE_STREAMING: "ビデオのストリーミング中にエラーが発生する",
  HELP_ITEM_TROUBLE_OTHER: "その他",
  HELP_ITEM_HOW_PROTECT_KIDS: "インターネット上で子供の安全を守るには",
  HELP_ITEM_HOW_MANAGE_DEVICES: "デバイスを管理するには",
  HELP_ITEM_HOW_BLOCK_DEVICES: "ネットワークに接続しないようデバイスをブロックするには",
  HELP_ITEM_HOW_IDENTIFY_DEVICES: "不明なデバイスを識別するには",
  HELP_ITEM_HOW_HNS_PROTECT: PROD_NAME_SHORT + "がどのようにデバイスを保護するかを確認するには",
  
  DIALOG_SETTING_COMPAT_TITLE: "ネットワーク設定",
  DIALOG_SETTING_COMPAT_MESSAGE: "サポート指定のモードを選択してください。",
  SETTING_COMPAT_MODE_0: "標準モード",
  SETTING_COMPAT_MODE_1: "互換モード",
  SETTING_COMPAT_MODE_2: "特殊互換モード",

  ANDROID_PERMISSION_CAMERA: "カメラ",
  ANDROID_PERMISSION_STORAGE: 'ストレージ',
  ANDROID_PERMISSION_REQUIRED: "{0}へのアクセスを許可してください",
  ANDROID_PERMISSION_REQUIRED_DETAIL: "スキャンするには{0}へのアクセスを許可する必要があります。許可するには [設定] をタップします。",

  // FOR FILTER TYPES
  FILTERING_ITEMS_SELECT_ALL: "すべて選択",
  FILTERING_ITEMS_EROTIC: "アダルト/ 成人",
  FILTERING_ITEMS_INTIME_APPAREL: "下着/水着",
  FILTERING_ITEMS_NUDITY: "ヌード",
  FILTERING_ITEMS_PRONOGRAPY: "ポルノ",
  FILTERING_ITEMS_SEX_EDUCATION: "性教育",
  FILTERING_ITEMS_BLOGS: "ブログ/掲示板/コミュニケーション",
  FILTERING_ITEMS_INSTANT_MSG: "チャット/メッセンジャー",
  FILTERING_ITEMS_EMAIL: "メール",
  FILTERING_ITEMS_HACKING: "ハッキング/プロキシ回避システム",
  FILTERING_ITEMS_NEWSGROUPS: "ニュースグループ/フォーラム",
  FILTERING_ITEMS_P2P: "ピアツーピア (P2P) ネットワーク",
  FILTERING_ITEMS_PHTOTO: "画像検索",
  FILTERING_ITEMS_SHARING_SERVICE: "ファイル共有サービス",
  FILTERING_ITEMS_SOFTWARE_DOWNLOAD: "ソフトウェアダウンロード",
  FILTERING_ITEMS_STREAMING_MEDIA: "ストリーミングメディア",
  FILTERING_ITEMS_SOCIAL_NETWORKKING: "ソーシャルネットワーキング",
  FILTERING_ITEMS_WEB_AD: "Web広告",
  FILTERING_ITEMS_ABORTION: "妊娠中絶",
  FILTERING_ITEMS_CULT_OCCULT: "特定の宗教/オカルト",
  FILTERING_ITEMS_GUN_CLUBS: "ガンクラブ/ハンティング ",
  FILTERING_ITEMS_ILLEAGE: "違法と思われる行為 ",
  FILTERING_ITEMS_TASTELESS: "低俗",
  FILTERING_ITEMS_VIOLENCE: "暴力/差別 ",
  FILTERING_ITEMS_WEAPONS: "武器/軍事",
  FILTERING_ITEMS_ALCOHOL: "酒/タバコ",
  FILTERING_ITEMS_AUCTIONS: "オークション",
  FILTERING_ITEMS_GAMBLING: "ギャンブル",
  FILTERING_ITEMS_SHOPPING: "ショッピング",
}